### ISSUE TITLE
Add support for kaggle datasets as a remote storage

### ISSUE THREAD

**Issue by Muhammad-Abdelsattar** [iterative/dvc#10025]
Currently kaggle has an API for creating and updating datasets and models using [kaggle-api](https://github.com/Kaggle/kaggle-api). It gives more than 100GB of private datasets for each user and unlimited storage for public ones.
I think it would be extremely useful to be supported.

**Comment by pioneerHitesh** [comment]
can i pick this one up?

**Comment by dberenbaum** [comment]
Unfortunately, we don't have the bandwidth to support additional remote types right now. If you are interested in using kaggle for remote storage, it would help to upvote and provide some more context on how it would be useful.

**Comment by skshetry** [comment]
We don't have plans to add new remote implementation ourselves. Of course, contributions are always welcome.

In the future, we have plans to offer plugin system so that we can create remotes out of tree.
Remotes like s3/azure, etc are already out of tree, but they are hardcoded in the registry.
We'll refactor this in the future to make it easier for creating new remote plugins.

I am closing this issue ticket for now.
