### ISSUE TITLE
exp: unique ids

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#10048]
btw., what happens if two people name the experiment the same way simultaneously (feels that it would have been better to have still some random id / hash in the name or something).

_Originally posted by @shcheklein in https://github.com/iterative/dvclive/pull/725#discussion_r1366078405_

**Comment by pmrowla** [comment]
> btw., what happens if two people name the experiment the same way simultaneously

This is the same as if two people that clone a git repo create identically named branches or tags. Nothing happens locally (since it's a non-issue in the local-only case).

It only matters once the two people try to push those matching Git refs. In that case, the first `dvc exp push` will succeed, and the second will fail due to the conflicting experiment (the same as when you try to push a diverged/conflicting Git branch or tag). The second user would have to either force-push (to overwrite the first person's experiment) or rename their experiment before pushing.
