### ISSUE TITLE
Simple intro use cases not working as expected

### ISSUE THREAD

**Issue by chrisrapson** [iterative/dvc#10052]
I'm experimenting with DVC, and have immediately discovered two use cases which don't work as expected for me. I've put together a couple of minimum working examples to demonstrate. But first:

``` 
$ dvc doctor
DVC version: 3.27.0 (snap)
--------------------------
Platform: Python 3.8.10 on Linux-5.15.0-87-generic-x86_64-with-glibc2.29
Subprojects:
	dvc_data = 2.18.1
	dvc_objects = 1.0.1
	dvc_render = 0.6.0
	dvc_task = 0.3.0
	scmrepo = 1.3.1
Supports:
	azure (adlfs = 2023.10.0, knack = 0.11.0, azure-identity = 1.14.1),
	gdrive (pydrive2 = 1.17.0),
	gs (gcsfs = 2023.9.1),
	hdfs (fsspec = 2023.9.1, pyarrow = 13.0.0),
	http (aiohttp = 3.8.6, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.6, aiohttp-retry = 2.8.3),
	oss (ossfs = 2021.8.0),
	s3 (s3fs = 2023.9.1, boto3 = 1.28.17),
	ssh (sshfs = 2023.7.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2023.9.1)
Config:
	Global: /home/username/.config/dvc
	System: /etc/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p5
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/nvme0n1p5
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/f63638a24a253aaf212233537891e8b3
```

1st scenario: using two local folders as repositories.
```
mkdir folder1; cd folder1
git init
dvc init
echo file1 > file1
dvc add file1
git add .gitignore file1.dvc
git commit -m "added file"
cd ..
git clone folder1 folder2
cd folder2
dvc remote add -d origin ../folder1
dvc fetch file1 -r origin  # warning
dvc checkout file1  # error
```

2nd scenario: trying to access two files in succession out of a larger repo
a) trying to fetch one file actually fetches the whole folder unless I call `dvc data status --granular` first
b) fetching the second file _claims_ success, but actually doesn't download anything. Trying to `checkout` causes an error.
```
mkdir dvc_test; cd dvc_test
git init
dvc init
mkdir -p a/b; mkdir -p a/c
echo d >> a/b/d
echo e >> a/c/e
dvc add a
dvc remote add -d storage gs://unique_bucket_name
git add a.dvc .gitignore .dvc/config
git commit -m "initialised repo"
dvc push
cd ..
git clone dvc_test dvc_test2; cd dvc_test2
# dvc fetch a/b/d  # downloads 3 files (dir + 2x files)
dvc data status --granular
dvc fetch a/b/d  # downloads 2 file (dir + a/b/d)
dvc checkout a/b/d  # works
dvc fetch a/c/e  # claims success, but no file downloaded
dvc checkout a/c/e  # error
```

Do I need to adjust my expectations, or are these bugs?

**Comment by chrisrapson** [comment]
Thanks @dberenbaum. Perhaps it would help if I outlined my expectations for the first scenario?

I assumed that DVC would operate much like git, or any other distributed version control system. For a DVCS, it doesn't matter whether the repository I'm pushing to or pulling from is local or remote, the commands and the result are the same. All clones of a repository are equal. My objective was to test some features and get comfortable with some commands without having to set up cloud storage.

What makes `folder1` an invalid dvc remote? Should I be thinking of DVC more like SVN, where there is a central master repository, and that is the single source of truth?

**Comment by pmrowla** [comment]
> What makes `folder1` an invalid dvc remote? 

DVC remotes are not the same as Git remotes. A DVC remote is not a clone of your entire repository. It is only a remote copy of the underlying object storage used for DVC-tracked files. In Git terms, the local DVC cache is like `.git/objects` but for DVC tracked files, and the DVC remote is more like a remote copy of only `.git/objects`, not the entire Git repository.

> Should I be thinking of DVC more like SVN, where there is a central master repository, and that is the single source of truth?

Your single source of truth here is still the Git repository. You should be thinking of DVC as an extension to Git, rather than an entirely separate version control system.

**Comment by chrisrapson** [comment]
Ok, I've had another go at an example using DVC with local folders. It seems to me like there are two types of DVC repositories.

1. "active", with files in the expected path, accompanying `.dvc` files next to them and versions of those files in `.dvc/cache`
2. "intermediate", which appears to consist solely of a copy of `.dvc/cache` renamed to `files`.

I can only `dvc push/pull` inside an "active" repo, and only to/from an "intermediate" repo. I can't go directly from "active" to "active". (Please let me know if there are better terms for active/intermediate.)

Can anybody explain the reasoning behind moving `.dvc/cache` to `files`? If an "intermediate" repo kept the cache at the same path, i.e. `.dvc/cache`, then would intermediate and active repos be interchangeable? Would they then be able to work like a DVCS?

```
mkdir active1; cd active1
git init
dvc init
echo file1 > file1
echo file2 > file2
dvc add file1 file2
mkdir ../intermediate1
dvc remote add -d intermediate1 ../intermediate1
git add .gitignore file2.dvc file1.dvc .dvc/config
git commit -m "added files"
dvc push
cd ..
git clone active1 active2
cd active2
dvc fetch file1
dvc checkout file1

echo file3 > file3
dvc add file3
mkdir ../intermediate2
dvc remote add intermediate2 ../intermediate2
dvc push -r intermediate2
git add .gitignore file3.dvc .dvc/config
git commit -m "added another file"

cd ../active1
git pull ../active2
dvc pull -r intermediate2
ls -la
```

**Comment by pmrowla** [comment]
> It seems to me like there are two types of DVC repositories.
>
> 2. "intermediate", which appears to consist solely of a copy of `.dvc/cache` renamed to `files`.

DVC remotes are not repositories (i.e. they are not the equivalent of a bare/server Git repository). It is not accurate to call DVC remotes an "intermediate" repository. A "DVC repository" is the entire combined Git+DVC repository (what you are calling an "active repository").

DVC remotes are just a remote storage location for DVC tracked files. DVC tracked files are pushed and fetched to/from the DVC remote storage so that anyone collaborating on the project (that has also cloned the same upstream Git+DVC repository) can also access that data. Please refer to the documentation on remotes: https://dvc.org/doc/user-guide/data-management/remote-storage#remote-storage).

DVC tracked data is not stored in Git - only the .dvc files are stored in Git but the actual file data is stored separately in the DVC cache. So sharing DVC tracked data requires pushing that DVC cache data to a remote location - i.e. the DVC remote. In Git terms, the DVC cache is like an extra object storage (in addition to your local `.git/objects/`). The DVC remote is like an extra object storage (in addition to the remote Git repository's `objects/`).

`dvc push` and `dvc fetch` are not replacements for `git push` and `git fetch`. Sharing the state of a Git+DVC repository requires doing both `git push/fetch` and `dvc push/fetch`. When you do a `git push`, Git pushes the git object data (from `.git/objects`) into the remote Git repository's `objects/` location. 

> I would be interested in understanding the design decision to move .dvc/cache to files for an intermediate repo. If an "intermediate" repo kept the cache at the same path, i.e. .dvc/cache, then would intermediate and active repos be interchangeable? Would they then be able to work like a DVCS?

DVC remote storage only contains the raw object data (the equivalent to `.git/objects/`). If you look at your `.git/` directory (or at a bare git repository directory), you will see that Git also stores additional information on top of the raw object data. Being able to clone a Git repository requires both the raw object data and this additional information.

DVC does not store this "additional information" in DVC cache or in DVC remotes. It only stores raw DVC-tracked file data. DVC is not a complete distributed version control system - it relies on Git to be the distributed version control system. DVC is an extension on top of Git that handles storing large binary files in an alternate location from `.git/objects` (in `.dvc/cache` locally and in DVC remotes).

In summary, cloning a Git+DVC repository requires cloning the remote Git repo (which does an initial `git fetch`), and then doing `dvc fetch` to get the additional DVC-tracked object data. You cannot just `cp .git/objects` to a new folder and end up with a cloned Git repository in that new folder. In the same way, you cannot just copy the contents of a DVC remote into a new folder and end up with a cloned Git+DVC repository.

> I can only dvc push/pull inside an "active" repo, and only to/from an "intermediate" repo. I can't go directly from "active" to "active".

As explained above, `dvc push/fetch` are not pushing the entire repository state, only the DVC file data. What you can do is re-use an existing DVC repository's `.dvc/cache` as a DVC remote for another repo. So you can have workflows like

```
$ git clone ssh://machine1/path/to/my-repo  # clone a Git+DVC repository from a remote machine over SSH
$ cd my-repo
$ dvc remote add -d my-ssh-remote ssh://machine1/path/to/my-repo/.dvc/cache  # use the source repository's cache as the destination repository's DVC remote
$ dvc fetch  # fetch the DVC file data (which is not included in the initial 'git clone')
```

This also works in the local case. Going back to your example, you could do

```
$ mkdir active1; cd active1
... # init active1 repo

$ cd ..
$ git clone active1 active2
$ cd active2
$ dvc remote add -d my-remote ../active1/.dvc/cache
$ dvc fetch file1
$ dvc checkout file1
```

**Comment by pmrowla** [comment]
`dvc status` and `dvc checkout` require being in an actual DVC repository. I'm not really sure what you are looking to do here.

`.dvc/cache` is also just the default cache location, you can use other directories as your DVC cache by setting `dvc cache dir` (see https://dvc.org/doc/user-guide/how-to/share-a-dvc-cache#how-to-share-a-dvc-cache).

If you want your remote to be prefixed with `.dvc/cache`, you can just set that to be your remote path (i.e. `dvc remote add my-remote /path/to/other/.dvc/cache`). The reason we don't add the `.dvc/cache` prefix by default is that remotes are normally not used as the cache for a local DVC repository. If you consider the cloud storage use case, you cannot `dvc checkout` from an AWS S3 bucket (but again, if you really wanted to you could prefix your S3 bucket like `s3://my-bucket/.dvc/cache/`).

> I think I understand everything you've written, but I'm still unsure why DVC remotes (what I called "intermediates" in my earlier comment) save the tracked data in files.

The DVC remote structure is exactly the same as the DVC cache structure. If you look at what's inside `.dvc/cache`, it contains the same `files/md5/...` directories that you see in your remotes. For an explanation on why the cache/remote structure looks like that, see: https://dvc.org/doc/user-guide/project-structure/internal-files#structure-of-the-cache-directory

**Comment by chrisrapson** [comment]
Sorry, we seem to be talking past each other. I'll try starting from the beginning again...

One of my favourite things about git (and hg), is that the repo is decentralised. I can pull from github to my laptop, push to a compute cluster through ssh, clone to a USB stick, and push back from there to any of the others. I read that DVC is ["Git for data"](https://github.com/iterative/dvc), and that I could ["Stick to the regular Git workflow"](https://dvc.org/doc/user-guide). I assumed that meant I could create a DVC repo, clone it (using `git clone` and `dvc pull`, since dvc doesn't have clone), and then I would be able to push and pull between the two. I've since realised that the DVC workflow is more like SVN than git. DVC is not intended to be decentralised, it has a central (or server or "intermediate" or "master") repository where multiple client (or "active") repositories can push and pull from.

That is what I was trying to demonstrate in my example. i.e. when I start from a DVC repo "active1", the cache is in `.dvc/cache`. After pulling once, the cache ends up in `files` ("intermediate1"). When I pull it again from there to a new location, the cache is back in `.dvc/cache` ("active2"). It's not possible to push/pull directly between "active1" and "active2", which would be expected behaviour for a git repo.

I guess I should stop at that point, and check I have understood correctly? 

If my understanding is accurate, then I'm curious why DVC was designed like that? I can't think of any reason why it wouldn't be possible to have decentralised version control for data. In fact, from my naive viewpoint, it looks like something as trivial as keeping the same cache path the same (`.dvc/cache`) for all incarnations of the repo would provide that functionality. 

Thanks for the explanations btw. They weren't what I was originally asking, but I have a much better understanding of how the cache works now.

**Comment by pmrowla** [comment]
> If my understanding is accurate, then I'm curious why DVC was designed like that?

This is because the typical use case for DVC is that the user does not want to store the entire history of every large binary file in their local repository. The full history for all of your data may be too large and impractical to keep entirely in local storage. So instead, you want to push your data into one central location (like an S3 bucket) so that it can be accessed if/when needed. Once it's needed, you would only fetch the specific versions that want locally.

Likewise, in the cases where you are using multiple repositories locally, it is still more practical to ensure that you are not duplicating any data which is re-used across those repositories. In this case, using a shared local cache between all of your local repositories is ideal, since it ensures that your local data is de-duplicated (and you only need to have a single copy of a given large binary file on your local disk, even if you have multiple DVC repositories that use that file).

---

The typical use case for DVC is that you would configure a default DVC remote which is accessible from anywhere you would be cloning your repository. i.e. in "active1", you would do something like

```
$ cd active1
$ dvc remote add -d my-remote s3://my-s3-bucket/
$ dvc add some-data
$ git commit .
$ git push
$ dvc push
```

A this point, you can do

```
$ cd ..
$ git clone active1 active2
$ cd active2
$ dvc pull
```

And it will pull the DVC data which you pushed to the S3 bucket.

**Comment by pmrowla** [comment]
In the event that you don't want to deal with cloud storage or having a default central DVC remote, you can still do what you are looking for, and get a completely decentralized copy of your entire repository. You just have to explicitly tell DVC that you want active2 to push and fetch DVC data to/from active1's cache directory. (This works because DVC remote storage is the exact same format as local DVC cache)

In your active1/source repo:
```
$ cd active1
$ dvc add some-data
$ git commit .
```

In active2/destination repo
```
$ cd ..
$ git clone active1 active2
$ cd active2
$ dvc remote add --local active1 ../active1/.dvc/cache
$ dvc fetch -r active1 --all-commits  # fetch the entire history for all DVC-tracked files across all of the cloned git commits
```

At this point, active2 contains a complete decentralized copy of active1. Note that in this example, I configured a non-default remote (without `-d`) and used `--local`, which adds the remote configuration into `.dvc/config.local` which is gitignored by default. This results in a remote that only exists within the active2 repo (and that remote configuration would not be git committed or git pushed back to the original source repository).

In this scenario, you can also make changes from active 2 and push them back to the original repository

in active2:
```
$ vim some-data  # make modifications to your dvc-tracked data
$ dvc add some-data  # track the modifications
$ git add .
$ git commit  # git add and commit the modified some-data.dvc
$ git push  # push git changes back to active1/.git
$ dvc push -r active1  # push DVC data changes back to active1/.dvc/cache
```

---

But again, this is just not the default behavior in DVC, because typically users do not actually want the complete copy of the history for every large binary file tracked in DVC in local storage.

**Comment by dberenbaum** [comment]
Copied the relevant parts of the bug to #10069, so closing this one
