### ISSUE TITLE
Showing real files names instead of cache file name

### ISSUE THREAD

**Issue by dbalabka** [iterative/dvc#10098]
While doing `dvc pull`, it shows the cache file name on the remote storage. However, it would be much more useful to see what real file is pulled from the remote source:
![image](https://github.com/iterative/dvc/assets/1269372/1a292d74-260c-4a6e-ae0c-01e9bfc913c6)

**Comment by efiop** [comment]
The way we store data is content-based, so one object can have multiple names (gets even worse when dealing with multiple git revisions), so we just use a name based on object id.

We used to have real names in the past, but due to the reasons mentioned above dropped it. It seems like knowing file sizes usually helps with that, so maybe you will find `dvc list . --size` useful.

**Comment by dbalabka** [comment]
@efiop , am I right that in the scope of one repository it is very often the case when the user keeps multiple copies of one file under multiple names? Even so, I believe it is enough to show at least one of them and skip other names.

**Comment by efiop** [comment]
I can't say "very often", but it is a consideration that we have to keep in mind. E.g. the most common case is the same file across multiple revisions that you are pulling: reflecting which revision that particular object is in is not trivial in this ui and quickly becomes overloaded. Also this doesn't work with our future plans of further splitting those objects into chunks, that have an even more vague connection to file names.

**Comment by dbalabka** [comment]
Thanks for detailed explanation. Initially I thought that it should a simple change. Now it seems that it will require too much effort with too few benefit for the UX. Feel free to close it if you think it is not realistic to implement.
