### ISSUE TITLE
exp: branch mode

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#10147]
It might be useful to add a "branch mode" to experiments. Instead of saving exp refs, each experiment would be saved as a branch. Branches lose a lot of the subtle nice features of exp refs (branches are noisy, they may get accidentally modified, we may not be able to show them in the "nested" structure we use for exp refs), but they are easier for users to understand, so it may be a good way to onboard users.

**Comment by SoyGema** [comment]
Hey.
At some point, this possibility crossed my mind. However, when I started building, I prioritized the research question ML criteria for organizing branches inside the git repo. Instead of one branch per experiment, I prioritized branch-per -language , for organizing experiments. 

ex context: Inside the translation scenario, and taking into account that I want to find the attention heads for each language, and ultimately to try to answer the question ,` is there a model to translate then all ? ` ended up creating branches that could hold different languages with different datasets ... 
<img width="873" alt="Captura de pantalla 2023-12-14 a las 16 58 19" src="https://github.com/iterative/dvc/assets/24204714/80bc414c-96a2-4b87-9630-f9a0d103f90a">

Possible insgight : the domain criteria would prioritize making different branches.
My two cents. Im sure you have seen a lot more cases for this !

**Comment by dberenbaum** [comment]
Yes @SoyGema, I think this is a good mental model for an ideal scenario. Also related: https://github.com/iterative/dvc/issues/10165.

This issue was more about onboarding for those who find the concept of DVC experiments too overwhelming at first, but I think it might be better to focus on proposals like yours above and in #10165 about how to organize those experiments, so I'll close this one and we can continue discussion there.

**Comment by SoyGema** [comment]
Thanks for providing more context. True, I saw the onboarding word...Please consider adding the label onboarding as you folks do with the extension if you consider it necessary or in title issue so contributors can glimpse intention quikly, as well as consider how onboarding might be different from CLI and extension.

Keep up the great work !
