### ISSUE TITLE
dvc add -R dir

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#1026]
Thanks for the great project !

Let's say I have the following workflow:

data/dataset1/dataset1.csv
data/dataset2/dataset2.csv

`dvc add data/dataset1 && git add data/dataset1.dvc` --> creates data/dataset1.dvc and tracks with git
`dvc add data/dataset2 && git add data/dataset2.dvc` --> creates data/dataset2.dvc and tracks with git

Now let's say I modify both dataset1.csv and dataset2.csv I want to add both updates to dvc in a single command
`dvc add data` --> this fails because `data` contains files tracked by git.

Would it be possible to support that use case (i.e. ignore the git-tracked files when running dvc add)

**Comment by efiop** [comment]
Hi @tdeboissiere !

This happens because `dvc add data` tries to track the directory as a whole and not as a set of files. We should definitely implement something like `dvc add -R dir` which will recursively walk through the directory and add each file in it that is not tracked by git. Turning this issue into a feature request, will be sure to implement this shortly.

Thanks,
Ruslan

**Comment by efiop** [comment]
Hi @tdeboissiere !

Just wanted to let you know that I've merged the patch that implements this feature and I am going to release it in 0.18 today.

Thanks,
Ruslan

**Comment by tdeboissiere** [comment]
Awesome, thanks !
