### ISSUE TITLE
Unable to track metrics on state file name not ending with "dvc"

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1054]
Platform: Ubuntu 16.04
Installation method: pip
DVC version: 0.18.3

After running `dvc run ... -M metricFilename -f state ... `
 and commiting, `dvc metrics show` displays:

> Error: Failed to show metrics: No metric files in this repository. Use 'dvc metrics add' to add a metric file to track.

Further experiments show that running `dvc run ... -M metricFilename -f state.dvc ...`  solves problem.
Is this intended behaviour? I did not have problem with repro-ing from `state` file

**Comment by efiop** [comment]
Hi @pared !

Yes, it is an expected behaviour. `-f` is used to specify filename for the dvcfile and in order for dvc to find it later it should be either `Dvcfile` or end with `.dvc` suffix. So when you use `-f state` instead of `-f state.dvc` dvc is simply not finding it. This is definitely something we should prevent when running `dvc run`. I will prepare a patch shortly. Thank you!

**Comment by efiop** [comment]
>  I did not have problem with repro-ing from state file

Ah, looks like we should check it there too, since it only works if you explicitly specify `dvc repro state` and will not be discovered automatically by dvc. Great catch!

**Comment by pared** [comment]
Glad I could be of use, if there is no one to patch this up i can try to do it. 
I am new to open source, so I probably would need some guidance.

**Comment by efiop** [comment]
Hi @pared !

Thank you so much for offering help! I'm ready to send a patch to fix this particular issue, but if you still wish to help out in a different task we do have some and are happy to help tackle them :slightly_smiling_face:  Full list is available [here](https://github.com/iterative/dvc/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22). For example here are two simple tasks related to out visualization feature `dvc pipeline show` that are perfect to start with:

1) [`--dot`](https://github.com/iterative/dvc/issues/1051) -- basically you will need to add `--dot file.dot` option for `dvc pipeline show` that will output DAG of the pipeline in graphviz dot format that user will be then able to render using graphviz itself. We already store our DAG using networkx, so [this](https://networkx.github.io/documentation/stable/auto_examples/pygraphviz/write_dotfile.html) should be useful;

2) [`--tree`](https://github.com/iterative/dvc/issues/1038) -- this one is similar to our `--ascii` option, but will actually unroll all the dependencies down the graph into a dependency tree. Something like [asciitree](https://pypi.org/project/asciitree/) should be helpful;

Examples for both tasks are located at `dvc/commands/pipeline.py`. And our CLI parser is in `dvc/cli.py`. You might also find our [contrib](https://dvc.org/doc/user-guide/contributing) doc useful.

Please feel free to ping me if you need anything, I will be happy to help. If you decide to tackle some task please write in a comments to it, so that I will be able to assign you to it, so that no one else takes it.

Thanks,
Ruslan
