### ISSUE TITLE
Confusion with dvc repro when specifying output file in subfolder

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#1109]
**Ubuntu 16.04 dvc 0.18.15 (pip install)**

Sorry if this question looks similar to #1028 but the behaviour of DVC feels unnatural in this slightly different situation:

**This script throws an error:**

```
set -e
set -x
rm -rf foo
mkdir -p foo
cd foo
git init
dvc init
mkdir -p data/subdata
mkdir -p out/data/subdata/subsubdata
echo "data" >> data/subdata/data.txt
dvc run\
    -c out/data \
	-d ../../data/subdata \
	-o subdata/subsubdata \
	-f subdata/subsubdata.dvc \
	cp ../../data/subdata/data.txt subdata/subsubdata
dvc repro out/data/subdata/subsubdata.dvc
```
(In the script above, I do want to save a .dvc file in `out/data/subdata/subsubdata.dvc`, dvc run works, but dvc repro fails with:

`Failed to reproduce 'out/data/subdata/subsubdata.dvc': Failed to reproduce 'out/data/subdata/subsubdata.dvc': Stage 'out/data/subdata/subsubdata.dvc' cmd cp ../../data/subdata/data.txt subdata/subsubdata failed`
)

**However, this one does not:**

```
set -e
set -x
rm -rf foo
mkdir -p foo
cd foo
git init
dvc init
mkdir -p data/subdata
mkdir -p out/data/subdata/subsubdata
echo "data" >> data/subdata/data.txt
dvc run\
    -c out/data \
	-d ../../data/subdata \
	-o subdata/subsubdata \
	cp ../../data/subdata/data.txt subdata/subsubdata
dvc repro out/data/subsubdata.dvc
```

But in the script above, the .dvc file is saved in `out/data` instead of `out/data/subdata`)

**Comment by efiop** [comment]
Hi @tdeboissiere !

The repro error happens because the `cp` is being run from the location of the `.dvc` file `out/data/subdata/`, while it was first ran from `out/data`(because of the `-c out/data`). I believe your `dvc run` should look like this:
```
dvc run\
    -c out/data/subdata \
	-d ../../../data/subdata \
	-o subsubdata \
	-f subsubdata.dvc \
	cp ../../../data/subdata/data.txt subsubdata
```
Notice how the command and its arguments are specified relative to the location of the `subsubdata.dvc` file, because that is the location from where the command will be run when reproducing.

We should definitely check `-f` value to make sure that it doesn't contain subdirectories and only specifies the filename of the stage file to avoid such confusion. Created https://github.com/iterative/dvc/issues/1110 to track the progress on it.

Considering that currently `dvc run` creates so much confusion with its path resolution, I think we should think about redesigning `dvc run` for v1.0 to have a more natural interface. Created https://github.com/iterative/dvc/issues/1111 to track the progress on it.

Thanks,
Ruslan

**Comment by tdeboissiere** [comment]
I see, that did the trick.

Is there any way for it to work without using `dvc run -c` ?

For instance, the script below fails to reproduce:

```
set -e
set -x
rm -rf foo
mkdir -p foo
cd foo
git init
dvc init
mkdir -p data/subdata
mkdir -p out/data/subdata/subsubdata
echo "data" >> data/subdata/data.txt
dvc run\
	-d data/subdata \
	-o out/data/subdata/subsubdata \
	-f out/data/subdata/subsubdata.dvc \
	cp data/subdata/data.txt out/data/subdata/subsubdata
dvc repro out/data/subdata/subsubdata.dvc
```

**Comment by efiop** [comment]
It is possible, but not with the current `dvc run`, since it acts more like a dumb wrapper for just writing stuff into dvc files. I think starting from 1.0 we will make it save cwd(and it will be configurable as well), so that the script you've provided would work by saving `cwd=$(pwd)` and write the dvcfile to `out/data/subdata/subsubdata.dvc` which seems much more natural.

Thanks,
Ruslan

**Comment by shcheklein** [comment]
@tdeboissiere @efiop is it still relevant or last changes with `wdir` and `-f` are enough? What's missing?

**Comment by efiop** [comment]
@shcheklein yep, it does work now. @tdeboissiere Please give `dvc run --wdir` a try and see if it works for you. The test script from above works for me now.
