### ISSUE TITLE
dvc checkout changes the md5 of the dvc file.

### ISSUE THREAD

**Issue by yukw777** [iterative/dvc#1206]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

```bash
$ dvc --version
0.19.2
```
Installed using DEB.

I'm seeing a weird behavior with after running `dvc checkout`
```bash
$ dvc checkout my.dvc
....
$ dvc checkout my.dvc
Data didn't change messages...
$ dvc status -v
Debug: Dvc file 'my.dvc' md5 changed (...)
my.dvc
```
Why did the md5 change after I checked it out?

**Comment by efiop** [comment]
Hi @yukw777 !

Could you please show `dvc status -v` output before `dvc checkout`?

I don't think that `dvc checkout` is what changed `my.dvc`, since it doesn't even write .dvc files. I think that  `my.dvc` got changed by some other action, which didn't affect `path:` and `md5:` fields of outputs of `my.dvc`, which is what `dvc checkout` is checking and that is why it reports `data didn't change'. On the other hand `dvc status` checks everything in the `my.dvc`, since it needs to check if the command for your stage is changed and thus the stage is going to be reproduced with next `dvc repro`. We have actually discussed this discrepancy earlier and created https://github.com/iterative/dvc/issues/1202 to be sure to separate 'data' and 'pipeline' parts of `dvc status` in 1.0. Your feedback makes it even clearer that we should separate those parts somehow to avoid confusion.

Thanks,
Ruslan

**Comment by yukw777** [comment]
OK, I haven't seen this since I reported it, and I think it went away when I reproduced that file again. I'll close this for now.
