### ISSUE TITLE
run: Check whether file specified by the output already exists

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1235]
DVC version: `0.19.12`
Installation: `Arch Linux AUR package`

This prevents overwritting the file or causing some unexpected behaviour.

```bash
#!/bin/bash

# Clean and create a repository
rm -rf myrepo
mkdir myrepo
cd myrepo

# Init git and dvc
git init
dvc init
git add -A
git commit -m "Init"

# Creating the dependency
echo "hello" > hello.txt

dvc run \
  --file circular-dependency.dvc \
  --deps hello.txt \
  --outs hello.txt \
  'echo "overwrite" > hello.txt'
```

**Comment by efiop** [comment]
Btw, you can still get this bug if you use `-O|--outs-no-cache`:

```
dvc run \
  --file circular-dependency.dvc \
  --deps hello.txt \
  --outs-no-cache hello.txt \
  'echo "overwrite" > hello.txt'
```

This is because you should check `stage.outs` and `stage.deps`, instead of `outs` and `deps`. Plus, when you are using `outs` and `deps`, they can have non-normalized paths e.g. `./foo` and `foo`. You should use `.path` property for every entry in `stage.outs` and `stage.deps` lists. Could you please send a fix for that?

Thanks,
Ruslan

**Comment by mroutis** [comment]
Sure, @efiop! I'll send a patch tomorrow
