### ISSUE TITLE
Better status for aggregate DVC files

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#1278]
DVC version : 0.20.0 (python 3.6 anaconda install)

```
#!/bin/bash

# Create repository
rm -rf myrepo
mkdir myrepo
cd myrepo

# Init Git and DVC
git init
dvc init
git commit -s -m"Init"

# Create data directory with ("proccesed" data and "raw" data)
mkdir -p main_data/data/procdata
mkdir -p main_data/data/rawdata

# Create initial rawdata
#
#   echo 1 > main_data/data/rawdata/file1.txt
#   echo 2 > main_data/data/rawdata/file2.txt
#
for d in {1..2}; do
    echo $d > main_data/data/rawdata/file$d.txt
done

# Create two `dvc` files: (file1.txt.dvc && file2.txt.dvc)
#
# - Change directory to `main/data/procdata`
# - Dependency: `main_data/data/rawdata/file1.txt
# - Output:     `main_data/data/procdata/file1.txt
# - Command:    `cp main_data/data/rawdata/file1.txt main_data/data/procdata
for d in {1..2}; do
    dvc run \
      --no-exec \
      -c main_data/data/procdata \
      -d ../rawdata/file$d.txt \
      -o file$d.txt \
      cp ../rawdata/file$d.txt .

    DEPS="$DEPS -d procdata/file$d.txt"
done

echo "Dependency flags: $DEPS"

dvc run \
  --no-exec \
  -c main_data/data \
  $DEPS \
  -f data.dvc

dvc repro main_data/data/data.dvc

# Now modify file1.txt
echo 5 > main_data/data/rawdata/file1.txt
dvc status main_data/data/procdata/file1.txt.dvc
dvc status main_data/data/data.dvc
```

The first `dvc status` command will show that `file1.txt` has been modified. However, the second  `dvc status` command shows that everything is up to date.

This is misleading because calling `dvc repro main_data/data/data.dvc` actually re-runs the whole pipeline to account for the change in `file1.txt`

Is it possible to fix this behaviour of `dvc status` ?

**Comment by efiop** [comment]
Hi @tdeboissiere !

Currently `dvc status target.dvc` will tell if only direct dependencies of the `target.dvc` had changed(unlike `dvc status` without an argument, which shows status for the whole project and all dependencies). We have --with-deps option(which provides more of a `repro` like behavior) supported for other commands and I've sent a patch to support it for `local status` as well. The confusion is related to https://github.com/iterative/dvc/issues/1202 . I've created https://github.com/iterative/dvc/issues/1364 to separate `data` and `pipeline` commands into sub-commands, so that there is hopefully less confusion. For now, you can use `dvc status target.dvc --with-deps` or maybe even `dvc repro target.dvc --dry` as a workaround.

Thanks,
Ruslan
