### ISSUE TITLE
import: When using an S3 URL it should accept the --profile flag

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1282]
```bash
# Create directory
rm -rf example
mkdir example
cd example

# Init git and dvc
dvc init --no-scm

# Generate a DVC file
dvc run -o hello 'echo "hello" > hello'

dvc remote add -d myremote s3://mybucket/dvc-storage
dvc remote modify myremote profile local
dvc remote modify myremote endpointurl http://localhost:9000

# Run minio
docker run \
  -d \
  -e MINIO_ACCESS_KEY=changeme \
  -e MINIO_SECRET_KEY=changeme \
  -p 9000:9000 \
  --name minio \
  minio/minio \
  server /data

# Create bucket
aws \
  --endpoint-url 'http://localhost:9000' \
  --profile local \
  s3 mb s3://mybucket

# Upload cache to minio
dvc push

# Create file and upload it to bucket
remote_file=$(mktemp)
echo "remote file" > $remote_file

aws \
  --endpoint-url 'http://localhost:9000' \
  --profile local \
  s3 cp $remote_file s3://mybucket/remote_file

# Download file via dvc
dvc import \
  --endpoint-url 'http://localhost:9000' \
  --profile local \
  s3://mybucket/remote_file \
  remote_file

# Remove minio
docker rm -f minio
```

**Comment by efiop** [comment]
The problem here is that you will need these config options later anyway for dvc to check if the external dependency has changed, so it makes sense to setup the remote once and for all. That being said, in the proposed import format, we could either create a remote automatically in one of our configs(which will be effectively duplicating `dvc remote` command, so we might as well just ask user to setup the remote by himself at that point) or we could store those options in the dvc file itself, which is an option, but, it would create unnecessary complications. So i think that the current way of configuring remote beforehand is suitable for now.

**Comment by mroutis** [comment]
I totally agree, @efiop , let's keep using `remote://`
