### ISSUE TITLE
init: Remove SCM message when using `--no-scm`

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1305]
**Command**:
```bash
dvc init --no-scm

```
**Current output**:
```bash
You can now commit the changes to git.
```

**Comment by veera83372** [comment]
Did you mean running `dvc init --no-scm` in a scm initialised repository?

**Comment by efiop** [comment]
@veera83372 Just running `dvc init --no-scm` in a new directory not controlled by any scm. E.g.
```
mkdir myrepo
cd myrepo
dvc init --no-scm
```

**Comment by veera83372** [comment]
I am getting different output, Please see below
<a href="https://asciinema.org/a/3Iwg1nnf1Ef4QxdTaETrnwLQJ?autoplay=1"><img src="https://asciinema.org/a/3Iwg1nnf1Ef4QxdTaETrnwLQJ.png" width="836"/></a>

**Comment by efiop** [comment]
@veera83372 Ah, indeed. Looks like it was fixed at some point :slightly_smiling_face: https://github.com/iterative/dvc/blame/master/dvc/repo/init.py#L90 Thanks for the heads up! Closing.

**Comment by veera83372** [comment]
FYI: It gives the same message when the folder has scm but using `--no-scm` option.

**Comment by efiop** [comment]
@veera83372 That is because of the way dvc handles scms. It dynamically checks if it is available and will use it if it is. `--no-scm` is just a helper to make sure that you indeed want to use dvc without any scm. Also, without `--no-scm` it would be hard to catch when user is just accidentally initializing dvc project in some subdirectory of his git project instead of doing that in root dir.
