### ISSUE TITLE
dvc remote: set and unset to default

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#1357]
I have a remote which was not set as a default for some reason:
```
$ dvc remote list
mys3	s3://examples-so/dataset-25K-ver
```

It looks like the only way to make my remote default is to reconfigure dvc `dvc config core.remote mys3` or remove the remote and create a new one.

I'd expect to have this option in `dvc remote modify`.

Also, it is not clear:
1. Why don't we set a remote as default if this is the only remote? 
2. Why don't we agree to use `origin` as a default remote?
3. Why don't we show some (let say S3) example in `dvc remote add -h` and all possible types.

**Comment by efiop** [comment]
You can use `-d` when adding a remote to make it default.

> It looks like the only way to make my remote default is to reconfigure dvc: dvc config core.remote

Right, or by editing config yourself.

> I'd expect to have this option in dvc remote modify

`dvc remote modify` is only for modifying remote section, not `core` section. We could think of adding a separate command for that like `dvc remote default myremote`, but at that point it is easier to just edit the config instead of looking for a separate command :slightly_smiling_face: 

> Why don't we set a remote as default if this is the only remote?

If you would to add another remote one day(say in your system/user/local configs, or maybe your team member added it and you've pulled it from git), it would simply break for no reason. This action is only done once and usually when the remote is added, so it is not a problem to just use `-d` option with it.

> Why don't we agree to use origin as a default remote?

Origin in git is the remote that you've cloned from, so it doesn't really apply to our case and might lead to confusion.

> Why don't we show some (let say S3) example in dvc remote add -h and all possible types

We have agreed to have stuff like that in our docs https://dvc.org/doc/commands-reference/remote , where it is easier to manage. Indeed, it would be great to have at least some examples in cli help. Created https://github.com/iterative/dvc/issues/1358 .
