### ISSUE TITLE
dvc pull of remotes pointing to old versions of resources

### ISSUE THREAD

**Issue by D3Reo** [iterative/dvc#1362]
Hi, I'm running dvc  0.20.6 on a debian vm (installation from pip).
A colleague of mine modified a data folder, added its .dvc file to dvc's staging area, committed it to our git server and pushed, but he forgot to do a dvc push. This morning I knew he some of the data in the pipeline, so did a git pull followed by a dvc pull, and the report stated that he couldn't find directory with the correct hash - so far so good. My concern is that my local version of that folder was deleted in the process, I fear that this is not an intended behavior: shouldn't local versions of files/dirs be deleted only after dvc is certain that all of the hashes match and that it will be effectively able to replace it with a new different version?
Thank you!

I know there's a new version out, I haven't had time to test if this happens in the latest  0.20.7 yet, I hope I'm not reporting something that has already been fixed.

**Comment by efiop** [comment]
Hi @D3Reo !

The behavior is harmless, because dvc _knows_ that it has your old version saved in cache, otherwise it would've prompted you to ask if you are sure you want to delete unsaved data. It only deleted that directory from the workspace, leaving all the cache for it intact, so you can safely roll back to previous commit and do `dvc checkout`, that will put that directory back together.

Thanks,
Ruslan

**Comment by D3Reo** [comment]
Ok, that makes sense, I was kind of scared when I saw the dir disappear, but I actually should have come up with that idea myself. Thank you!
