### ISSUE TITLE
checkout: don't ask for removal confirmation if we have that file in the cache

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1366]
```
#!/bin/bash

set -e
set -x

rm -rf myrepo
mkdir myrepo
cd myrepo
git init
dvc init
git commit -m"init"

git checkout -b foo
echo foo > file

dvc add file
git add file.dvc .gitignore
git commit -m foo

git checkout master
git checkout -b bar
dvc checkout

echo bar > file
dvc add file
git add file.dvc .gitignore
git commit -m bar

git checkout foo
dvc checkout
```

shouldn't ask for confirmation when deleting `file`, since it has that version in the cache already.

**Comment by mroutis** [comment]
We would need to recompute the checksum for every file we check, as we don't know if it has changed or not.

```diff
#!/bin/bash

set -e
set -x

rm -rf myrepo
mkdir myrepo
cd myrepo
git init
dvc init
git commit -m"init"

git checkout -b foo
echo foo > file

dvc add file
git add file.dvc .gitignore
git commit -m foo

git checkout master
git checkout -b bar
dvc checkout

echo bar > file
dvc add file
git add file.dvc .gitignore
git commit -m bar

git checkout foo
+ echo other_content > file
dvc checkout
```

What we are trying to achieve is preventing the user from deleting files that are "work in progress" (a dirty working directory) when `checking out`.

I'll submit a patch for it, but I can't imagine how expensive would be to recalculate MD5s in order to know which files are safe to delete without prompting.

What do you think, @efiop ?

**Comment by efiop** [comment]
@mroutis If that file is already in cache and was linked to the workspace by dvc, then the checksum for it is already cached and costs nothing to retrieve. Otherwise we do re-compute the checksum, since we need to ensure that checksum is the one or not the one we need. We actually do that already, see https://github.com/iterative/dvc/blob/master/dvc/state.py#L87 . Or, another possibility, is to simply check if that file is in our link_state table(https://github.com/iterative/dvc/blob/master/dvc/state.py#L346), so we quickly know that it was indeed created by us and can be removed safely.
