### ISSUE TITLE
Possible consistency issue when locking and unlocking changed DVC files

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#1380]
Hi guys, 

just wondering whether this could be a problem: After a dvc file content is changed, the md5 checksum of the dvc file can be tricked by locking and unlocking the file, making it seem like the file was not changed. Should dvc refuse to lock an inconsistent file to avoid unintentionally hiding inconsistencies, or would that just provide more headache to the users?

**Comment by prihoda** [comment]
Or maybe locking and unlocking shouldn't change the md5 checksum. The files won't be shown in `dvc status` anyway so the inconsistency wouldn't be a problem.

**Comment by efiop** [comment]
Hi @prihoda !

Great catch, as always! The issue is caused by `Stage.dumpd()` method, that is re-computing dvc file checksum even if you simply reload your dvc file, which is not right. It should leave md5 the way it is, and only compute it when there was an actual `run` performed. You are right, we should exclude unrelated parameters from the dvc file dict, when computing a checksum for it(e.g. `locked`, `metrics`, etc). Thank you for the amazing feedback! We will fix this shortly.

**Comment by efiop** [comment]
Hi @prihoda !

The fix was released in 0.21.3. Please upgrade :slightly_smiling_face: 

Thanks for the feedback!
