### ISSUE TITLE
Support calling DVC with output path as alternative to stage path

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#1403]
Hi guys, just an idea, what if you could also use `file.txt` just like `file.txt.dvc` when calling all DVC commands? 

Since DVC already checks that a single file cannot be an output of multiple stages, its stage is uniquely defined and can be retrieved automatically. Both ways could be supported, the user could call DVC the way they prefer: `dvc repro file.txt` or `dvc repro file.txt.dvc`.

The motivation is:
- `file.txt` appears before `file.txt.dvc` when using tab expansion :)
- when working with files, my focus point is the output file rather than the DVC file

The main problems that come to mind:
- for stages with multiple outputs, all of them would be reproduced/pushed/pulled. But is that too surprising? 
- it might be confusing when the file is not present yet - you could still use `dvc pull file.txt`, but you would have to know the filename.
- it might be confusing that you can call DVC both ways

**Comment by efiop** [comment]
Hi @prihoda !

Thank you for detailed analysis, it is great! All three problems can be mitigated with appropriate warning messages, that would let user know that something is happening. I see no reason why we can't or shouldn't support this behavior. We'll take a look at implementing this soon.

Thanks,
Ruslan

**Comment by dmpetrov** [comment]
This problem can become even worse because of #1341. I can easily imagine as people put all the command in a single dvc file.

I'd even consider using only data files as commands parameters and stage files through a separate option. Like `dvc repro file.txt` or `dvc repro -s file.txt` but not `dvc repro file.txt.dvc`.

**Comment by efiop** [comment]
@dmpetrov I see no problem supporting both, no need to abandon current behaviour. Even in multiple-stages-per-dvc-file, running `dvc repro multi.dvc` is useful to run all of those stages and doesn't conflict at all with `dvc repro someoutput`. Keep in mind that if we decide to implement #1341 , we'll need to distinguish separate stages within multi-stage-dvc-file anyway(e.g. maybe to naming separate stages within it), so we'll provide some granularity either way.

**Comment by dmpetrov** [comment]
@efiop no conflicts in names - good point. 
Could you please clarify why separate stages should we distinguished in a single file? It looks like naming is not an issue since you can address stages by data files.

**Comment by efiop** [comment]
@dmpetrov good point about data files, that is one way to go about it, sure. But we might want additional names for stages within a single-dvc-file, so it is easier for the user to read it and separate them in his head with special stage names instead of using outputs and commands. E.g.

```
name: featurization
cmd: featurization.py
outs: ...
deps: ...

name: training
cmd: train.py
outs: ...
deps: ...
```

or something like that. And so you would do something like `dvc repro multi.dvc --stage featurization`. But in any case, all of these do not conflict so we can leave particular details for later.

**Comment by dmpetrov** [comment]
@efiop stage name could be optional. Or we can use corresponding command as a replacement for a name.

**Comment by efiop** [comment]
With new dvc.yaml we have stage names that could be passed to `dvc repro`. The output-based targetting is implemented for status/push/pull/checkout/etc. Closing for now as output-based targetting no longer get's requests.
