### ISSUE TITLE
Getting DVC status for subset of output files

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#1404]
Hi guys, in the IntelliJ plugin, I guess we could save a lot of processing power if we checked the status just for a subset of currently changed output files, as opposed to checking status of all active stages. 

For example, I know that files `a.txt` and `b.txt` just changed, it would be great if I could run something like `dvc status --only-changed-files a.txt b.txt` and get status of `a.txt.dvc` and `b.txt.dvc` and all other stages that depend on those inputs. 

Or is the overhead of running `dvc status` small, when most of the files didn't change? Since you're caching the state.

**Comment by efiop** [comment]
Hi @prihoda !

The overhead for `dvc status` is indeed pretty small and would be comparable to `dvc status --only-cached-files`, since dvc would still have to build DAG and analyze it traversing dependencies and stuff. Does `dvc status` suitable is your current scenario? I guess in your case, you need to parse the output of `dvc status` to know which files have changed and then use it in the plugin somehow, right?

**Comment by efiop** [comment]
If you don't mind, let's then close this one in favor of #1406 :slightly_smiling_face:
