### ISSUE TITLE
azure/gs/s3: re-design checksum computation for external dependencies/outputs

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1410]
<s> Unlike S3, azure does provide `content-md5`(need to investigate if it still works, since s3 had support for it some time ago and doesn't have it right now) This is related to external outs/deps feature, that is not implemented yet. Usual `push/pull` are not going to be affected. </s>

**Comment by efiop** [comment]
Ok, turns out user should set content-md5 by himself in order for this to work. Also ETag does indeed change when you simply copy blob from one location to another. So we need to require Content-Md5 to be present or to compute and set it ourselves. We can use ETag for dependencies though.

**Comment by efiop** [comment]
Ok, turns out when you move multipart objects on s3 they don't retain their etag. See https://discordapp.com/channels/485586884165107732/485596304961962003/563864123587297280 . So we might need to come up with a general approach to handle all of these clouds :(

**Comment by efiop** [comment]
Another approach to handle all of these in a unified way is https://discordapp.com/channels/485586884165107732/485596304961962003/563899005151608843

**Comment by efiop** [comment]
Related workaround for s3 https://discordapp.com/channels/485586884165107732/485596304961962003/563910400450625546

**Comment by olveirap** [comment]
I'm giving a shot at the s3 workaround. As far as I can see we need to check if the origin object of the copy in [here](https://github.com/iterative/dvc/blob/master/dvc/remote/s3.py#L109) is a multipart uploaded object by checking if it has a suffix in the etag. If that's the case, we need to calculate from the size it has and the number of parts it was uploaded in from the suffix of the etag, the chunk size of we need to set in the TransferConfig passed to the copy in order to achieve the same number of parts in the copy.

**Comment by olveirap** [comment]
Actually, the head_object has the part count and the size, using that is less hacky.

**Comment by harshavardhana** [comment]
> Actually, the head_object has the part count and the size, using that is less hacky.

https://github.com/aws/aws-sdk-java/issues/1303 that has been generally considered undocumented and shouldn't be used as per aws-sdk-java

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/3920
