### ISSUE TITLE
dvc: support .dvcignore

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1499]
Same as .gitignore, but for dvc. It will tell dvc which paths to ignore when caching data. Would be extremely useful for ignoring auto-generated/temporary files/directories that are created as a side effect and don't carry anything useful.

First iteration should make patterns listed in dvcignore be ignored on Repo.stages() when collecting stages.
```
echo '/directory_with_millions_of_files' > .dvcignore
dvc status # should not enter `directory_with_millons_of_files`
```

Second iteration should support `dvc add/run`. We have a separate issue for it at https://github.com/iterative/dvc/issues/1876

**Comment by efiop** [comment]
It is for users mostly as a convenient way to ignore some paths/files/dirs from being cached/tracked by dvc. Good point about `.dvc/` though, we will act as if it is in `.dvcignore` by default :)

**Comment by mroutis** [comment]
Is this somehow related https://github.com/iterative/dvc/issues/1471 ?

I saw on the chat that the problem was that the MD5 of a directory changed because the file system created a `.DS_Store` on that one and detected it as changed.

I can see the same stuff happening for other things if you are not careful enough (e.g. vim swap files, file locking mechanisms that create dotfiles, IDE specific files / `.tags`, etc.)

If we are introducing `.dvcignore` it would also be great to have a global `.dvcignore` the same way you can have a global `.gitignore`

**Comment by efiop** [comment]
@mroutis Not related to #1471 , it is exclusively about dvc tracking files.

Great idea about a global .dvcignore! I didn't know .gitignore could be global.

**Comment by zb0th** [comment]
I think an equally pressing issue is that having a large un-cached folder slows down dvc, as it needs to traverse the whole folder before executing any command.

**Comment by shcheklein** [comment]
Please, create a ticket or a page to document the changes.
