### ISSUE TITLE
test: investigate test failure

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1534]
Only on @shcheklein 's machine: https://gist.github.com/shcheklein/507b0d99a24d1e18249a8c0ad3791110

**Comment by shcheklein** [comment]
More context:

When cache type is reflinks and we run `dvc add foo`, we move it to cache under the hood and create a link. It looks like there are two files, two inodes, they internally share data blocks. But we don’t update our state db, as far a I understand. It basically means that we have an inode in state db that belongs to the cached file, not the one from the workspace. It means that if run `dvc run -d foo` it calculates the md5 again.

^^ This should be fixed in https://github.com/iterative/dvc/issues/1221 .

Tests should be fixed two ways if it's indeed related to reflinks:

1. CI should be set to run on APFS, brfts, or similar systems. We need to run the whole test suite on different environment.
2. Failing tests have to be fixed to account for that.

**Comment by pared** [comment]
#1221 is fixed, @shcheklein, can I close this?

**Comment by shcheklein** [comment]
Yep, it is fixed. Feel free to close it.
