### ISSUE TITLE
Use mock instead of HTTPServer

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1573]
For functional tests we use tests.utils.httpd.StaticFileServer. To prevent mess associated with multiple tests trying to use server, we would prefer to use something that could mock responses, like https://github.com/bblimke/webmock (proposed by @shcheklein  in #1540). 
Task:
Remove StaticFileServer, use mocks instead.

**Comment by efiop** [comment]
@pared we could have both. The current one is suitable for functional tests, and mocked one would be suitable for unit tests. We will introduce a requirement for 100% coverage by unit tests in the future, so that is where mocked server could be used to quickly and efficiently test PRs, so then we could have a cron job or master tests to run functional tests.

**Comment by mroutis** [comment]
Some how related: https://github.com/iterative/dvc/issues/907

**Comment by efiop** [comment]
Closing in favor of #907
