### ISSUE TITLE
Consider using ORM

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1594]
State is stored as sqlite database.
Should we use some ORM?

**Comment by efiop** [comment]
We are having some problems with our state db when trying to use it in multithreaded mode, as our `state` wasn't meant for that. And it makes us use ugly workarounds like https://github.com/iterative/dvc/blob/0fdb119ed54438fe6f58d53020b96aebc0abbd9b/dvc/tree/base.py#L327 , where we have to use state only in the main thread. Plus we have some code duplication in index-related code :slightly_frowning_face: 

No strong opinion, but from a quick lookaround, we might be able to use sqlalchemy (scoped_session seems especially nice), as it seems stable and has proper wheels (e.g. peewee doesn't).

**Comment by efiop** [comment]
Looked into it a bit closer, just dropping in the sqlalchemy works just fine, but using scoped_session (or any similar mechanism like that even outside of sqlalchemy) gets really cumbersome with how our state is loaded. We'll get back to this after Tree refactor when we will be able to have a global pool for filesystems, in which it will be a bit easier to handle connection sessions.

**Comment by efiop** [comment]
An even better option might be to refactor state structure from saving inode, size, mtime, etc into just saving a checksum and the hash. E.g. fsspec has checksum() https://github.com/intake/filesystem_spec/blob/c2b6eabd37bf8c10222f17e8a816e19b43c70c01/fsspec/spec.py#L605 call, that can be used universally and that already depends on mtime/inode/size for local files. That could be transfered for any other fs too, as long as it implements the checksum()

**Comment by DavidGOrtega** [comment]
When I read ORM I have nightmares 😄 🛏️

**Comment by efiop** [comment]
Another point is that our state is currently inode-based because it used to make sense a long time ago when hardlinks were defaults and we didn't support shared cache scenario, so files moved from the workspace to the cache would have the same inode and so we could reuse the state records. These days that no longer makes much sense, as we explicitly save hashes for cache files to state when they are being transfered (e.g. pulled) and a dict-ish structure where keys are paths to the files and values are `(checksum, hash)`(checksum in fsspec meaning https://github.com/intake/filesystem_spec/blob/4d03e1e07ada08f91784e7826c355da71a13aa1e/fsspec/spec.py#L605 which is pretty much the same as our inode, size, mtime tuples) pairs would make a lot more sense and would be much easier to manage.

**Comment by efiop** [comment]
Fixed by #5505
