### ISSUE TITLE
dvc repro --force is ignored when stage does not change

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#1667]
Hi guys, an unchanged stage does not reproduce even when using `dvc repro --force` 

```bash
echo "Hello" > foo.txt

dvc run -d foo.txt -o bar.txt 'echo foo.txt > bar.txt; date > bar.txt'
# [##############################] 100% bar.txt
# Running command:
# 	echo foo.txt > bar.txt; date > bar.txt
# Saving 'bar.txt' to cache '.dvc/cache'.
# Saving information to 'bar.txt.dvc'.

cat bar.txt
# Thu Feb 28 10:56:32 CET 2019

dvc repro --force bar.txt.dvc
# Stage 'bar.txt.dvc' didn't change.
# Reproducing 'bar.txt.dvc'
# Running command:
# 	echo foo.txt > bar.txt; date > bar.txt
# Checking out '{'scheme': 'local', 'path': '/Users/prihodad/Documents/projects/dvc-bug/bar.txt'}' with cache '62bd24502e0833c73a3b0f3e96f28474'.
# Output 'bar.txt' didn't change. Skipping saving.
# Saving 'bar.txt' to cache '.dvc/cache'.
# Saving information to 'bar.txt.dvc'.

cat bar.txt
# Thu Feb 28 10:56:32 CET 2019
```
This happens even with `--ignore-build-cache`:
```
dvc repro --force --ignore-build-cache bar.txt.dvc
# Stage 'bar.txt.dvc' didn't change.
# Reproducing 'bar.txt.dvc'
# Running command:
# 	echo foo.txt > bar.txt; date > bar.txt
# Checking out '{'scheme': 'local', 'path': '/Users/prihodad/Documents/projects/dvc-bug/bar.txt'}' with cache '62bd24502e0833c73a3b0f3e96f28474'.
# Output 'bar.txt' didn't change. Skipping saving.
# Saving 'bar.txt' to cache '.dvc/cache'.
# Saving information to 'bar.txt.dvc'.

cat bar.txt
# Thu Feb 28 10:56:32 CET 2019

```

(dvc version 0.29.0)

**Comment by efiop** [comment]
Hi @prihoda !

Great catch! This happens because of https://github.com/iterative/dvc/blob/0.29.0/dvc/stage.py#L660 and https://github.com/iterative/dvc/blob/0.29.0/dvc/stage.py#L644 in `dvc import` case, which do not care about `--force` or `--ignore-build-cache` options. @mroutis Could you please take a look? :slightly_smiling_face:

**Comment by mroutis** [comment]
Hello, @prihoda , thanks for your report and the detailed reproduction script! I'll work on it right now :)

**Comment by piojanu** [comment]
In what version can we expect this fix? In v0.30.1 `dvc repro --force --ignore-build-cache <name.dvc>` still don't run commands, just checkout files from cache.
I've tried @prihoda test too. It still doesn't force reproduce.

**Comment by efiop** [comment]
> I've tried @prihoda test too. It still doesn't force reproduce.
@piojanu Did you try upstream version? Or do you mean 0.30.1? We'll release a new version later today.

**Comment by piojanu** [comment]
You, I mean 0.30.1 from pip. It'll be on pip today?

**Comment by piojanu** [comment]
When can I expect new version? Or how to install upstream version as currently I can't force reproduce my pipeline :(

**Comment by efiop** [comment]
@piojanu Sorry for the delay. Will try to release it today. Thanks for the feedback!

**Comment by efiop** [comment]
@piojanu 0.31.1 is out. Please feel free to upgrade and give it a try. Thanks for the feedback!

**Comment by piojanu** [comment]
Hmm, `pip install -U dvc` doesn't upgrade it. How to upgrade then?

**Comment by efiop** [comment]
@piojanu Try uninstalling it manually with `pip uninstall -y dvc` and installing again with `pip install dvc` and see if that works. Please let us know if that worked for you or not.

**Comment by piojanu** [comment]
Oh sorry, my bad. I've tried it on my local machine, where I've installed dvc using homebrew 😮 `brew upgrade dvc` works like charm 👍

I've also upgraded it on my remote machine (linux) and version number printed by `dvc --version` is strange: `0.29.0+220b4b.mod`. It is some development version right? It's strange because pip prints that it installed `dvc-0.31.1`.
I thought that it might be because of gitpython (I've installed it to get dev version earlier). I've tried to uninstall it, but I also see it is dependency now and it gets installed with dvc again.

**Comment by efiop** [comment]
@piojanu Yes, `0.29.0+220b4b.mod` is definitely a dev version. I would guess that you have a few instances installed there through different ways(e.g. pip, binary package, etc). So you need to clean everything up, and then install a new version.

**Comment by piojanu** [comment]
I've installed it just with pip, but in two virtualenvs. I'll try to sort it out later.
