### ISSUE TITLE
Automatic/suggested 'dvc remove' on 'dvc run' overwrite

### ISSUE THREAD

**Issue by mmaorc** [iterative/dvc#1679]
Say we have a pipeline phase that outputs multiple files:
```
dvc run -O file1 -O file2 -f phase.dvc "touch file1; touch file2"
```
Now we want to change it so we do:
```
dvc run -O file1 -O file3 -f phase.dvc "touch file1; touch file3"
```
After overwriting the existing dvc file, we are still left with the old irrelevant output files (file2 in this example). Over time this can leave the repository, if we are not careful, with many irrelevant files.
I know we can use ```dvc remove``` before the second ```dvc run```, but maybe the process can be made more idiot-proof by automatically removing the old irrelevant outputs when we overwrite a dvc file, or at least suggesting it.

What do you think?

**Comment by shcheklein** [comment]
Great suggestion, @mmaorc ! I think we can make it a default behavior for the overwrite operation, and probably introduce an additional option to keep files (`--keep-outputs`?) if it's needed.

We already have a prompt asking if you want to overwrite it in `stage.py` lines ~460-470. 

```python
           msg = (
                "'{}' .already exists. Do you wish to run the command and "
                "overwrite it?".format(stage.relpath)
            )

            if not overwrite and not prompt.confirm(msg):
                raise StageFileAlreadyExistsError(stage.relpath)

            os.unlink(path)
```
I actually think that some refactoring here is also needed - actual removal should not be happening in the `create`, it should be a separate method `cleanup` or something that should be taking care of outputs, .gitignore, previous stage file, etc.

@efiop @mmaorc what do you think guys?

**Comment by efiop** [comment]
@shcheklein 
Not so sure about making it a default behavior though, since it is a destructive operation after all. Currently you are only loosing the reference from your dvc file, but if we also remove outputs by default you'll lose data too. This is especially scary in `--no-commit` scenario that is going to become a default one in the future, since you won't even have it stashed in the cache(though this can be handled with an additional prompt as well). Let's start with an explicit option for now, so that we don't break backward compatibility and we could recosider making it default in v1.0, when we'll be free to break backward compatibility.

**Comment by shcheklein** [comment]
@efiop yeah, I think you there was some misunderstanding by what I meant by default behavior. I meant to make it part of the `--overwrite` option. Basically that prompt that ask you if you want to overwrite the existing file should ask something like "Do you want to overwrite ... and potentially delete orphaned outputs ...". Versus making a second addition prompt to ask separately about outputs.

**Comment by dberenbaum** [comment]
A lot has changed since this initial request. The basic idea is still relevant, but seeing as it's been so long without much momentum, I'm going to close this one until there's more interest.
