### ISSUE TITLE
run/repro: support config option to opt-out out of fish warning

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1765]
See https://github.com/iterative/dvc/issues/1307#issuecomment-475305943

**Comment by efiop** [comment]
For the record, maybe https://github.com/iterative/dvc/issues/1307#issuecomment-536635027 would be better.

**Comment by efiop** [comment]
Closing for the lack of interest from users.

**Comment by jhrmnn** [comment]
> Guys, we were thinking about maybe making dvc fallback to another shell like sh (usually linked to something simple as dash) or bash when we detect fish, so that we can at least run your commands in the same environment. Maybe even make that configurable. What are your thoughts on that? I'm not that familiar with fish, so it is hard for me to tell how essential fish-specific syntax is for you in your pipelines.

I can't find a reference, but AFAIK `SHELL` is supposed to point to user's preferred interactive login shell, not the shell program used to execute non-interactive shell code. For example, `os.system()` or `subprocess.run(..., shell=True)` don't run `SHELL`, but `/bin/sh` by default. I can't imagine a user of Fish shell would expect DVC to run the command through Fish shell, and not through some POSIX compatible shell. So I would suggest for DVC to behave as Python in this regard, and run everything through `/bin/sh` unless instructed otherwise.
