### ISSUE TITLE
Skip staging when calling dvc add?

### ISSUE THREAD

**Issue by p00temkin** [iterative/dvc#2123]
Current ML pipeline involves ingesting a continous feed of small immutable files (5-20MB), appearing in a date based folder structure. 

Although dvc is not optimized for directories with many files, the usercase seems reasonable:

For every folder matching current date, run 
1) dvc add <datefolder>/*.csv
2) git add <datefolder>/*.dvc + .gitignore
3) dvc push
4) git push

dvc works great for this, but quickly slows down when the number of dvc files grows slightly within the folder. If there are 500 files already tracked and 10 new show up, the staging step called for every new file will process the previous 500 dvc files as part of the call to _create_stages() in dvc/repo/add.py. 

Since the staging step will happen again on "dvc push" (step 4), simply removing the staging part of "dvc add" makes the above pipeline work ok. 

Have just began experimenting with the codebase so not sure if this change has other negative impacts. The core issue seems related to the expensive stages() function in dvc/repo/__init__.py, which also highlights the issue in its comment:

        """
        Walks down the root directory looking for Dvcfiles,
        skipping the directories that are related with
        any SCM (e.g. `.git`), DVC itself (`.dvc`), or directories
        tracked by DVC (e.g. `dvc add data` would skip `data/`)

        NOTE: For large repos, this could be an expensive
              operation. Consider using some memoization.
        """

Would it make sense to add a "--skip-staging" option to dvc to use as part of step 2 in the above pipeline?

**Comment by efiop** [comment]
Hi @p00temkin !

Do you actually want to track each individual file in that directory or do you want to track that directory as a whole? E.g. if you have a directory `data` with files inside, you could simply do `dvc add data` and not `dvc add data/*` or `dvc add -R data`. The latter command will even print a warning these days asking if you really mean to do that. Indeed, the more dvc files there are in your repo, the harder it is for dvc to work with it, but, as I've noted, you could and probably should track your directories as a whole if you treat them that way, and so it will not create an excessive amount of dvc files. Also, when you are tracking directory as a whole, `dvc status` and `dvc repro` will be able to tell if you've added/removed any file in that directory, and will be able to handle it properly, instead of making you manually add new files one-by-one.

**Comment by p00temkin** [comment]
Yes tracking the files individually in the git repo is required in this specific scenario. We actually have multiple sites running the above pipeline as "data producers", where enrichment happens before pushing to the content to s3 with dvc. The "data consumer" side consists of workers running "git pull && dvc pull -f" before training, and this runs very smoothly. 

But we just implemented a simple alternative approach for the producers, where they would delete their local dvc files as soon as they have been pushed. For now this allows us to use dvc "as-is" with no additional feature flags and also speeds up "dvc push". A bit messy but works :)

Thanks again for the quick reply, closing this feature request
