### ISSUE TITLE
build: windows: investigate improper version

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2191]
https://github.com/iterative/dvc/releases/tag/0.50.0

```
dvc-0.50.0.a54a34.mod.exe
```

should be

```
dvc-0.50.0.exe
```

**Comment by ryokugyu** [comment]
@efiop where to start looking for this issue?

**Comment by efiop** [comment]
@ryokugyu the script that is generating the version is in `scripts/innosetup/config_gen.py`. It is importing `__version__` from dvc that is in the environment. In appveyor.yml(which is building this exe on CI) we are installing dvc locally with `pip install .` and I'm not sure if `config_gen` got the `__version__` from the repo itself or from the installed dvc package. One of the possible solutions is to just modify config_gen to get the _BASE_VERSION from dvc/version.py, which is always present during the build from our repo.

**Comment by ryokugyu** [comment]
i installed dvc via `pip install dvc` on my machine.

when running `dvc version` or `dvc --version`
![dvc_vesion_windows](https://user-images.githubusercontent.com/16274905/60188451-e9441380-984c-11e9-969f-e483dbafddd4.PNG)

 i am getting this.

**Comment by efiop** [comment]
@ryokugyu with `pip install dvc`? I meant `pip install .`, we are using that in appveyor.yml. The `dvc version` itself is working fine, tested it too, the issue is somewhere during the build process on appveyor.

**Comment by efiop** [comment]
@ryokugyu Here is where we are installing dvc twice (this is a bug, probably don't need the latter one) https://github.com/iterative/dvc/blob/master/.appveyor.yml#L55
```
  - pip install .[all,tests]
  - python setup.py install
```
Maybe the latter one is causing this issue. After that, we are running https://github.com/iterative/dvc/blob/master/.appveyor.yml#L73
```
.\scripts\build_windows.cmd
```
which is building the executable with a wrong version.

**Comment by ryokugyu** [comment]
> @ryokugyu Here is where we are installing dvc twice (this is a bug, probably don't need the latter one) https://github.com/iterative/dvc/blob/master/.appveyor.yml#L55
> 
> ```
>   - pip install .[all,tests]
>   - python setup.py install
> ```
>
> Maybe the latter one is causing this issue.

so, we just remove the `python setup.py install`? 
and then how to test it?

**Comment by efiop** [comment]
@ryokugyu To test it:
1) make sure there is no dvc installed (`where dvc` should not print anything)
2) do `git checkout 0.50.0` 
2) run `pip install .`
3) run `.\scripts\build_windows.cmd`
4) check that created dvc-*.exe has proper version

**Comment by efiop** [comment]
Still persists in 0.50.1 https://ci.appveyor.com/project/iterative/dvc/builds/25560657/job/cevfj2se81oiigs4

**Comment by pared** [comment]
#### Ok so here is why we get this strange number of version:
- when installing we get the version of dvc to properly name executable
- if current branch is tagged and unchanged, we will name it as version number (`dvc-0.50.0.exe`)
- if something has been changed, we will add first 6 letters of revision `sha`, which results in `dvc-0.50.0.a54a34.mod.exe` 

#### But why is it happening on freshly checked out 0.50.0 version? 
- to install it on windows we need to download some dependencies (dvc_left.bmp, dvc_up.bmp, dvc.ico) using dvc. 
- calling `dvc` cause repo initialization
- repo by default should ignore [file list](https://github.com/iterative/dvc/blob/a54a34042ef637de1d8f1b715addc4d107f47547/dvc/repo/__init__.py#L140)
- problem is that `.gitignore` on this branch did not included `/repos`
- pulling causes adding `/repos` to `.gitignore`, branch is unclean
- during installation new version name is introduced, because branch is not clean

#### Proposed solution

- introduce `/repos` to master `.gitignore` to avoid same bug in the future

- we could replace released windows binary with build that has been build after `git reset --hard`, which should follow pulling `dvc_left` and the rest

**Comment by pared** [comment]
Fix has been introduced by @Naba7 in #2195, thanks @Naba7!

**Comment by efiop** [comment]
@pared so you are confirming that it is fixed? Should we close this?

**Comment by pared** [comment]
Yes, checked on master, pulling the dependencies does not introduce changes to the repo.

**Comment by pared** [comment]
I am closing the issue, next release should not have such problems.
