### ISSUE TITLE
import: strange error with path ending in `/`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2237]
```
DVC version: 0.50.1
Python version: 3.7.3
Platform: Darwin-18.6.0-x86_64-i386-64bit
```

> First `dvc init` an empty DVC repo and run the following inside. In my case the working dir is called `emptydvcrepo`.

```console
$ dvc import https://github.com/iterative/example-get-started data/prepared/
...
ERROR: failed to import 'data/prepared/' from
'https://github.com/iterative/example-get-started'. - current working directory
'/path/to/emptydvcrepo' is specified as an output in 'emptydvcrepo.dvc'. Use another CWD
to prevent any data removal.
```

Notice the given `path`, `data/prepared/` ending with `/` and the error mentioning an inexistent DVC-file called `emptydvcrepo.dvc`.

It works normally without the slash.

**Comment by MalaysiaMariuane** [comment]
https:#//github.com/iterative/example get-started data prepared

**Comment by pared** [comment]
The problem is that when generating default default_out name [in imp_url](https://github.com/iterative/dvc/blob/0ab55f84ba279c22efcc7d2fc46aafa9f0243929/dvc/repo/imp_url.py#L13) we do not normalize path, so basename for anything ending with '/' will be ``, which will lead to some strange behaviour, like creating stage file with repo directory name.
