### ISSUE TITLE
Athena Views on top of S3

### ISSUE THREAD

**Issue by dancsalo** [iterative/dvc#2321]
I have an S3 bucket set up as a remote for a DVC project. I would like to use Athena to query the bucket, but it seems that DVC has an unusual way of storing data in the remote, and I can't seem to figure out how it's structured.

Any ideas? It would be great to be able to set up Athena on a S3 bucket managed by DVC. In essence, point to a DVC commit and query that snapshot of the data.

**Comment by efiop** [comment]
Hi @dancsalo !

DVC cache format is actually pretty simple. Basically any cache file is just your plain unchanged data file, named by its checksum. We are using subdirectories for optimization, so that you can shrink down the number of files you have in a directory. So for example, say your `data.txt` has checksum of `123456`, then dvc will store it at `12/3456` cache file. So there are no real names in the cache, we use our dvc-files for those (this is done for optimization, so you don't have to duplicate your cache file if you have the same file in multiple places).

As to Athena, I'm not quite familiar with it, so it would be great if you could describe your scenario a little more :slightly_smiling_face:

**Comment by shcheklein** [comment]
This is a really interesting question. We have a few functions to reference data via Git repo - `dvc import`, `dvc get`. But I'm not sure how this Athena integration should look like.

One of the possible solutions to this is to use external outputs (https://dvc.org/doc/user-guide/external-outputs). This way you can version certain data on S3 and it will be readable for Athena in a regular way. But to switch to the previous version you will need to run `dvc checkout` from the command line.

Would be great to lear more indeed to give a better advice? :)

**Comment by efiop** [comment]
@dancsalo Closing as inactive. Please feel free to reopen.

**Comment by karrtikiyer** [comment]
I have a similar question, not sure if it is the same.
Say I have set up a DVC pipeline, in which the first step is get_data, which loads the data from Athena using SQL queries.
When I run dvc repro, will this step get executed every time even if the data underneath Athena in S3 buckets might have not changed? Is there a way that DVC can determine if get_data should be executed again?

**Comment by dberenbaum** [comment]
@karrtikiyer You would have to point to the underlying s3 data as a dependency if you want DVC to be able to determine if get_data should be executed again.

**Comment by dberenbaum** [comment]
I don't have any examples for Athena, but if you know where the data is in s3, you can use this to see how to point to it as a dependency: https://dvc.org/doc/user-guide/external-dependencies.

**Comment by karrtikiyer** [comment]
Thanks @dberenbaum , I am wondering even if I get handle to the underneath bucket whether it will help. I am loading a part of the data using SQL where clauses, so ideally I would want this stage to run only if there is change in this filtered data. The underneath S3 data will have complete data and that would almost change every day. I was thinking if I can add a pre-get stage, which will get some summary stats of the get-stage, say number of rows & last modified time-stamp, and if there is change to that then execute the get-stage. What do you think of this approach?

**Comment by dberenbaum** [comment]
Sounds good! I think these type of "hacks" are pretty typical for SQL-like extracts.
