### ISSUE TITLE
run: warning/exception when dependency is a dvc-file

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2345]
It doesn't make a lot of sense to depend on a dvc-file, however, the interface is not intuitive enough to prevent this.

If we want to allow this behavior, it should be with a warning.

**Comment by efiop** [comment]
As a first step we might just add a check that dependency is not a dvc file. Having it as a feature also sounds quite neat, so one could do `-d my.dvc` which would mean "depend on all outputs of my.dvc". Not sure if that feature is desirable though, since it might be used by accident causing some obscure bugs in the pipeline.

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/605892459461083140

**Comment by mroutis** [comment]
ohh, @efiop, that sounds really neat! never thought about it, and it make sense since "the output of  a stage become the input of the next one".
