### ISSUE TITLE
DVC run -d error message is confusing

### ISSUE THREAD

**Issue by amutz** [iterative/dvc#2439]
Hello,

If you create a stage that depend on the contents of a bucket with something like `dvc run -d gs://some_bucket/` you will get this error message:

failed to run command - missing dependency

What this should say is "Depending on a bucket is unsupported.  Please depend on specific files within the bucket."  or something like that

**Comment by efiop** [comment]
Hi @amutz !

Thanks for the feedback! I would probably just go ahead and implement support for directories. A lot of generalization is already there as local and ssh support directories. I'll close this one in favor of https://github.com/iterative/dvc/issues/1654 . Basically, in order to implement a meaningful message, we need to implement RemoteS3.isdir method, at which point we might just go right ahead and fill 1 or 2 additional methods needed for full blown directories support.
