### ISSUE TITLE
detect multiple dvc installations in PATH and warn about them

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2567]
We've sometimes seen users installing dvc through multiple packages (e.g. deb and pip) and not realizing it. It would be nice to simply check if there are any `dvc` installations in PATH and warn that this might be a mistake.

**Comment by shcheklein** [comment]
I wonder if there are examples of tools that are doing something like this?

**Comment by efiop** [comment]
@shcheklein I'm sure I've seen a few doing that. Can't remember the specifics right now, though.

**Comment by mroutis** [comment]
@shcheklein , good question, @shcheklein , don't know of any, personally :(

Usually you use the distribution's package manager when possible; `pip` is cool but you need to take care of the way it interacts with the environment nice and maintaining it updated.

I'm not sure if tools actually "deal" with this. It is a _common problem_ but I'll hesitate to "solve it" from our side, since there can be a lot of _pollution_ on the _userland_.

**Comment by Suor** [comment]
Agree with @mroutis we shouldn't solve it with any checks. If we can solve this with docs that would be nice though.

**Comment by Suor** [comment]
BTW, `pip --version` provides a related hint:
```console
$ pip --version
pip 19.2.3 from /home/suor/.virtualenvs/dvc/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by efiop** [comment]
@Suor Making `dvc version` check that would be acceptable for me too :slightly_smiling_face:
