### ISSUE TITLE
ui: add a way to undo `dvc add` easily

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2575]
Maybe repurpose `dvc remove` for this, which at least be somewhat intuitive.

The hard part here is removing added file from cache: `dvc gc` is dangerous now and might be slow, simply removing cache file doesn't account for possible other refs to it.

This is inspired by https://github.com/iterative/dvc.org/issues/625 and a corresponding Stackoverflow question.

**Comment by dashohoxha** [comment]
@Suor Are you suggesting that `dvc remove file.dvc` removes the cached outputs of `file.dvc` and the `file.dvc` itself, but does not touch the files on the work place? This would indeed undo `dvc add file`. Maybe it should also delete the output files from `.gitignore`, to be exactly the undo operation.

**Comment by Suor** [comment]
@dashohoxha basically yes. We need to decide on retiring current `dvc remove` behaviour first though.

**Comment by dashohoxha** [comment]
>  @Suor: We need to decide on retiring current dvc remove behaviour first though.

@shcheklein has already asked for `dvc remove` to be deprecated/removed. I proposed that maybe we should improve it, instead of removing. But now I think that your approach of re-purposing it is better.

**Comment by mazzma12** [comment]
Hi, what about `dvc reset` to follow git naming?

**Comment by dashohoxha** [comment]
@mazzma12 The analogy between Git and DVC is not perfect because DVC does not have an intermediate stage, before you commit. When you make `dvc add` it also does an implicit `dvc commit` (saving file to cache). To remove from Git a file that is committed by mistake you actually need `git rm --cached file && git commit --amend -CHEAD` (https://help.github.com/en/enterprise/2.15/user/articles/removing-files-from-a-repositorys-history#removing-a-file-added-in-the-most-recent-unpushed-commit)

But `dvc reset` makes sense to me, since `dvc remove` might seem a bit scary to a beginner. Even `dvc untrack` would be ok for me.

**Comment by Suor** [comment]
git reset is a bad name, we shouldn't use it as a guide.

вс, 6 окт. 2019 г., 15:35 mazzma12 <notifications@github.com>:

**Comment by casperdcl** [comment]
> git reset is a bad name, we shouldn't use it as a guide

maybe bad but the functionality will be understandable by end users without much explanation.

**Comment by shcheklein** [comment]
Before we discuss name, let's try to come up with a some description on what this command supposed to do in what cases? Then it should be easier to discuss is `reset` relevant or not. As it often happens I think we have a bit different implementations/behavior in mind.

**Questions I have im mind:**

* does it accept DVC-file, output path?
* what does it do in case of no arguments (default)?
* does it only affect cache and/or workspace?

**Comment by soerface** [comment]
I'm just getting started with DVC so I will miss a lot of things, but maybe my impression as a new user helps.

As I followed the [dvc.org video tutorial](https://dvc.org/doc/start/data-versioning) I accidentally ran `dvc add data` instead of `dvc add data/data.xml`. As an inexperienced dvc (but experienced git) user, I tried undoing my mistake with `dvc rm data`. I would have been fine if `rm` actually deleted my data; if it did, I would have expected an option similar to `git rm --cached`.

I tried `dvc remove` but was irritated since I know nothing yet about stage entries. `dvc remove data` told me:

```
ERROR: failed to remove 'data' - 'dvc.yaml' does not exist.
```

It was frustrating to be able to add a file, but removing it requires some additional file I know nothing about. But I'll guess this is fine if the command will be improved or deprecated anyway.

---

> does it accept DVC-file, output path?

Since I don't know yet much about the `*.dvc` files, I'm intuitively trying to run commands on paths, not on dvc managed files (I wouldn't run git commands on the `.git/` directory either)

> what does it do in case of no arguments (default)?

Just show usage as `git rm` does?

I'll just remove the whole hello-world and will finish the tutorial first, but maybe my new-user-experience is of any help :)

**Comment by jorgeorpinel** [comment]
Related: #5791

**Comment by jorgeorpinel** [comment]
> The hard part here is removing added file from cache: dvc gc

Seems like that'll be the only part left after #5757.

**Comment by efiop** [comment]
Closing as stale.
