### ISSUE TITLE
Add stats

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#2658]
continuation of #2546

- [ ] tidy up remaining stats (no need for `<00:00`, add total size in bytes, etc)
- [ ] add progress to other uses of `stage.dump`
- [ ] profile `repo.check_modified_graph()`, `stage.save()`, `stage.dump()` etc to find out what other functions are slow, perhaps add progress for them too
  + md5sums only take about 10% of the total time. There must be other more time consuming functions

**Comment by shcheklein** [comment]
moved this to #2699

**Comment by casperdcl** [comment]
K, not sure why a new issue was needed but whatever...

**Comment by shcheklein** [comment]
@casperdcl I realized that the ticket I created was overlapping with this to some extent - both are about improving `dvc add` output. Probably, it's better to see the full scope and collect it under one issue. Since the second one had more comments already, and I was more comfortable editing my own stuff I decided to consolidate everything in that one :) 

No strong opinions here, feel free to revert and split them in a way you feel better.
