### ISSUE TITLE
is it possible to run more than one dvc pipeline in the same dvc context?

### ISSUE THREAD

**Issue by aabramovrepo** [iterative/dvc#2851]
Hi,

   I'm trying to run multiple dvc pipelines (trainings) on the same data in the same dvc context. The only difference is .dvc config file. I'm getting the following error message:

`ERROR: cannot perform the cmd since DVC is busy and locked. Please retry the cmd later.`

Is it somehow possible to start multiple dvc processes at the same time?

Thanks!

Best,
Alexey

**Comment by efiop** [comment]
Hi @aabramovrepo !

The issue is that dvc is not able to run multiple instances at the same time https://github.com/iterative/dvc/issues/755 . It is a known issue and we are working on a solution in https://github.com/iterative/dvc/pull/2584 , which should hopefully be done soon-ish. As a workaround, you could try re-running individual long-running commands by-hand and then `dvc commit`-ing the result.

I'll close this for now as a duplicate of #755

**Comment by aabramovrepo** [comment]
@efiop: thanks for your response, we are waiting then...

**Comment by free-soellingeraj** [comment]
Is this resolved?

**Comment by efiop** [comment]
@free-soellingeraj We are releasing locks since #2584 Are you running into any particular issues?
