### ISSUE TITLE
`dvc repro` for multiple git revisions

### ISSUE THREAD

**Issue by wattik** [iterative/dvc#2936]
The problem:

You have trained several models and stored their performance in `metrics.json`. Each model has a corresponding tag in a git repo. So each git version of `metrics.json` stores the performance of the corresponding model. To compare the metrics, one can for instance run `dvc metrics show -T`.  Now, say you want to enrich the evaluation statistics and add more metrics into `metrics.json`, thus you modify the evaluation script that produces `metrics.json`. What is a best way of obtaining the new metrics for all models? At this point, one has to manually create a new branch, merge in the new evaluation script and run `dvc repro`. All of that for each model (i.e. for each tag). 

Is there a way to make this procedure more automatic?

**Comment by efiop** [comment]
Hi @wattik !

Since you are modifying the script, there is no way around modifying it for all the tags, in your current setup. I would consider using subdirs for all those models, if you feel like this situation happens a lot and the script is the same for all of them. Would that be suitable solution for your scenario?

**Comment by shcheklein** [comment]
@wattik good question, and I don't have any ideas from the top of my head except some crazy stuff like going with bash and retrospectively applying changes to all commits + running `dvc repro` on them (means, redoing Git history with amend, rebase and other destructive commands).  

Have you seen other tools that are able to do this kind of stuff - rerunning all the experiments with some changes applied in a bulk? I'm just wondering if you have any ideas how can it be organized.

**Comment by wattik** [comment]
@efiop Of course, I can rearrange the models and use subfolders. But again, that is what I am trying to avoid when I use DVC (or other versioning systems). 

@shcheklein one thing on my mind is to have a branch per model. Then you cherrypick the change to each branch (or use a similar git hack, for instance the one you mentioned). But this seems hacky to me -- sort of versioning through obscurity. 

I realised that the need for executing `dvc repro` for several models/branches/tags/etc is a general thing. Think for example of regenerating up-to-date training data and retraining all candidate models on it to choose one to deploy.

I do not have any solution right now and I think it has not yet been tackled entirely. But a rough idea: It seems to me that each transformation script (that is each stage.dvc file) shall somehow be versioned independently of other transformation scripts in the pipeline (preceding and following stage.dvc files). For instance, the `train.py` versions correspond to a model, the `evaluate.py` file does not merely change at all, but `evaluate.py` may have different versions as you expand your metrics. So ideally, if you change `evaluate.py`, you expect that the pipeline is ran for all versions of `train.py`. On the other hand, you arrive at a Cartesian product of versions which is hard to capture with git. 

I understand this is a very vague description of my problem. I currently do have a technical solution, nor a proposal. But this may drive your thoughts to come up with something.

**Comment by shcheklein** [comment]
@wattik it makes sense. I don't have a solution either. It would be great if read and chime in in this epic, btw - https://github.com/iterative/dvc/issues/2799 - some decisions that are being discussed in it can definitely affect this scenario.

Thinking more about this case I realized that I definitely don't like an idea of amending Git history (the one I suggested) - that's important to keep, right? that's how you can see the progress, return back if something happens, etc. Otherwise we are undermining the whole concept of versioning.

Also, whenever we change something and do a new run it's better to have an option to save it. I would even say - it's better to save it no matter what - so there should be some mechanism. Besides using branches (and do a new commit every time you change and run something) and directories (which still feel to me like a hack ppl use because we don't have any other good ideas yet) I don't have any other option.

I wonder what are your thoughts about branches and/or directories? Could you analyze why don't you like them? May be it's time to come with light-weight branches/experiments or something? :)

**Comment by efiop** [comment]
Closing as stale.
