### ISSUE TITLE
Installation is really tedious

### ISSUE THREAD

**Issue by r0f1** [iterative/dvc#2989]
Hi, I am using linux and the latest version of Anaconda and I have to say that installation using pip is really really tedious. Could you please fix these issues such that newcomers have an easier time using dvc?

1) On installation one gets the following message: `ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.` So there is an issue with the installed PyYAML version. dvc wants to install its own version, but can't. 
Workaround: `pip install --ignore-installed dvc`.

2) Running dvc leads to the following message: `AttributeError: module 'enum' has no attribute 'IntFlag'`. 
Workaround: `pip uninstall enum34`.

Thank you.

**Comment by efiop** [comment]
Hi @r0f1 !

1. If you are using anaconda already, why not install dvc from anaconda as well?

2. It is a known issue https://github.com/iterative/dvc/issues?q=is%3Aissue+enum+is%3Aclosed but it is caused by some other package in your workspace installing enum34, which shouldn't be installed for this python version. There is not much we can do about that, except recommend using pipenv or some other type of isolation. Or use other packages like brew, that have isolation built-in.

**Comment by r0f1** [comment]
Thanks for the quick response. Yes, those issues are related to my environment. I just checked that if I create a new, fresh environment with `conda create -n testtest python=3.7`, everything seems to work. Regarding 1), I never installed anything using distutils. I must be some other package that I installed in the past that is responsible for this. I have so many packages installed in the conda `base` environment that it is hard to say which package is the culprit. Anyway, thanks for your response. Maybe this issue will help future googlers, that encounter the same problem :)

**Comment by efiop** [comment]
@r0f1 Sure! Thank you so much for the feedback! 🙏

**Comment by casperdcl** [comment]
Running `conda update conda --force` in the broken environment *may* fix the issue.

**Comment by caseyjconger** [comment]
I would just like to throw out that I ran into this issue as well while trying to install it in a docker container based off of `jupyter/tensorflow-notebook`.

Since these are the official images and they are pretty ubiquitous  to use as a base (and thus not know all the details of how it was set up) it would probably be worth either putting a note in the documentation or even finding a fix on DVCs end.

**Comment by efiop** [comment]
@caseyjconger Great idea! Created https://github.com/iterative/dvc.org/issues/983 to address that. Thanks for the feedback!
