### ISSUE TITLE
add support of team drives for GDrive remote

### ISSUE THREAD

**Issue by antonkulaga** [iterative/dvc#3015]
Google TeamDrives are common for sharing data in academia and education as they provide unlimited storage for free. Right now dvc supports only personal googledrive and it is not clear how to configure a remote to a folder inside of the teamdrive to which you have write access to.

I believe that teamdrive support will be very valuable for dvc (at least we use team drives a lot in our lab). Teamdrives are already supported by rclone and other gdrive libs (see https://github.com/gsuitedevs/PyDrive/issues/149 )

**Comment by efiop** [comment]
Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/661010338879111179

**Comment by efiop** [comment]
@antonkulaga FYI: we've released 0.83.1 with this feature, but weren't able to include newer version of pydrive (because it is not released yet and pypi doesn't allow github deps 🙁 ) so you will have to manually `pip install git+https://github.com/gsuitedevs/PyDrive` after you install dvc. We are currently working on a more robust solution, so stay tuned! 🙂

**Comment by efiop** [comment]
For the record: we've forked pydrive to have it actively maintained and will soon release new dvc version based on our fork https://github.com/iterative/dvc/pull/3161.
