### ISSUE TITLE
refactor: use relative Python imports instead of absolute ones

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#3109]
Extracted from https://github.com/iterative/dvc/issues/1818#issuecomment-570020128

**Comment by alexmojaki** [comment]
I have a PR for this in #7962. @efiop has [pointed out](https://github.com/iterative/dvc/pull/7962#discussion_r912481987) that relative imports can sometimes be unreadable, e.g. `from .....proc.manager import ProcessManager`. So a more nuanced rule like "relative up to a maximum of N dots" may be required. Automating this gets a bit more messy though, as [a PR to add that kind of config to the tool was already rejected](https://github.com/MarcoGorelli/absolufy-imports/pull/53).

FWIW, I don't personally think it's very important for imports to be a certain way, but if you want to enforce a convention then I agree with [this comment](https://github.com/PyCQA/isort/issues/1677#issuecomment-1120254892).

**Comment by efiop** [comment]
I'm not sure that there could be a readable consistent policy except for enforcing absolute imports everywhere. We should've clarified it before, but this issue is really about using relative imports where it makes sense and makes code nicer (e.g. nested modules where it makes more sense to use `.` instead of `dvc.module.`). But I guess that makes this issue not very actionable, as it is hard to define the endgoal. Let's close this one then.

@alexmojaki Thanks taking your time to look into it! 🙏
