### ISSUE TITLE
api/get: cannot show url for git only repos

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3181]
There's no straight way to support direct url to files in git repos unless we do some kind of magic. 

Currently, `--show-url` fails with:
```sh
➜ dvc get https://github.com/schacon/cowsay install.sh --show-url          
ERROR: failed to show url {} - URL 'https://github.com/schacon/cowsay' is not a dvc repository.
```

Similarly, `dvc.api.get_url`:
```
> import dvc.api
> dvc.api.get_url("install.sh", repo="https://github.com/schacon/cowsay")
UrlNotDvcRepoError: URL 'https://github.com/schacon/cowsay' is not a dvc repository.
```

**Comment by Suor** [comment]
Not clear how what it should show.

**Comment by skshetry** [comment]
This issue is just opened for discussion.

But, one idea was to use `https://raw.github.com/username/project/master/file.txt` kind of URL if it's a GitHub repo.

**Comment by mroutis** [comment]
@skshetry , I would way for someone to request this :sweat_smile:

**Comment by jorgeorpinel** [comment]
> one idea was to use `https://raw.github.com/username/project/master/file.txt` kind of URL if it's a GitHub repo.

Is this a Git standard? `raw.[git-url]/user/repo/branch/path`? Otherwise, if it's Github specific, DVC would need to handle other servers specially and some may be impossible to guess. In that case I would incline to just show a better error message instead. Something like `` `--show-url` only works for DVC repos.`

**Comment by pmrowla** [comment]
That's specific to github.
