### ISSUE TITLE
Any suggected way to use dvc from python?

### ISSUE THREAD

**Issue by byaka** [iterative/dvc#3278]
We want to use dvc commands right from our software.

As i see dvc dont have stable api for this.

what way u suggest?

i find [this](https://medium.com/qonto-engineering/using-dvc-to-create-an-efficient-version-control-system-for-data-projects-96efd94355fe) and here they use it like
```python
from setuptools import setup
from setuptools.command.build_py import build_py
from dvc.main import main


class FetchError(Exception):
    pass


class AssetFetcher(build_py):

    def run(self):
        print('Start pulling dvc asset')
        
        ret = main(['pull', 'train.dvc'])
        if ret != 0:
            msg = 'DVC returned error code {} while pulling assets'
            raise FetchError(msg.format(ret))
        
        print('Asset pulled successfully !')
        build_py.run(self)


setup(
    name='vat_detection',
    # and many other arguments ...
    cmdclass={'build_py': AssetFetcher}
)
```

Is this way ok or it can breaks on new versions?

**Comment by mroutis** [comment]
@byaka , that's a good option, if you need more control over the operations, you can try using `dvc.repo.Repo`

**Comment by efiop** [comment]
@byaka Your example uses CLI through a python entrypoint. That is pretty stable, almost no chance of us moving `main()` somewhere else anywhere in the future. So that (or just `os.system("dvc ...")` or Popen) totally works :slightly_smiling_face:

The Repo class mentioned by @mroutis is officially not as secure from changes as CLI, but you should be fine, as long as you use specific dvc version as a dependency in your project. :slightly_smiling_face:

**Comment by byaka** [comment]
Good to know this, thx!
We give it a try :)
