### ISSUE TITLE
dvc cache dir: carry over the existing cache

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#3300]
What do I suppose to do with the existing cache dir after `dvc cache dir ../../my_shared_cache`? Probably I should copy it to the new one (`cp -r .dvc/cache/* ../../my_shared_cache && rm -rf .dvc/cache` ).

Is there any reason why the command does not do that by default (or through some option like `--carry-over`)?

**Comment by efiop** [comment]
@dmpetrov `cp & rm` will be really slow, but I do understand that you've suggest it because it would be atomic unlike moving files one by one. The main reason we don't do it is because it is very heavy-weight and often the cache dir we move to already has something in it (e.g. shared machine scenario). Doing that by default would be a bit too much. Though, maybe `dvc cache move` would be a solution? Not sure if we should take on that functionality in dvc itself, feels like it is out of our focus.
