### ISSUE TITLE
DVC does fails when the md5 hash contains only numbers

### ISSUE THREAD

**Issue by charlesbaynham** [iterative/dvc#3331]
The description is in the title. When an md5 hash randomly contains only numbers DVC fails,  reporting

    ERROR: failed to update 'step_X.dvc'. - DVC-file 'step_X.dvc' format error: expected str for dictionary value @ data['md5']

This should happen on average once for every 3 million hashes. For a big project with a lot of files that get changed, that's not so implausible.

**Comment by efiop** [comment]
Hi @charlesbaynham ! Could you please show `dvc version` output?

**Comment by efiop** [comment]
For the record: can reproduce this myself as well, by modifying md5 in a dvc file by-hand. We've had a similar issue with pyyaml earlier, need to check this.

**Comment by efiop** [comment]
Ok, so both pyyaml and ruamel are affected, so we need to tweak our SCHEMA instead. Working on a fix...

**Comment by efiop** [comment]
Ok, in fact, this is pyyaml's fault. We are using it sometimes instead of pyyaml to improve the performance, but the very serious downside is that pyyaml doesn't preserve the types of values that well. So if md5 is `"1111"`, pyyaml will write it down as `1111` and will then read it as `1111`(int), while ruamel writes it down as `'1111'` and reads it as `'1111'`(str). Looks like we could still handle it alright by expanding our hash schema to `str, int`, so that if a hash (e.g. md5, some etag or whatever)  is written as integer, we will try to convert it. There are some corner cases to that approach like hex and octal numbers, but I we don't use hashes that might start with 0x or 0o and I'm not aware of any hashes like that, so we should be fine for now.

**Comment by efiop** [comment]
@charlesbaynham We are releasing 0.85.0 right now. Please upgrade, give it a try and let us know if that fixed the issue for you or not. Thanks for the feedback! :slightly_smiling_face:

**Comment by charlesbaynham** [comment]
Wow I think that's the fastest response I've ever seen on github! Thanks a lot, I'll give it a try
