### ISSUE TITLE
Add 'dvc mv'

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#336]
We have 'add' and 'remove', but lack 'mv'.

**Comment by dmpetrov** [comment]
Why is 'git mv' not enough?

**Comment by efiop** [comment]
Because dvc also needs to cleanup old data and create new link.

**Comment by dmpetrov** [comment]
It should be fine if you are talking about external links (links from external directories).

**Comment by efiop** [comment]
I will take a closer look soon just to be sure.

**Comment by matanster** [comment]
are `dvc add` and `dvc remove` features introduced post the stable version which we get through `pip` at present time? or is there an API reference beyond what we get with `dvc --help`?

**Comment by dmpetrov** [comment]
Yes, `dvc add` is one of the new commands. This is the way to remove unnecessary features out from DVC like `dvc import file.txt`.

In the new version, you suppose to import file by yourself and add the file as a data file by `dvc add file.txt`.

**Comment by matanster** [comment]
Thanks, keep it going! :-)

**Comment by dmpetrov** [comment]
It looks like we cannot just move data file without changing corresponding stage file and changing stage file **automatically** looks like a risky idea.

With the new design, the solution should be:
1. Modify the name in staging file `vi Posts.xml.dvc`. It is a manual but an easy step.
2. Copy the file `cp Posts.xml post.xml`
3. Convert the file into data file `dvc add post.xml` 
4. Remove the old file `dvc remove Posts.xml`.

Step (1) is not easy to automate because of paths in a command might be changed. We should make some assumption about the command line.

@efiop Any idea how to do that? If not then let's close the bug.

**Comment by efiop** [comment]
I actually think that 'remove' and 'mv' should only work with data sources, so that we don't even have to worry about cmds. I will add it soon.

**Comment by efiop** [comment]
Leaving this for next release.
