### ISSUE TITLE
Previous import stage disappears on import failure

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3362]
```sh
$ dvc import /path/to/existing/repo file
$ ls
file file.dvc
$ dvc import /path/to/not-existing/repo file
$ test -f file.dvc || echo $? # no files or import stages
1
```

Same thing happens when the repo is valid but the file does not exist.

**Comment by efiop** [comment]
@skshetry This issue affects any dvc command such as `dvc add/run/import/import-url`. The reason is that when you run the same command again, you are explicitly overwriting the dvc-file and if the operation fails we don't want to give you a false sense of successful operation. E.g. if you would run `dvc checkout` after that you won't run the risk of getting an old file and not even realising that.

**Comment by skshetry** [comment]
@efiop, I think the behaviour should be more robust. Right now, I guess this is a limitation of the way we collect stages or build graph ( that could be solved by `update/replace` methods in `repo.index` with a `trie`?)

**Comment by skshetry** [comment]
These days we fail with:
```console
unexpected error - [Errno 17] File exists: 'file'
```

For `--no-download` case, we do end up overwriting as the file won't exist in the workspace which is preventing this from happening. It is not ideal, but closing for now, as the above mentioned issue is somewhat fixed.
