### ISSUE TITLE
address `dvc list` review from Jorge

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3381]
Click https://github.com/iterative/dvc/pull/3246#pullrequestreview-362991972

**Comment by jorgeorpinel** [comment]
Awesome! Please also check the latest state of the changes in iterative/dvc.org/pull/967 so both sides are in sync when this is addressed 🙂

**Comment by jorgeorpinel** [comment]
Also, should the file name be `list.py`? its `ls.py` now.

**Comment by jorgeorpinel** [comment]
And not sure about the `target` name for the last param... Why not `path` like in `dvc get/import`?

**Comment by jorgeorpinel** [comment]
Another question here: is there an easy way to tell which files in the list are tracked by DVC and which ones by Git? This is kind of important for finding paths that can be sent to `dvc import/get`.

**Comment by JIoJIaJIu** [comment]
@jorgeorpinel  At this moment only coloring is supported as a way of the differentiating types of the files.
You may read more in [the comment](https://github.com/iterative/dvc/issues/3431#issuecomment-593560766)

**Comment by shcheklein** [comment]
@JIoJIaJIu I think that link is just somewhat relevant. We have two things to colorize in a different way:

1. DVC tracked files - e.g. we need to use a different color for a directory we did `dvc add data\` with. Or the same for `dvc add data\data.xml`. And we should have a flag (--outs?) to filter DVC "outputs" only.
2. DVC-files - we can use a color scheme for links, for example (since they serve to some extent as a link)
3. Git-traked .dvcignored files.

That link it probably relevant to 3 only, but most likely @jorgeorpinel was asking about 1.

**Comment by JIoJIaJIu** [comment]
> That link it probably relevant to 3 only

In the comment I provided info about **1** and **2** scenarios, but the main issue relates to **3**, right
Let me summarize it here then

We color output as `out=color`
```
LS_COLORS="out=01;37" dvc list ...
```
will color outs only

**Comment by jorgeorpinel** [comment]
OK thanks for the info guys, that's great to know. But since colorizing is not enabled by default (I assume) nor supported in every system, would it make sense to add another way to tell them apart? It can be as simple as a 2nd column in the output that has either `git` or `dvc`, or maybe only `out` for DVC outputs (stuff that you can `dvc import/get`). After all this was one of the main motivations for `dvc list` in the first place.

**Comment by shcheklein** [comment]
@jorgeorpinel what is the motivation for you to distinguish DVC-tracked and Git-tracked files by default? The whole point is to make the whole experience with get/import/list the same for all files as much as possible.

**Comment by jorgeorpinel** [comment]
True, I forgot you can get/import Git-tracked files now!
