### ISSUE TITLE
pyfastcopy causes BlockingIOError

### ISSUE THREAD

**Issue by murnanedaniel** [iterative/dvc#3395]
**Please provide information about your setup**

> DVC version: 0.83.0
> Python version: 3.6.9
> Platform: Linux-4.12.14-150.38-default-x86_64-with-glibc2.9
> Binary: False
> Package: pip
> Cache: reflink - not supported, hardlink - supported, symlink - supported
> Filesystem type (cache directory): ('gpfs', 'tlhome2')
> Filesystem type (workspace): ('gpfs', 'tlhome2')

-------------------------------------------

I am getting the error `BlockingIOError: [Errno 11] Resource temporarily unavailable` when running `dvc checkout`. This has been solved by uninstalling pyfastcopy, but for future reference I am submitting it as a bug report.

**Comment by murnanedaniel** [comment]
[dvc_debug.txt](https://github.com/iterative/dvc/files/4246099/dvc_debug.txt)
See output of `dvc checkout -v` for full details.

**Comment by efiop** [comment]
Hi @murnanedaniel !

Thanks for the report! We've removed pyfastcopy from deps for now, will release a new version soon.

**Comment by rxxg** [comment]
Unfortunately I don't have access to a Linux setup to test that module, I just put in the code for symmetry with the Windows version.  If nobody is complaining about Linux network perf you can probably just leave it out and wait for the transition to Python 3.8.

Otherwise it might be worth a bug report to the upstream project, but with no possibility to test it I'll have to let someone else handle that.
