### ISSUE TITLE
Faster data transfer from remote

### ISSUE THREAD

**Issue by vernt** [iterative/dvc#3407]
Currently transferring data from an ssh remote uses Paramiko. On my files I observe an 18x improvement in transfer rate by using rsync instead of `dvc pull`. Perhaps there are other options too. It would be nice to use some fast tools when they are available.

**Comment by shcheklein** [comment]
@vernt have you tried increasing number of jobs and checksum jobs (--jobs in the `dvc pull` and probably `dvc config core.checksum_jobs`) parameters? 

could you please share `dvc pull -v` with the latest DVC version so that we can see how much each operation takes (calculating md5s vs downloadin vs linking files to the workspace).

It would be great to see the profiler results as well:

`python -m cProfile -o dvc-pull.prof -m dvc pull -j`

**Comment by jorgeorpinel** [comment]
Just for references, here's some previous exploration along these lines: #2330

**Comment by efiop** [comment]
We've now migrated from paramiko to asyncssh (see https://github.com/iterative/sshfs), which is up to 4 times faster than old approach (https://github.com/iterative/dvc/issues/6064#issuecomment-876340381). We plan on pushing it even further in the future.
