### ISSUE TITLE
dvc pipeline show --ascii - visual bug since version 0.82.9

### ISSUE THREAD

**Issue by Noizecube** [iterative/dvc#3410]
DVC version: 0.82.9 and following
reproduced on several platforms, like:
4.15.0-55-generic #60-Ubuntu
macOS High Sierra 10.13.6
macOS Catalina 10.15.2

Hi,

the command "dvc pipeline show --ascii" seems to have a bug since version 0.89.9, which does not display the dependencies properly, when there is a branch in a Pipeline. 

I created a simple pipeline, which looks like this:

**Pipeline with Version 0.82.8**
<img width="440" alt="Pipeline with Version 0.82.8" src="https://user-images.githubusercontent.com/58767298/75341258-5e606080-5894-11ea-8317-5ddeaf79f5c2.png">

If i use the command "dvc pipeline show --ascii validation.dvc" with version 0.82.8, the whole pipeline gets displayed properly.
If i upgrade my Version to e.g. 0.83.0, the connection between "val.dvc" and the previous Stage is missing. If i use the command on val.dvc itself, the stages "train.dvc" and "validation.dvc" are missing (see screenshots).

**Pipeline with Version 0.83.0**
<img width="453" alt="Pipeline with Version 0.83.0" src="https://user-images.githubusercontent.com/58767298/75341262-5f918d80-5894-11ea-841c-e59b56dfed33.png">

**Pipeline with Version 0.83.0, when using val.dvc in the command**
<img width="227" alt="Pipeline with Version 0.83.0, when using val.dvc in the command" src="https://user-images.githubusercontent.com/58767298/75341265-5f918d80-5894-11ea-9a35-0e53619e5c55.png">

**Comment by pared** [comment]
Can confirm that issue still exists.
Reproduction script:

```
#!/bin/bash

rm -rf repo
mkdir repo

pushd repo
git init --quiet
dvc init -q

echo data>>data
dvc add data

dvc run -d data -f dvc_run.dvc -o processed_data "cat data>>processed_data"
dvc run -d processed_data -o val "cat processed_data>>val"
dvc run -d processed_data -o train "cat processed_data>>train"
dvc run -d val -d train -o validation "echo validated >> validation"
dvc pipeline show --ascii validation.dvc
```

**Comment by efiop** [comment]
Might be caused by https://github.com/iterative/dvc/pull/3217

**Comment by pared** [comment]
Ok, so:
1. @efiop  is right that the cause lies in #3217 
2. Before this change, when building graph for outs we iterated over all graph edges and have been adding them for display.
3. After the change, we used `dfs_edges` algorithm which, as stated in [source](https://github.com/networkx/networkx/blob/fd0ecd22723cb30a365511d324841a85caad589c/networkx/algorithms/traversal/depth_first_search.py#L25):
`Perform a depth-first-search over the nodes of G and yield
    the edges in order.`
So what does it mean, is that `dfs_edges` iterates over **nodes** using dfs and returns edges visited during traversal. That means that if some edges were not visited during traversal, it was not returned.
4. In order to obtain **all** edges, we need to use [`edge_dfs`](https://github.com/networkx/networkx/blob/fd0ecd22723cb30a365511d324841a85caad589c/networkx/algorithms/traversal/edgedfs.py#L17) which focuses on visiting edges, and not nodes.
