### ISSUE TITLE
Latest version of DVC does not work without GIT

### ISSUE THREAD

**Issue by sniranjan** [iterative/dvc#3474]
We build models locally and push them to DVC(S3) and we build docker containers(which are don't contain  GIT). The old version 0.71.0 used to work fine  but the latest version fails  with  the below error  "ERROR: unexpected error - /my-folder is not a git repository"

**Comment by shcheklein** [comment]
More context here:

https://discordapp.com/channels/485586884165107732/485596304961962003/687403454989467650

**Summary:**

We broke the compatibility after we introduced the `dvc init --subdir` and made `no-scm` mode explicit. If `.git` is not found DVC expects to find the `--no-scm` flag in `.dvc/config`. If flag is also not found it raises this error.

**Workaround:**

run: `dvc config core.no_scm true` 

It can be part of the script that creates a Docker image.

alternatively, include `.git` - it clearly can be suboptimal in some cases.

**Proposed steps:**

Since this error happens only in two situations:

1. legacy scripts, code
2. someone broke the existing repo (by deleting .git)

we can handle the error gracefully:

```
ERROR:  /my-folder is not a Git repository. Since version <V> DVC expects the directory it runs in to be a Git repository or explicit flag `core.no_scm` must be specified in the config. Run `dvc config core.no_smc true` if you don't need DVC to use Git in your setup. Read more information here - <make a troubleshoot link>
```

**Comment by efiop** [comment]
Closing as stale

**Comment by nameless0704** [comment]
I used `dvc config core.no_smc true `but raised another `ERROR: configuration error - config file error: extra keys not allowed @ data['core']['no_smc']`

**Comment by skshetry** [comment]
> I used `dvc config core.no_smc true `but raised another `ERROR: configuration error - config file error: extra keys not allowed @ data['core']['no_smc']`

Looks like you have made a typo: it should be `no_scm` instead.
