### ISSUE TITLE
remote: use progress bar when paginating

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3526]
Followup for #3501

**Comment by pmrowla** [comment]
Currently for `cache_exists()` threaded traverse, there is a single progress bar that shows that tracks how many cache prefixes (out of 256) have been fetched. For large remotes, fetching each prefix will still be a slow operation, and it may appear to the user that dvc is hanging.

Since we have an estimated size for the remote and know approximately how many objects/pages will be returned for each prefix, we can track progress for the total number of pages fetched rather than the number of prefixes fetched.
