### ISSUE TITLE
azure: support external dependencies and outputs

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3540]
As the title says, we currently do not support external dependencies and outputs from azure. So, 
`dvc import-url` and friends don't work.

#### Implementation
It should be trivial to implement.  `dvc` uses etag to ensure that it's same file. So, just need to implement following methods in [dvc/remote/azure.py](https://github.com/iterative/dvc/blob/master/dvc/remote/azure.py) similar to one in [dvc/remote/s3.py](https://github.com/iterative/dvc/blob/master/dvc/remote/s3.py):

https://github.com/iterative/dvc/blob/a1fe6c6f44777463876ad24ee0d162173999f9d3/dvc/remote/s3.py#L78-L79

> From Ruslan's reply on Discord: https://discordapp.com/channels/485586884165107732/485596304961962003/691327678271193160

Then:
- Implement a `DependencyAzure` and `OutputAzure` classes. Refer [DependencyS3](https://github.com/iterative/dvc/blob/master/dvc/dependency/s3.py) and [OutputS3](https://github.com/iterative/dvc/blob/master/dvc/output/s3.py) for the example.

- Add `OutputAzure` on [OUTS](https://github.com/iterative/dvc/blob/02f92b3ac85532d24ae94727a6071376dbf35452/dvc/output/__init__.py#L16), [OUTS_MAP](https://github.com/iterative/dvc/blob/02f92b3ac85532d24ae94727a6071376dbf35452/dvc/output/__init__.py#L24) and [CHECKSUMS_SCHEMA](https://github.com/iterative/dvc/blob/02f92b3ac85532d24ae94727a6071376dbf35452/dvc/output/__init__.py#L46) on [dvc/output/__init__.py](https://github.com/iterative/dvc/blob/master/dvc/output/__init__.py)

- Also `DependencyAzure` needs to be added on [DEPS](https://github.com/iterative/dvc/blob/02f92b3ac85532d24ae94727a6071376dbf35452/dvc/dependency/__init__.py#L19) and [DEPS_MAP](https://github.com/iterative/dvc/blob/02f92b3ac85532d24ae94727a6071376dbf35452/dvc/dependency/__init__.py#L29) on [dvc/dependency/__init__.py](https://github.com/iterative/dvc/blob/master/dvc/dependency/__init__.py).

P.S. I could be missing a few things though. :(

**Comment by steffansluis** [comment]
For the purposes of completeness and easy reference (this was also discussed on [Discord](https://discordapp.com/channels/485586884165107732/565699007037571084/713462619469643796 and in the [relevant PR](https://github.com/iterative/dvc/pull/3852)): 

From the [official API docs](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob):
> In version 2012-02-12 and newer, Put Blob sets a block blob’s MD5 hash value even when the Put Blob request doesn’t include an MD5 header.

If I am reading that correctly, it basically means that every blob will always have the content-MD5 property set on upload. Additionally, the [PUT](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob) request fails if the MD5 specified in the request doesn't match that of the computed one, so that means no blob can ever have an incorrect MD5. If the header is omitted, the MD5 is calculated anyway.

Nevertheless, testing with uploading a 4GB file through the web UI of Azure resulted in it not being assigned a `Content-MD5` property. Hence, apparently it does not actually work as expected. I have submitted a request to to Azure support to ask for clarification, explaining that ideally it would always have a correct `Content-MD5` property set. I'll provide an update of some kind when I get a response.
