### ISSUE TITLE
Make progressbar not change format

### ISSUE THREAD

**Issue by AljoSt** [iterative/dvc#3571]
When using tqdm in its default settings, `it/s` is changed to `s/it` for values below 1.0 (thus becoming bigger than 1.0). This happens e.g. for `dvc status -c` when the progress per `dir` is given. I think it would be better to be consistent about the format (so rather use `0.5 dir/s` instead of `2.0 s/dir`), as it's easier to see how the progress is going.

The behaviour can be altered with `bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_noinv_fmt}{postfix}]"`

**Comment by casperdcl** [comment]
thanks @AljoSt for bringing this up; but the problem is there are many cases where

- `file/s` is more appropriate because there are many files being processed per second
- `s/file` is more appropriate because it takes a long time to process a large file

So in general both cases are needed and it's important to automatically switch between them.

Of course, it's annoying if something is hovering around `1.0` to see constant flipping between `file/s` and `s/file` but not sure about a strategy for that case.
