### ISSUE TITLE
push: improve behavior for new gdrive folders?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3575]
```console
λ dvc version
DVC version: 0.91.2
Python version: 3.7.5
Platform: Windows-10-10.0.18362-SP0
Binary: True
Package: exe
...
λ dvc push -r mygdnewfolder
ERROR: failed to upload '.dvc\cache\61\37cde4893c59f76f005a8123d8e8e6' to 'gdrive://root/dvcstore/61/37cde4893c59f76f005a8123d8e8e6' - Google Drive path 'gdrive://root/dvcstore' not found.
ERROR: failed to push data to the cloud - 1 files failed to upload
...
```

This happens because I haven't created the dvcstore folder in my Google Drive root, so it's not a bug, but:

a) The message could be a little nicer, at least break line before "Google Drive path..." but probably the whole cache paths are not needed here (only in -v verbose output)
b) Have we thought about automatically creating missing folder structures on GDrive remotes? Maybe not by default but with a new flag for `dvc push`, similar to `mkdir -p`

**Comment by shcheklein** [comment]
It's a duplicate of one or two checkboxes in the #2865 . 

We don't want creating a missing remote root path on GDrive since GDrive allows for duplicate names and we want to avoid race conditions or something and end up creating multiple directories in different locations, etc, etc.

In general we should be doing the same for other remotes - aks users to be explicit and create directories.

**Comment by jorgeorpinel** [comment]
Got it.
