### ISSUE TITLE
remote add: should gdrive://root be an error?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#3586]
> Extracted from https://github.com/iterative/dvc.org/pull/1096#pullrequestreview-386034041

The URL `gdrive://root` means the root of your Google Drive (aka "My Drive") but maybe it's a bad practice to use that, which can be shared with a bunch of other files and Google Docs, so easy to mess with. In this case using this URL should throw an error and the documentation should specify it's not allowed and why.

On the other hand, maybe some users will create a GDrive acct just for this and using root as the URL would allow them not having to manually go into the Drive and create a folder to use as remote storage. In this case no action is needed, maybe just re-add the root URL example to the docs.

**Comment by shcheklein** [comment]
Yes, I even created a checkbox in the #2865 for this :)

**Quick considerations:**

1. (not related to this ticket even) `gdrive://root/something` does not make sense for the team - only personal use. Need to adjust docs a bit. Workaround - users share that dir and do `remote modify url` later if they decide to share the project, but commits they made before with the previous URL to the remote won't work for others.

2. In 99% of cases path equals `gdrive://root`is an error indeed. Still quite hesitant to act only because of this - I would for users to complain. It might be we don't account for some nice use case (automation?).

3. I think I created that checkbox to even before we realized that in case of shared folders path like `gdrive://<folder-ID>` (mind no path here, similar to `gdrive://root`) makes total sense. And we need to support no-path URLs in code anyways. So, that checkbox is less relevant now.

**Comment by jorgeorpinel** [comment]
OK, addressing for docs in https://github.com/iterative/dvc.org/pull/1096#pullrequestreview-386926510. Since no changes are needed in core, I'm closing here.

@shcheklein I'm assuming you'll update the checkbox you mentioned as needed.

**Comment by shcheklein** [comment]
@jorgeorpinel yes, I put a link to this ticket to read this when time comes to that checkbox. thanks!
