### ISSUE TITLE
Secsh channel 10 open FAILED: open failed: Connect failed

### ISSUE THREAD

**Issue by Sunny-Day200** [iterative/dvc#3654]
Linux
snap install --classic dvc 0.92.1

['remote "ssh"']
    url = ssh://hyperloop@ip/mnt/sdc1/dataset/data    
    user = hyperloop
    port = 22
    keyfile = /home/python/.ssh/id_rsa
    ask_password = true

-----------------------------------------------------
Sorry, I'm new to DVC and I showed up during a push;

  0% Querying cache in ssh://hyperloop@192.168.99.52/mnt/sdc1/dataset/data| |0.0Secsh channel 10 open FAILED: open failed: Connect failed
  0% /mnt/sdc1/dataset/data/e6/207d85aca1e16fa0c766232729176f.dir| |1.00/21.4k [Secsh channel 10 open FAILED: open failed: Connect failed
Secsh channel 10 open FAILED: open failed: Connect failed
Secsh channel 10 open FAILED: open failed: Connect failed

But remote warehouses also seem to store data. I don't understand why.

**Comment by skshetry** [comment]
Hi, @Sunny-Day200. Thank you for reporting this. The push works successfully, right? The problem could be with the server that's not allowing us to open more channels and has been reported before in #3482. 

Closing for now, feel free to jump in #3482, or if the `push`/`pull` fails, please reopen. The action point for us for this issue is to silence the paramiko logger. But, please try to check issues  with your ssh server.
