### ISSUE TITLE
Introduce check-ignore for dvc ignore command.

### ISSUE THREAD

**Issue by pared** [iterative/dvc#3736]
There should be functionality providing easy way to check whether some file is `dvc-ignored` or not. Related: #3538

**Comment by karajan1001** [comment]
@pared
Hi, I'd like to look into it this weekend. And now are asking for some advice.

According to [git](https://git-scm.com/docs/git-check-ignore).
It has `-q`, `-v`,  `--stdin`, `-z`, `-n`, `--no-index` arguments. 

Among them, I consider `-v`(show details, the last pattern matches) `--no-index` (without this ignore-check would ignore those files already added in cache) most required.

Then, `--stdin` is very helpful at debugging, `-q` is a default parameter. `-z` is used when we are about to output to files or use it in scripts. At last `-n` is an optional I think but is easy to implement.

So, at first, I'd like to implement `-v`, `-q`, `-n`, and `--no-index` first, and `--stdin` in the next step. 
Besides these, Maybe `-a, --all` which shows all of the patterns matches the files instead of only the last one are useful?

**Comment by pared** [comment]
@karajan1001 
Ill try to provide as much info as I am able:
1. `-q` - I think that if we are to use the logger to display the information, the only important thing to implement is proper return code on   command.  `quiet` behavior is handled by [default parser](https://github.com/iterative/dvc/blob/5ed832077df8de445c1bac20fadc93b8d9d14d31/dvc/cli.py#L139)

2. `--no-index` - I am not sure whether this one is vital. In my understanding, in git, it can be used to verify whether some element would be ignored if it was not already added to the index. So there is a kind of superiority of index over the workspace. In DVC however, if you put something into the `.dvcignore`, and run `dvc status`, DVC will pick it up and report your dir as changed, even if it is not. But from the point of view of DVC it did change because you "deleted" particular file. So I think in this point DVC differs from git in its operating principles and might not require `--no-index` option. Though if you have some other perspective, please share, I might be missing something here.

So, for now, if you want to implement a few features, I think `-v`, `-q`, `-n` will already be super-useful. Just a note though, please don't consider it as a must. It will be awesome even if you were able to do just `dvc check-ignore` returning `1/0`.

In next steps `--stdin` would be great and nicely matching other command-line helpful options, like `--show-vega` for `plots` command. `-a` also sounds awesome.

Please ping me if you want me to extend some parts.

**Comment by karajan1001** [comment]
@pared 
Thank you, 
1. For `-q`. I agreed, the only thing need to take care is the return number, non-zero return number may cause some report process.

![git ignore-check](https://user-images.githubusercontent.com/6745454/88446235-d5f1e600-ce5a-11ea-9d90-3f69bf88fe8e.jpg)

2. For `--no-index`, I had tried on my computer, seems that it is vital for Git but not for DVC. The reason lies in the differences in treating ignored files between Git and DVC. In Git `.gitignore` changed didn't influence files existing in the cache, Ignore check skips them. But for DVC, ignored check on files whether added to cache or not. 
> So without `--no-index` Git can't check files in the cache, while for DVC actually we are always in a `--no-index` mode.

**Comment by karajan1001** [comment]
@pared 
![verbose](https://user-images.githubusercontent.com/6745454/88452517-01dc8e00-ce92-11ea-90f0-0a37a576b986.jpg)

Seems that `--verbose` conflict with debug model, use `-d`, `--details` instead.

**Comment by pared** [comment]
@karajan1001 
Some disrepancies are unavoidable, feel free to invent your own names. Until we create docs for the command, we can assume its experimental feature which can be adjusted. We can also come to some agreements during review.
