### ISSUE TITLE
Single .dvc File

### ISSUE THREAD

**Issue by kamra8** [iterative/dvc#3919]
For current stable version 0.94 when we use **dvc add** and add multiple files,multiple .dvc files are being created for each file.Can we have a feature so that only one .dvc file is created for multiple target arguments or we can also add option in command to do this explicitly.

**Comment by efiop** [comment]
Hi @kamra8 !

Could you please elaborate on your scenario?

The reason it is one dvc-file per artifact is so that it acts as a placeholder for an actual file/directory, so you could even see where things are while browsing the github. Also, cramming multiple outputs into one file will make merges a lot harder for you, because you will have to keep track of md5s.

**Comment by kamra8** [comment]
Hi @efiop !
In my scenario I have 15 files to track and these files are in different folders(These folders also contains some files which i don't want to track).I have added all files individually and 15 .dvc files are created.So as the number of files to keep track of increases .dvc files will also increase.So it will be better to have an option in command to have one .dvc file.
We are already keeping track of all md5s in separate files.I think we can have a single file which will have all md5s.

**Comment by efiop** [comment]
@kamra8 Got it. You could hack it together by adding new entries to `outs:` list in a `*.dvc` file that you already have, but I'm not sure we should implement a special flag for it, as it is, well, a hack, that goes against current recommended practices :) But if you feel like you really need it and you'd like to contribute a PR for that, we would gladly accept it.

**Comment by efiop** [comment]
Closing as stale.
