### ISSUE TITLE
Pointer files are shown as changed

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3927]
### Steps to reproduce:
```console
$ git checkout 0.94.0
$ echo "foo" > foo
$ dvc add foo -q
$ git checkout master
$ dvc status
foo.dvc:
	changed checksum
```

Is this ^ intended? @efiop

**Comment by efiop** [comment]
@skshetry Yes, we broke it intentionally.

**Comment by skshetry** [comment]
We only changed file formats right? Should the `status` even  show changed checksum and repro?

I'm suggesting something in the line of:
```diff
diff --git a/dvc/stage/__init__.py b/dvc/stage/__init__.py
index 725cb1e0..47c579d3 100644
--- a/dvc/stage/__init__.py
+++ b/dvc/stage/__init__.py
@@ -248,6 +248,8 @@ class Stage(params.StageParams):
         return False
 
     def changed_stage(self):
+        if self.is_data_source and not self.is_import:
+            return False
         changed = self.md5 != self.compute_md5()
         if changed:
             logger.debug(self._changed_stage_entry())
```

which will avoid `repro` and not show any checksum changes on `status` for pointers.

Though, this might not change formats of file unless there's any modification.

**Comment by efiop** [comment]
@skshetry Yes, it could skip it too (not for the import though, at least for now), but the intended way is for `dvc add`ed files to not have any top md5s at all, and that's why it is showing them as `changed`. It is solved with a simple `commit` and shouldn't happen in the future. Right now it can also be considered as a `dvc-file` format change (e.g. someone edited dvc-run dvcfile by removing cmd and deps).

**Comment by skshetry** [comment]
[The genie is out of the bottle](https://github.com/iterative/dvc/releases/tag/1.0.0) with this ~~bug~~ feature. Closing.
