### ISSUE TITLE
brancher: potential collision with "workspace" tags/branches

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#3943]
https://github.com/iterative/dvc/pull/3914#discussion_r433051870 Kudos @Suor

**Comment by Suor** [comment]
There are two subissues caused by htis name clash:

**Input one.** When someone uses `repo.brancher(revs=[..., "workspace"])` it's unclear whether he or she wants workspace to be included or there is a tag/branch named "workspace", which needs to be included.

**Output one.** When brancher yields `"workspace"` does it show workspace or a tag/branch with that name? This further confuses things like `metrics/plots show/diff` output and corresponding `Repo.metrics.show()/Repo.params.show()`.

Also, we sometime refer to workspace as "" (empty string) for whatever reasons.

**Comment by efiop** [comment]
We could mark it with some char that is forbidden for tags. With `working tree` it was the space that was illegal, so we didn't have any issues. We could do something similar by including some rare illegal character somewhere.

**Comment by Suor** [comment]
If we don't care about presentation we can make some str subclass:
```python
class Workspace(str):
    pass
WORKSPACE = Workspace("workspace")
```
Will work both for in and out. Looks as hacky as special char to me.

On the other hand the most clean solution I can think of is use flag for input and empty string for output. CLI should show `workspace` or something instead of empty string and it should go first.
