### ISSUE TITLE
Error: google-api-python-client DistributionNotFound when dvc is installed on Linux (Fedora/CentOS)

### ISSUE THREAD

**Issue by snehalvartak** [iterative/dvc#3981]
I am trying to use dvc pull command to pull my data from gdrive folder to my training instance on AWS, but getting the following error.
ERROR: unexpected error - The 'google-api-python-client' distribution was not found and is required by the application.

I tried installing from the repository as well as the package (.rpm) following the instructions on https://dvc.org/doc/install/linux for Fedora/CentOS but in both cases I get the same error.

**Comment by efiop** [comment]
Hi @snehalvartak !

We've fixed this issue not long ago in https://github.com/iterative/dvc/issues/3913 . It should be fixed in 1.0.0a10. You could try installing our binaries from https://github.com/iterative/dvc/releases/tag/1.0.0a10 . Or you could simply install from pip/conda/brew, those packages are not affected by this issue.

**Comment by efiop** [comment]
I'll close this one as a duplicate of #3913 for now. Please let us know if that works for you. Thanks for the feedback! :pray:
