### ISSUE TITLE
refactor: consolidate tree classes

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#4050]
Follow up to #3882.

Currently we have tree classes that all inherit from `dvc.scm.tree.BaseTree` spread out all over the code base w/`DvcTree`, `RepoTree`, SCM/git related trees, `BaseRemoteTree`, and all of the associated cloud remote trees. It may make more sense to group these in something like `dvc.tree` and `dvc.tree.cloud`. This would also allow us to simplify what is currently under `dvc.remote`, since we really only need single files for `Remote` and `CloudCache` now. (Cloud cache code could also potentially just be moved into `dvc.cache` now as well.)

**Comment by efiop** [comment]
Ok, I think we are done for now. Core code is separated, but there might be some issues like https://github.com/iterative/dvc/pull/4244 which were there before this, but we weren't able to see them. We'll have to fix them as we go, especially since we are trying to use trees more and more and those bugs are getting more and more obvious.

I didn't move the tests around for now, because they are intermixed and it doesn't seem worth it to bother with in this sprint. But it is a technical debt, so we'll have to get to them at some point in the future. Luckily, they are easy to separate when writing new tests (similar how we are doing with unit -> pytest migration). Plus, `cache` and `remote` classes still have some cloud-specific implementations (e.g. local and ssh where we use some sftp channel magic) which will likely be slimmed down once we unify tree interfaces (see comment about it below). 

Next big thing here is to, of course, optimize dvcignore (something that is on our radar right now, has a separate ticket and PR), but , even more importantly, we will need to unify interfaces of our tree classes better. E.g. make them all raise appropriate OSErrors (or something else if we will be able to find something better) so we are able to handle them in a unified way. Same with return types, where it would be great to use type hints and use mypy to check them.
