### ISSUE TITLE
azure: use ~/.azure/config

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#4129]
Today we recommend using local config for Azure: https://dvc.org/doc/command-reference/remote/add#supported-storage-types
This approach is not the best since users need to remember and reconfigure URL in addition to credentials.

We need to support a regular flow for Azure (the same as S3 and GCS) when config contains URL/bucket and credentials are stored at `~/.aws/credentials` & `~/.gcp/*.json`.

Solution 1: use `~/.azure/config` as a recommended way of storing credentials (`connection_string` I guess): https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables

Solution 2: Support a combination of local and regular remote settings:
```
$ dvc remote add -d myremote azure://my-container-name/path  # NOT LOCAL
$ dvc remote modify --local myremote connection_string  "my-connection-string"  # LOCAL - but now it fails
ERROR: configuration error - config file error: remote 'myremote' doesn't exists.  # BTW, there is a grammar error, should be "doesn't exist"
```

1st one is more important and it aligns well with the other remote types.

**Comment by shcheklein** [comment]
@efiop do we have a ticket to update docs for this? is it needed?

**Comment by efiop** [comment]
@shcheklein I don't think we ever describe the creds priorities (e.g. with s3) and this is expected behaviour, so no, there is no ticket for azure specifically nor for everything. I don't think we've ever received confused questions about working remotes, so probably not worth the time for now to go that extra mile to describe it in our docs.
