### ISSUE TITLE
Brew install/upgrade dvc overwrites current version of python3

### ISSUE THREAD

**Issue by philipperemy** [iterative/dvc#4198]
I'm running on MacOS with python3.7.

When running `brew install dvc` or even `brew upgrade dvc`, my python was changed to python3.8 and it broke all my other virtual environments.

Not really a bug here but should be more careful about brew and forcing a python version.

```
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.8/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
```

```
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.8/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.8/site-packages
```

**Comment by philipperemy** [comment]
So please if you are suggesting for upgrade, do not force the update of python3! :)

**Comment by efiop** [comment]
@philipperemy IIRC homebrew guys updated it to 3.8 for us: https://github.com/Homebrew/homebrew-core/commit/bc452dce13767a10c673ef442fd8ff3c9d0dc8e7 because they are migrating to 3.8 by default. Looking through the formulas, all of them depend on 3.8, so this is a homebrew policy that we can't really do much about :slightly_frowning_face:  If you need very specific python version, I would suggest using something like pyenv. python brew package will be upgraded along with any package that depends on it, not only dvc.

**Comment by philipperemy** [comment]
Oh I see then nothing to do... Just to keep in mind!

**Comment by pmrowla** [comment]
For future reference, this is because homebrew changed their default python version from 3.7 to 3.8 last week (and is unrelated to the DVC brew package)
https://github.com/Homebrew/homebrew-core/pull/54912
