### ISSUE TITLE
Did you forget to fetch? is generally not the solution to my problem

### ISSUE THREAD

**Issue by braaannigan** [iterative/dvc#4316]
## Bug Report
I occasionally do ```dvc pull``` and get a failure with the message "Did you forget to fetch?". In my case the cause has always been that I've forgotten to push on another machine. The message could be expanded to cover this use case.
### Please provide information about your setup

**Output of `dvc version`:**

```console
1.2.1
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by pared** [comment]
@braaannigan but you do get the warnings that particular file was not found locally and remote, right?

AFAIK, we introduced a warning mechanism (instead of throwing) to make sure we download as much as we can. `pull` command consists of two separate operations: `fetch` and `checkout`. The error that you are mentioning happens on `checkout`. I guess what we could think of doing is gathering the failed downloads and reacting to them before entering checkout since we know that it has to fail.

**Comment by braaannigan** [comment]
Would that reaction include more suggestions of what might have gone wrong?

**Comment by pared** [comment]
@braaannigan 
I don't think it will contain more information that is already present in log. There should be WARNING entry that `data` has not been downloaded. But we should be able to stop the execution before entering `checkout` so that there is no misguiding message in the end.

**Comment by efiop** [comment]
Leaving open for now https://github.com/iterative/dvc/pull/4339#discussion_r467858929

**Comment by efiop** [comment]
Stale
