### ISSUE TITLE
status: flag to error-out if something is not up to date 

### ISSUE THREAD

**Issue by nik123** [iterative/dvc#4436]
Currently `dvc status -q` doesn't print anything and exits wit non-zero code if not all pipelines are up to date. There should probably be the flag "error-out if something is not up to date" with or without `-q` code.

Context:

1. https://github.com/iterative/dvc/issues/4383#issuecomment-673058969
1. https://discord.com/channels/485586884165107732/563406153334128681/743170972659613779

**Comment by efiop** [comment]
@nik123 How about `--exit-code` like in `git diff`?

**Comment by nik123** [comment]
@efiop  `--exit-code` seems like a good choice.

However, I'm not sure there is a need for a such option. At least for use case I had in my mind: I wanted a GH workflow script which checks if all dvc files has been pushed into remote. Here is an example of my intentions:

```bash
# '--filter' option - see issue #4557 
# not using '-q' since I want to know which exact files are not pushed
if ! dvc status -c --filter="missing"; then
    echo "Not all dvc files are pushed into remote!"
    exit 1
fi
```

Right now I'm able to solve my problem using `dvc status -c --show-json` and parsing json output. So there is no need for `--exit-code` for this exact use case.

On the other side it still might be useful. And it may be useful not only for `status` command but for other commands with `-q` flag. But in this case stronger arguments and/or other use cases are needed to introduce `--exit-code` option.

**Comment by efiop** [comment]
@nik123 `dvc status -c --filter="missing"` could be easily replaced with `dvc status -c | grep missing` :slightly_smiling_face: 

Glad to hear that --show-json works for you too. Closing this for now, since you don't need it anymore and we didn't receive any requests for it yet. We'll reopen if there is more interest or someone wants to implement it.

As always, thanks a lot for the feedback! :pray:
