### ISSUE TITLE
Target(s) of dvc repro as regular expression

### ISSUE THREAD

**Issue by Honzys** [iterative/dvc#4576]
Hi,

would it be possible to add feature, that would enable providing target(s) for `dvc repro` as regular expression ?

Let's say we have stages `prepare_db_1` and `prepare_db_2`. If I want to reproduce `prepare_db_*` stages I would use command:
```
dvc repro prepare_db_.*
```

Before DVC 1.0.0 it was possible to use wildcards to match the stage files without the need to type them all by hand.

What do you think about this feature?

**Comment by efiop** [comment]
@Honzys `dvc repro prepare_db_.*` this likely won't work, because your shell will try to evaluate the wildcard and will fail your whole command. So one would need to escape that or put into single-quotes so that expression is passed to the dvc. So it will be a bit confusing :slightly_frowning_face: 

I have a feeling that you are more concerned about the shell completion, rather than full blow regex support on dvc side, right? If so, that will be implemented in https://github.com/iterative/dvc/issues/3743 in the future.

**Comment by Honzys** [comment]
@efiop Yes, you are right. I was indeed more concerned about completion.

That feature would be nice :)! Thank you

**Comment by efiop** [comment]
Thanks for clarifying! :slightly_smiling_face:  Closing in favor of #3743
