### ISSUE TITLE
dvc checkout --ignore-missing;  build workspace even if some data is missing in local cache

### ISSUE THREAD

**Issue by DanielHiggs** [iterative/dvc#4746]
Currently 'dvc checkout' will fail with an error if the local cache does not contain all of the data specified by the repository and it will not construct any workspace directories.

For situations when having a partial subset of the repository's data is still useful, it would be nice to have an '--ignore-missing' option for the checkout command. When this option is invoked, 'dvc checkout' will create a workspace containing links to only those files which exist in the local cache, while only warning the user of the files that are unavailable instead of producing an error.

**Comment by pmrowla** [comment]
Worth nothing that we likely need this same behavior internally for checkpoint experiments, so it would not be too difficult to just add the `dvc checkout` command option once the checkpoints work is completed.

**Comment by dberenbaum** [comment]
@pmrowla Now that checkpoint experiments have been implemented for awhile, what is the level of effort to add this?

**Comment by christian-steinmeyer** [comment]
Just to clarify: When using the proposed `--ignore-missing` flag, warnings about missing files would still be printed, right?

If so, I'd propose to also make this option configurable as per config file, e.g.:
```
[core]
    ignore_missing = true
```

**Comment by frerksaxen** [comment]
I'd love to have this option since I usually add multiple stages in my dvc.yaml file, where outputs of one stage are dependencies of other stages. Calling `dvc pull` for the first time after defining these additional stages will fail because some dependencies have simply not yet been created at all. The `--ignore-missing` flag would really help in this situation, because it is not clear if `dvc pull` has finished pulling all available dependencies or if it just stopped at the first dependency it couldnt find.

**Comment by hemker** [comment]
I would also like to see this feature, because it simplifies the reproducibility of a partially executed pipeline on a remote server, for instance with Gitlab. Otherwise there would be the need to heavily customize the `.gitlab-ci.yaml` files for specific target pulling and force-reproducing.

**Comment by dberenbaum** [comment]
> @pmrowla Now that checkpoint experiments have been implemented for awhile, what is the level of effort to add this?

@pmrowla Following up on this. How much effort is it to add `--ignore-missing`?
