### ISSUE TITLE
run: Support comma separated list values of command options

### ISSUE THREAD

**Issue by PuneethaPai** [iterative/dvc#4806]
Currently only --params options support comma separated list of values.

Can we  add the same for other options like:

- [ ] --deps
- [ ] --outs & --outs-no-cache
- [ ] --outs-persist
- [ ] --metrics & --metrics-no-cache
- [ ] --plots & --plots-no-cache

**Comment by pared** [comment]
So, effectively, we would forbid coma in output name? We need to remember that currently, it is allowed.

**Comment by efiop** [comment]
Another option here is to use spaces, but that doesn't work because we are using REMINDER for the command itself, IIRC. Spaces seem to be a more natural thing to use compared to commas. Commas with params for default params.yaml file could also be then replaced with spaces, but for custom params file we will likely still need to use commas. There has been a discussion about using explicit `--cmd`, but as a downside it makes `dvc run` a bit more crowded.

Another thing that we've concluded over the years is that `dvc run` is really overloaded and there is no way to make it flexible enough to support every option that is supported by dvc.yaml. So we will likely be pushing people to write dvc.yaml by hand, but keep `dvc run`(maybe with another name) as a handy shortcut for simple commands.

**Comment by PuneethaPai** [comment]
Agreed, in long run we encourage users to edit `dvc.yaml` and use this `dvc run` as handy shortcut, to create `dvc.yaml` in first place, etc.

As we won't be deprecating `dvc run` anytime soon, implementing this is a value add IMO. To bring homogeneity w.r.t other `dvc run` options, and accept list values: comma separation makes sense.

If we want to change everything to space separation, I feel it is a larger discussion.
