### ISSUE TITLE
Documentation of DVC past versions 

### ISSUE THREAD

**Issue by beszedes** [iterative/dvc#4891]
It would be really helpful to have access to past versions of DVC documentation accessible.
OpenCv has something like this:  https://docs.opencv.org/

**Comment by skshetry** [comment]
Hi, @beszedes. Thanks for creating the issue. We are aware of this issue, but we haven't been able to prioritize this. Maybe, with pending 2.0 release around the corner, it'd be a good thing. Anyway, this is an issue about docs which we track in a different repo, and already have an open issue: https://github.com/iterative/dvc.org/issues/593.

It'd be great if you could share your thoughts there. I'm closing this issue here.
