### ISSUE TITLE
scm: Forward git flags such as -c

### ISSUE THREAD

**Issue by brainslush** [iterative/dvc#4980]
**Context:**

Azure DevOps Pipelines pull the git project of the branch from which the pipeline was called. If you want to to `git clone` either another project, another branch or use `dvc pull` to get some file you have to set the credentials in the `html.extraheaders` value with the `-c` flag.

This issue can be solved by calling git separately and then DVC or by calling `git config --global key value` in case of the `-c` flag. This requires you to now what DVC does under the hood or is actually trying to achieve there.

**Request:**

DVC should forward -c or more git flags to the internal git call.

**Example:**

`dvc get -c key value https://path.to/my/repo and/the/project/path`
`dvc get -git-c key value https://path.to/my/repo and/the/project/path`

**Comment by pmrowla** [comment]
Should note that the only reason the `git config --global` workaround works is because git-python calls command-line git for clone. If/when we move cloning via dulwich or pygit2 that workaround would no longer work at all. I'm not sure that dulwich supports these kinds of extra flags at all, pygit2 does via libgit's [git_fetch_options](https://libgit2.org/libgit2/#HEAD/type/git_fetch_options)

**Comment by brainslush** [comment]
As far as I know dulwich doesn't. Is it planed to opt in the future for one of these two or just one?

**Comment by pmrowla** [comment]
DVC will likely depend on both dulwich and pygit2 in the future, as certain features DVC needs are only available in dulwich, and certain features are only available in pygit2. Potentially, the user would be able to configure DVC to only use  one or the other if the user has a preference.

(But if/when we have internal DVC support for extra git fetch flags needed for this particular issue, we would require pygit2)

**Comment by efiop** [comment]
We don't use cli git at all these days.
