### ISSUE TITLE
diff: detect renames

### ISSUE THREAD

**Issue by cgebbe** [iterative/dvc#5150]
File renaming currently shows up in DVC DIFF <another_git_branch> as:

Added: (new filename after renaming)
Deleted: (old filename)

Would it be possible to group this information into a new category "Renamed" so that the overview is a bit clearer?

P.s.: If somebody could point me into the right direction, would like to create a pull request myself.

**Comment by efiop** [comment]
More context: https://discuss.dvc.org/t/merging-of-files-in-dvc-tracked-directories/599/5

**Comment by pmrowla** [comment]
Keeping this issue open for now since there are a few outstanding tasks that will need to be addressed eventually

* [ ] Make renaming detection in multiple matching file case consistent with git's
* [ ] Support similarity/rename detection once we have support for rolling hash based file chunking
* [ ] Consider options similar to git's `--no-renames`

**Comment by efiop** [comment]
Closing since the rest of tasks don't seem to be in demand.
