### ISSUE TITLE
import: resolve import-url from external repo

### ISSUE THREAD

**Issue by patzy** [iterative/dvc#5235]
I think it would make sense to have a unified behavior for anything external (git, http, ...). Anything external should be considered dangerous regarding reproducibility (an external git repo could be deleted and is not that different from a simple file url). Of course the user should be warned about this but he should be allowed to continue once the risks have been explained.

One use case I see for that is using dvc as a tool to easily get started with a project, i.e. maybe for teaching purpose using public data. Another one would be maintaining a registry with public and private data using only remote storage for private data while relying on the internet for public stuff.

It would make things easier to understand if all external dependencies could be imported with the same command and supported `dvc pull` instead of have two commands (`import` and `import-url`).

**Comment by pared** [comment]
Original discussion:
https://discord.com/channels/485586884165107732/563406153334128681/796761779162185758

To provide some context:
The original use case was that @patzy was trying to `dvc import` asset that has been `import-url` - ed into original repo, while at the same time not having to store it in the same remote. 

So the initial use case looked like this:
`{url} --import-url--> repo1 --import--> repo2`

So what op wanted to achieve is to resolve:
`--import-url--> repo1 --import-->` 
into
`{url} --import-url--> repo2`

@petzy
I am editing the title because `external dependencies` is reserved in our doc for `dvc run` arguments provided with `--external` which is not equivalent to assets obtained with `import`/`import-url`.
