### ISSUE TITLE
Sort files by size before push/pull

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#528]

**Comment by efiop** [comment]
Related to #522

**Comment by efiop** [comment]
Sorry, closed by accident.

**Comment by efiop** [comment]
No longer relevant with new design. Closing.

**Comment by casperdcl** [comment]
reopening due to https://github.com/iterative/dvc/pull/3594#issuecomment-610310130 and https://github.com/iterative/dvc/pull/3594#issuecomment-610432359. Basically:

- slight speed improvement
- reducing whitespace between nested bars
- to implement this, sizes aren't currently available for `pull` but they'll be required anyway for other thigs (e.g. #3568)

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/3682

**Comment by shcheklein** [comment]
> Closing in favor of #3682 , as that will be a better solution overall

💅 #3682 is not about performance though. Certain scenarios can benefit a lot from sorting by size on download/upload.

**Comment by efiop** [comment]
@shcheklein Single progress bar based on total size is what we are going to get for push/pull, especially when we implement the chunking.

**Comment by shcheklein** [comment]
@efiop yep, not sure I got the idea how is it related to the performance though? I was not referring to UI/UX (single vs multiple bars)

**Comment by efiop** [comment]
@shcheklein Ah, I misunderstood. The single pbar is also related to chunking from https://github.com/iterative/dvc/issues/829 , so without big files there is nothing to prioritize.
