### ISSUE TITLE
manually deleted stages not removed from lock file

### ISSUE THREAD

**Issue by patzy** [iterative/dvc#5293]
# Bug Report

## Description

Stages removed from a pipeline by editing `dvc.yaml` are not removed from `dvc.lock` after `dvc repro`.

### Reproduce

1. create a pipeline with two stages (stage_a, stage_b)
2. `dvc repro`
3. `dvc.lock` refers to stage_a and stage_b
4. edit `dvc.yaml` and remove one stage (i.e. stage_b)
5. `dvc repro`
6. stage_b is still mentionned in `dvc.lock`

### Expected

Manually deleted stages should have their corresponding section removed from `dvc.lock`

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.11.10 (pip)
---------------------------------
Platform: Python 3.9.1 on Linux-5.10.4-arch2-1-x86_64-with-glibc2.32
Supports: http, https, s3, ssh
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git
```

Discord context https://discord.com/channels/485586884165107732/563406153334128681/801147361837187102

**Comment by skshetry** [comment]
Hi, @patzy. I'd like to ask a few questions to better understand what we need to do to solve this:

1)  How does it affect you or other users? Is having a stale lock entry a bad thing (in that it does not affect any DVC's operations)?
2) Is this behaviour of not cleaning up lock entry useful? Maybe when experimenting with things between branches locally? 
3) Should this be supported in the `repro`? Or, should there be a separate utility to sync them from time to time (eg: `dvc sync`, `dvc commit`, etc.) ? This might depend on the answer of 1) and 2) I guess.

We did have a discussion during 1.0 about cleaning up lock-entry, but we decided against it because stage's lock entry only matters if the metadata and the name match with the one in the `dvc.yaml`, and might be useful when working locally and moving between different commits/stashes. But these days we do have `run-cache`, so maybe that's not that useful these days.

**Comment by patzy** [comment]
@skshetry not sure it has any real impact I just noticed it and created an issue as @efiop asked on discord.
I guess this could be a problem when switching between experiments as you explained, but I currently have an out-of-sync `dvc.lock` file and it doesn't seems to be a problem.
I'll see if I encounter any problems when experimenting but this was mainly my OCD talking here, also I though that dvc.lock was use when doing a checkout.

**Comment by skshetry** [comment]
> I guess this could be a problem when switching between experiments as you explained, but I currently have an out-of-sync dvc.lock file and it doesn't seem to be a problem.

I meant quite the opposite of it, that constantly removing these entries and adding them (at the bottom)  when moving in between those commits/stashes/experiments might increase the chances of merge conflicts. 
I don't know if these conflicts are that big of an issue though.

**Comment by patzy** [comment]
Sorry I misunderstood here. I see how this could be a source of conflict when switching between experiments. 
If all operations check for entries present in `dvc.yaml` too I don't think having stale entries in `dvc.lock` is really a problem.
Again I haven't used it enough to think of a proper use case that would require having the two files in sync.

**Comment by jorgeorpinel** [comment]
Hi. Foreach stages make it more likely/possible for users to generate a large number of stages with names that may keep changing (e.g. if the foreach is based on a params file which is constantly updated). This may cause dvc.lock to grow too much. May be a "missue" of the `foreach:` field ([example](https://discuss.dvc.org/t/versioning-predictions/656)), but still something to keep in mind.

**Comment by tbroadley** [comment]
I would like to point out that, the smaller `dvc.lock`, the faster `dvc repro` and other DVC commands can run. For example, `dvc repro` is reading `dvc.lock` into memory before running each stage, and writing it to disk after running each stage. In a pipeline with a lot of stages, this time can add up to multiple minutes.

It is possible to manually delete and recreate `dvc.lock` every once in a while, to clean out those unused stages, but it would be nice if it happened automatically.
