### ISSUE TITLE
pull: Failed to pull data from the cloud. <filename> is git-ignored.

### ISSUE THREAD

**Issue by benjamintanweihao** [iterative/dvc#5396]
# Bug Report

## Description

I tested this between DVC versions 1.11 and 2.0.  My setup is the following:

I have a folder called `env/resources` where I store Tensorflow binaries which are tracked by DVC. `env/resources` is also `git`-ignored.

When I do `dvc pull` in earlier versions of DVC (i.e 1.x) everything works as expected. However, when I do the same in version 2, I get `pull: Failed to pull data from the cloud. <filename> is git-ignored.`

### Reproduce

Example:

1. dvc init
2. Copy dataset.zip to the directory
3. dvc add dataset.zip
4. dvc push
4. Add the directory to `.gitignore`.
5. git clone the repository somwhere else.
6. dvc pull

### Expected

`dvc` should have let me `pull` in the file even though the directory is `git`-ignored.

### Environment information

**Output of `dvc version`:**

```console
DVC version: 2.0.0a0+bb4604 (snap)
---------------------------------
Platform: Python 3.6.9 on Linux-5.4.0-62-generic-x86_64-with-Ubuntu-18.04-bionic
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```

**Comment by skshetry** [comment]
@benjamintanweihao, could you please share the reason why you add the directory to `.gitignore`?

DVC already adds the tracked directory to the `.gitignore`s.

**Comment by benjamintanweihao** [comment]
That was done before we used dvc. Even if dvc were to add an entry to the
gitignore file, it should have the same effect.

**Comment by skshetry** [comment]
Hi @benjamintanweihao, is it possible to exclude those `.gitignore`s?

**Comment by macio232** [comment]
Up

**Comment by skshetry** [comment]
@macio232, could you please provide more details? How is it affecting you? And, is that possible to unignore them? Thanks. 🙂

**Comment by macio232** [comment]
Actually, all the details are in the first post :) Files/directories added to `.gitignore` (for whatever reason) and tracked by DVC can not be pulled, which makes not much sense for me and is different from the previous behavior.

I was testing on the pre-release version mentioned in the first post here, and I don't know if the bug (or feature) is present in the latest version (which is 2.0.5 while typing). I can not verify this because I no longer have access to the project.

**Comment by efiop** [comment]
@macio232 That behaviour was introduced in 2.0 intentionally. You need to exclude corresponding *.dvc files from .gitignore.

**Comment by efiop** [comment]
Just to clarify: we've started ignoring such dvcfiles in 2.0 to improve the performance https://github.com/iterative/dvc/pull/5265 @macio232 Would it be possible to unignore those dvcfiles in your scenario?

**Comment by benjamintanweihao** [comment]
We have the following scenario:

We have a bunch of DVC-tracked files in a folder called "resources", where
we want to make sure that developers do not accidentally git commit and
push. Therefore, the "resources" folder is git-ignored. Of course, this
means that when we commit the *.dvc files we would have to do a git add -f
but this is a small price to pay instead of having to do a
git-filter-branch when someone accidentally commits a 100MB file into the
master branch.

**Comment by macio232** [comment]
@efiop exactly as @benjamintanweihao wrote - the usual strategy is to put the whole `resources/data` directory to `.gitignore` because of data confidentiality reasons. Sometimes you also have local data resources which you do not want to track either by git and DVC.

Moreover, I have the `data` directory added to `.gitignore` in all of my projects. I want to upgrade to 2.0, but this requires taking care of each individual file that should be gitignored.

**Comment by efiop** [comment]
@macio232 @benjamintanweihao Would it be possible to add an exclusion rule only for *.dvc and dvc.yaml? 
```

**Comment by macio232** [comment]
> @macio232 @benjamintanweihao Would it be possible to add an exclusion rule only for *.dvc and dvc.yaml?

Yes! I think this is a solution, and I feel stupid I didn't think of it myself :) Thank you @efiop !
