### ISSUE TITLE
get/import(-url): broken progress bar

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5538]
The progress bar does not have a total size, so tdqm is not able to update the progress bar position, and is useless in the present condition.

[![asciicast](https://asciinema.org/a/iw6EXpAhln98nUN07aF0wsUnP.svg)](https://asciinema.org/a/iw6EXpAhln98nUN07aF0wsUnP)

Affected commands: `get`/`import`/`import-url`/`get-url`/`fetch` and `pull`.

**Comment by isidentical** [comment]
I guess we could either use `fs.info()` and then obtain size from it or fallback to the underlying fs's download method (but `DvcFileSystem` only implements `.open()` and not `._download` so it might be tricky). Though the problem with info() is that, it would mean a separate API call in some providers (like s3) and will be a no-op on others (like gs/azure, since they use fsspec which caches these stuff while doing the listings etc). I personally prefer doing an info() call and bear the cost for now (since we will be gradually moving towards to fsspec).  CC: @efiop

**Comment by shcheklein** [comment]
> separate API call in some providers

my 2cs - it can be very expensive in some providers (like GDrive) - we would need to batch API calls (which means also a separate approach), or just skip the progress bar completely (which is not nice from the UX perspective, but will be better probably than doing API requests to my mind).

**Comment by skshetry** [comment]
Closing as stale.
