### ISSUE TITLE
ui: what should `--quiet` do for tabular outputs?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5576]
What does the `--quiet` mean for our DVC commands? 

It can have two different meanings:
1. Don't show up verbose error messages, but show messages that do matter (important warnings + what the user has asked for).
2. Display nothing at all.

I have seen a few tools using `--silent` instead for 2). But, I guess the most important thing is being consistent here.

The following are the ones that do print on `--quiet`:
1. `stage list`
2. `exp show`
3. `completion`
4. `remote default`

Other commands such as `metrics/params/plots` don't show anything at all (what's the use here of `--quiet`?).

P.S. What should `dvc repro` and `dvc exp run` do?

**Comment by dberenbaum** [comment]
Good points, @skshetry.

As you pointed out, none of the silent examples implemented now (`metrics/params/plots`) make much sense. Interested to hear if there's a use case for being silent for those since their purpose is to show output.

Otherwise, it seems like we might consistently apply the first meaning to all of the commands. As you again noted, we can always add `--silent` if necessary.
