### ISSUE TITLE
Drop --live and corresponding dvc.yaml section?

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#5606]
See https://github.com/iterative/dvclive/issues/60 for context. Right now, dvclive integration requires a `live` section in `dvc.yaml`, and `dvclive.init()` is optional in the Python script for the stage. This might be problematic for a few reasons:
1. `dvclive.init()` directory may conflict with `--live` directory.
2. Without `dvclive.init()`, the script will only run through DVC, not if executed as `python train.py` directly.
3. `--live` introduces an option into DVC that is language-specific since dvclive is a Python library.

@pared has suggested that it might make sense to reverse the current implementation and instead:
* Require `dvclive.init()` even in DVC
* Drop `--live` and the corresponding `dvc.yaml` section
* Have DVC automatically integrate dvclive functionality where `dvclive.init()` is called in a stage

@pared Please correct any misinformation or add your thoughts.

**Comment by pared** [comment]
@dberenbaum 

> Drop --live and the corresponding dvc.yaml section

I wouldn't say I am for dropping `live` output, as it consists of `plots` dir and optionally `metrics` file, which by itself is problematic to handle, but currently works. Also, without `live` output, we would have to reconsider generation of training report - `live` helps to store information whether `dvc` should generate it or not. 

> Require dvclive.init() even in DVC

Yes, I think this should be required in order to not break users script just for sake of convenience. What might make sense is actually override `init` call with `--live` provided path. (credit for the [idea](https://github.com/iterative/dvclive/issues/60#issuecomment-794915809) to @jorgeorpinel). That way user is able to reproduce with `dvc repro`, `dvc` is happy with output, and if user wants to call `python train`, sure, why not. 

> Have DVC automatically integrate dvclive functionality where dvclive.init() is called in a stage

Yes, I think about that, though that would require some research - first problem I see is our verification of outs existence, which happens before we execute the script. If we were to implement it, we would be editing stage during execution. 

So I guess the main point here is precedence of `init` over `--live`, I would vote for `--live` to be more important, and requiring to call `init` always.

**Comment by pared** [comment]
One more thought on dropping `live` - maybe we could do that. 

One of the reasons of creating `live` output was to provide support for special HTML (avialable when `dvc live show`) is called that takes into consideration the optional metrics file and visualizes it too. If we, instead of treating `live` as separate entity, would treat it as `plots` directory, and add 2 flags to plots config (`is_live` and `live_generate_report`), we would get rid of `live` output and retain current behaviour. We would get rid of currently existing problem: that metrics file needs to be stored in git.

That would require one change on `dvclive` side. Instead of creating optional metrics file alongside plots directory, we would need to store it inside the directory (for example as `.latest.json`).

**Comment by jorgeorpinel** [comment]
Always requiring `dvclive.init()` seems fine and improves code consistency.

> > Have DVC automatically integrate dvclive functionality where dvclive.init() is called in a stage
>
> Yes, I think about that, though that would require some research - first problem I see is our verification of outs existence, which happens before we execute the script. If we were to implement it, we would be editing stage during execution.

But this part seems pretty tricky indeed. But if there's a good non-hacky solution, then 👍 — could be used to detect checkpoints without requiring the `checkpoint: true` field in stage outputs (unrelated, sorry) so maybe @pmrowla has thought about how to implement something like this?

**Comment by pmrowla** [comment]
I don't really see any way straightforward way of automatically determining that an output should be a `checkpoint`. The user has to tell DVC to that these outputs should be handled in a special way - for checkpoints, they get unique behavior (like with `exp run --reset`) that should only apply to those specific outputs. It's the same as where we can't automatically identify a `persist` output, the user has to explicitly tell DVC that the output needs to be persistent.

---

WRT live, my current understanding is that currently for `live` DVC outputs it means that:

- `<output_name>` itself is a directory containing dvclive `.tsv` logs, and is treated like any other DVC-tracked `persist` output directory
- During stage execution, DVC will take some steps when signaled by dvclive:
    1. If the `live` output has `summary = true`, we will look for `<output_name>.json`, which is the summary file for this particular iteration, and track it with git (I think this is mainly meant to be used in conjunction with checkpoints?)
    2. If the `live` output has `html = true`, we will generate the summary plots `<output_name>.html`, which is not git or DVC tracked

My thoughts (based on that understanding) on how to get rid of the `live` outputs from `dvc.yaml`:

What about adjusting the signaling method so that the live signal file also contains the paths to the dvclive generated metrics? So if dvclive is init'ed with `dvclive.init("path/to/training_metrics")`, dvclive would generate signal files containing something like
```yaml
summary: path/to/training_metrics.json
html: path/to/training_metrics.html
```

DVC would then just always monitor for the live signaling when running any stage, as opposed to only monitoring specific stages containing `live` outs. When signaled, if `summary` is present dvc would track the specified file with git. If `html` is present, dvc would generate the specified plots. So essentially this is just moving the `live` output section out of `dvc.yaml` and into the dvclive<->dvc signal file.

The main problem here would be that `path/to/training_metrics` itself is no longer automatically DVC-tracked. In theory, we could also modify the stage here when needed and automatically track `path/to/training_metrics` as a `persist` out (assuming the directory is not already tracked). We would also modify `dvc.yaml` at this time. However, I'm not sure that modifying pipeline stages during execution like this is something we would actually want to consider?

---

Now that I'm thinking about it, I suppose that in theory this might also work for checkpoints, but not as well as it would for dvclive.

Since we have full control over dvc and dvclive (and dvclive is python only), we can can make the signal files take any format we want, everything regarding signaling is completely hidden from the user.

Whereas for checkpoints we need to support signaling from any arbitrary (non-python) user stages, and requiring a simple "create file, wait for file to be removed" step is much more straightforward than, "generate file containing some specifically formatted list of files that DVC should treat as `checkpoint`s". (And note that for checkpoints, we do need that specific list of files, since they need to be treated in a unique way upon `exp run --reset`.)
