### ISSUE TITLE
installation: conda install hangs

### ISSUE THREAD

**Issue by marius311** [iterative/dvc#5625]
I'm unable to install dvc via conda across several systems. I think I can reproduce the issue in a Docker container so either its something very simple I'm doing wrong or its something wrong with the conda package:

```
docker run -it continuumio/miniconda:4.7.12
```
then run 
```
conda create -y -n test python=3.8 \
&& conda activate test \
&& conda install -c conda-forge dvc
```

This gives:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
```
and it just hangs there for at least 30min.

**Comment by efiop** [comment]
Hi @marius311 !

Thanks for reporting the issue! I can indeed reproduce it with your script. Moving the issue to https://github.com/conda-forge/dvc-feedstock/issues/191 , looking into it...

**Comment by maresb** [comment]
Hey @marius311, small world!!! (We met in Paris. If we get really lucky here shortly, we might be following in your footsteps once again... :wink:)

I have a few suggestions to solve your issue:
* First thing, `continuumio/miniconda` is the unfortunately-named package for miniconda with Python 2. Probably you want to be using `continuumio/miniconda3` instead.
* Second thing, conda is unbelievably horrendously slow. That's why it takes 30 minutes. I highly recommend using the C++ rewrite [mamba](https://github.com/mamba-org/mamba) instead. On my machine, the following never takes more than 2 seconds to solve:
  ```bash
  docker run -it continuumio/miniconda3:4.7.12
  
  : \
  && conda create -y -n test python=3.8 \
  && conda activate test \
  && conda install -y -c conda-forge mamba \
  && mamba install -y -c conda-forge dvc \
  ;
  ```
* Finally, you can save several steps by using a better container like:
  ```bash
  docker run -it condaforge/mambaforge
  
  mamba install -y dvc
  ```

**Comment by marius311** [comment]
Hey Ben, indeed small world! Thanks for the tips, I didn't know about mamba but that's helpful to know in general.
