### ISSUE TITLE
support for large file count with import-url and mounted cache directory

### ISSUE THREAD

**Issue by Eisbrenner** [iterative/dvc#5775]
Hi,

I have a setup where my cache is on a mounted data drive and my code in a home directory with very limited available disk quota.

Thus I use the feature to set a cache location, resulting in a `.dvc/config` like below
```
[cache]
    dir = /path/to/data/mnt/dvc-cache
    shared = group
    type = symlink
```

This allows me to use `import-url` on a single file; it creates a symlink to the file in my repository and moves a copy of the data to my data drive.

If I use `import-url` on a directory, the contents are copied to my repository instead and, in my case, the home quota is exceeded right away.

Now, using `import-url /path/with/wildcard_files_*.suffix` is not supported.

So my last resort was to write a loop, `for file in list_of_all_files; dvc import-url file; end` which took almost a full week to complete and also makes `dvc dag`  feature meaningless (it takes a few minuts and shows an endless list of files not providing useful information; in fact most functionality which looks up information of the project became useless, e.g. `dvc status` also takes several minutes).

**Feature request**

I would like to have support for
```bash
dvc import-url /path/with/wildcard_files_*.suffix
```
which should create a single `wildcard_data_list.suffix.dvc` file to speed up functions like `dvc status` and clean up functions like `dvc dag`.

**Comment by Eisbrenner** [comment]
I did an additional test which I haven't done before; that is importing a directory that actually fits on my home partition, and it turns out that the data is first downloaded to the repository and then moved to the cache, which is why `import-url dir` failed for me so far.

This behavior would, if kept for the wild card import, create the same issues as I had before.

**Comment by pmrowla** [comment]
Hi @Eisbrenner, are the files you want to contained within a directory (is the wildcard pattern strictly necessary here)?

If all of the files you want to add are contained in a single directory, you can use the [direct to cache](https://dvc.org/doc/command-reference/add#example-transfer-to-the-cache) feature within `dvc add`.

If you do
```
$ dvc add --out some_directory /path/to/external/directory
```
The contents of `/path/to/external/directory/` would be copied directly into your cache directory first, and then linked into your workspace so that the contents would inside `./some_directory/` with an associated `some_directory.dvc` file (as opposed to the issue you have encountered with `import-url`, where contents are copied into your workspace first and then into cache).

If you do need the wildcard because you only want to add specific files into the new directory, this alternative would still not work for your use case though.

**Comment by pmrowla** [comment]
Issue has been resolved via discord, closing issue

**Comment by Eisbrenner** [comment]
The wild card would allow me to have some control over the imports, for example importing only specific years, since my files have the date in the file name.

But I mostly have the data locally and can do some clean up of the directory beforehand.

So, your answer helps me out enough for now, if the wild cards ever come to DVC I'll be happy nonetheless :)
