### ISSUE TITLE
Unable to outpus directly to google cloud storage like dvc v1.11.6

### ISSUE THREAD

**Issue by dpcabo** [iterative/dvc#5854]
# Bug Report

## Description
Whe I try to run this stage y got this error but the file exists.
This error happens only with dvc 2.X, if I downgrade dvc to the version 1.11.6 this stage runs properly.

### Reproduce

1. Create a remote bucket in google cloud "mybucket"
2. Create a local file "touch delete.me"
3. Run dvc stage: `dvc run -n mystage -d delete.me --external -o gs://mybucket/delete.me gsutil cp delete.me gs://mybucket/`

### Expected

The same behaviour than the goten with dvc 1.11.6

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

Platform: Python 3.9.1 on Linux-5.4.0-1037-gcp-x86_64-with-glibc2.31
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, gs
Remotes: gs, gs, gs
Workspace directory: ext4 on /dev/root
Repo: dvc, git
```

**Comment by efiop** [comment]
Hi @dpcabo

We've removed support for gs because it was fundamentally broken for multipart objects. External output scenario is highly experimental in general and we don't recommend using it unless you really need to. But we are aware that there is a demand for that, so it is on our todo list to research it deeper and maybe propose a better general solution (related https://github.com/iterative/dvc/issues/3920).

Just to be clear, we are not going to support gs external outputs the same way anymore, so unfortunately you might be stuck with older dvc for now, if you have to use that feature.

Btw, could you describe your scenario, so we could understand better your particular case and maybe suggest an alternative?
