### ISSUE TITLE
`exp`: expose implementation (custom Git refs)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5882]
> From https://github.com/iterative/dvc.org/pull/2243#discussion_r591092531

Specifically, `apply` and `branch` are wrappers of narrow/complex `git` operations. Originally we didn't want users to worry about how experiments are implemented. That makes sense but is it the practical approach? If users are already familiar with Git (at least some, at least somewhat), why not expose the fact that exps are commits/branches that can be targeted by (certain) regular Git commands? Examples:

- Navigate between experiments: `git checkout exp-1234` (detached `HEAD`)
- "Apply" one or more experiments: `git merge --squash (--no-commit) (--theirs) exp-1234` (see #5782)
- Branch off an exp: `git branch exp-1234`
- There's probably a `git` substitute for `exp remove` too

The main pros I see is that the Git alternatives give users more flexibility, and we don't need to maintain them
The con is that we may need to educate users on Git to some extent.

Cc @pmrowla @dberenbaum @shcheklein

**Comment by shcheklein** [comment]
(I think this can be moved to the discussions?)

**Comment by jorgeorpinel** [comment]
(Probably. I assume this will be a discussion, so I'm fine with that. But TBH discussions feel like archived issues sometimes.)

**Comment by pmrowla** [comment]
The main limitation with forcing users to use CLI Git for these kinds of operations is that they cannot use experiment names with CLI Git. Additionally, the 1:1 substitutes for certain exp commands like would be low-level plumbing commands which users are probably unfamiliar with.

As an example, `exp remove exp-123` would need to be replaced by
```
git update-ref -d refs/exps/ab/c12345.../exp-123
```
which is probably not something we want to tell users to use (for several reasons).


---

Also, `exp apply` cannot be replaced by pure Git CLI commands, as it does additional DVC specific operations. `exp apply` is needed when users want to modify an intermediate checkpoint and then do a branching `exp run` from that modified point.

**Comment by jorgeorpinel** [comment]
Hmmmm OK.

Here's my thought process: from our many iterations on Experiments docs I've realized it can get pretty tricky to explain experiments without the context of how they're implemented, which is why I think maybe it would be easier to expose it anyway. Whether we keep some of these utilities or not.

So maybe just consider removing `exp branch` (only one that can be easy subs with `git`, it seems) and explain exps differently in docs. Thoughts?

**Comment by pmrowla** [comment]
The issue with being unable to use exp names still applies with `git branch`, but yes, you can do `git branch <new-branch-name> <exp-SHA>` to get the same behavior

**Comment by jorgeorpinel** [comment]
On the issue of exp names one option would be to show/list command SHAs by default instead (if we eventually decide to expose the underlying Git implementation).

**Comment by iesahin** [comment]
I do think the opposite, there are already too much Git-related messages, e.g., I'd simply commit the changes (subject to an option) instead of telling the user "You can now `git add .gitignore dvc.lock etc.dvc`". For the experiments, in particular, emphasizing to play with the related Git objects will result in more headaches for them, I think.

**Comment by dberenbaum** [comment]
Interesting discussion!

> I do think the opposite, there are already too much Git-related messages, e.g., I'd simply commit the changes (subject to an option) instead of telling the user "You can now `git add .gitignore dvc.lock etc.dvc`".

This is a common suggestion since it feels like dvc requires an extra step that many users will always be doing by default. I think forcing users to `git add` gently forces them to understand what dvc is doing. If dvc committed all those files automatically, many users would have no idea that `.gitignore` gets modified or that `dvc.lock` or `.dvc` files even exist or how they got there.

@shcheklein has linked to this article before, which I find really useful in thinking about designing UI: https://hisham.hm/2020/12/18/user-power-not-power-users-htop-and-its-design-philosophy/. It's a bit long, but here's a quote that summarizes the point:

> I wanted to make a tool that has the power but doesn't hide it from users, and instead invites users into becoming more powerful. A tool that reaches out its hand and guides them along the way, helping users to educate themselves about what's happening on the internals of their system, and in this way have more control of it.

Whether this is correct or not, there is some rationale for why the current UI exists, and a similar rationale could apply to gently exposing the experiments implementation.

**Comment by jorgeorpinel** [comment]
> there are already too much Git-related messages

Idk if that's a problem. There's no way around the fact that DVC versioning and other features (experiments) need Git.

The problem with just asking users to "commit changes to Git" is that some people may not know what to do exactly. Failing to copy/paste `git commit .gitignore data.dvc` is much less likely.

> A tool that reaches out its hand and guides them along the way

Great principle. I think that as far as DVC builds up on Git, we may need to educate about that as needed.

p.s. OK, moving this to discussions...
