### ISSUE TITLE
stage add: quotes are missing in dvc.yaml

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc#6072]
# Bug Report

## Description

Quotes in `dvc stage add` aren't added to dvc.yaml as expected. The following `dvc repro` fails as python script expects to have an empty string provided.

### Reproduce

1. mkdir dvc-bug-empty-string-arg
2. cd dvc-bug-empty-string-arg
3. dvc init --no-scm
4. dvc stage add -n train python train.py --weights ""
5. dvc stage add -n train-second python train.py --weights '""'
6. cat dvc.yaml

output:
```
stages:
  train:
    cmd: 'python train.py --weights '
  train-second:
    cmd: python train.py --weights ""
```

### Expected

Expected to have quotes in the first stage, have two quotes in the second one.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.1.0 (brew)
---------------------------------
Platform: Python 3.9.5 on macOS-10.16-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc (no_scm)
```

**Additional Information (if any):**

Rechecked this in bash and zsh.

**Comment by skshetry** [comment]
@aguschin, this is expected. You have to escape those quotes explicitly.

**Comment by shcheklein** [comment]
@skshetry could you please provide a bit more context on why is it expected? thanks!

**Comment by skshetry** [comment]
We use a `argparse.REMAINDER`, so that means we have to parse things and quote things properly. And to be cross-compatible, we have to quote with double-quotes rather than single. So, the parsing of those commands get ugly here because of all the quoting that we need to do for earlier arguments, and to solve this empty string that we get from `""`, we might need to replace that to a double quoted string, which might clash with previous ones.

So, I prefer users to escape things when not working to escape from this ugly parsing stuff. But the fix for this would be to just replace the empty string with a quoted empty string.

**Comment by aguschin** [comment]
@skshetry, is this also indended? One may want to provide an empty parameter value: 

```
dvc exp run -S param=
ERROR: Must provide a value for parameter 'param'
# or
dvc exp run -S param=""
ERROR: Must provide a value for parameter 'param'
```

**Comment by skshetry** [comment]
For the record, replied in https://github.com/iterative/dvc/issues/6107#issuecomment-853718432.
