### ISSUE TITLE
tests: test_experiments::test_untracked is failing in CI

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#6374]
may be related to existing flaky pygit tests issue?

**Comment by pmrowla** [comment]
https://github.com/iterative/dvc/pull/6369/checks?check_run_id=3218847399

**Comment by skshetry** [comment]
The issue seems to be due to the latest version update of `python-benedict` (i.e. `0.24.1`). I looked into the internals of it, and the way we expect it to keep the references to the dictionary to update is wrong (though this is how `benedict` is supposed to work, but well it cannot keep pointers to the empty dictionary easily). I'll think of creating an issue later, but I think it's wise for us to just skip empty dictionaries, and only update non-empty ones.

See https://github.com/fabiocaccamo/python-benedict/issues/57#issuecomment-890490982 for more information.
