### ISSUE TITLE
`dvc exp show --all-tags`: doesn't show the names of annotated tags. 

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc#6383]
# Bug Report

## Description

`dvc exp show --all-tags` lists commit id's which correspond to tags, but the tag names are not shown when they are created with `git tag -a`. 

![image](https://user-images.githubusercontent.com/476310/128154051-e2c04254-04eb-47f4-9ec9-55946fa34290.png)

![image](https://user-images.githubusercontent.com/476310/128154186-2ad0c539-4a22-4723-a5cb-2f94417917c5.png)

![image](https://user-images.githubusercontent.com/476310/128154431-a9652a3a-f3cd-444f-8a8a-2c41078f8dd3.png)

### Reproduce

```
git clone https://github.com/iterative/get-started-experiments
dvc exp show --all-tags
```

### Expected

The `Experiments` column in the table should show tag names. 

### Environment information

Recent Ubuntu 20.04 WSL on

Edition	Windows 11 Pro
Version	21H2
Installed on	‎7/‎28/‎2021
OS build	22000.100
Experience	Windows Feature Experience Pack 421.18901.0.3

![image](https://user-images.githubusercontent.com/476310/128154737-434c82ca-ff2a-4177-9204-4f461a19cfd4.png)

**Comment by daavoo** [comment]
Fun history, I found a fix but the issue only happens when the tags are missing from `.git/refs/tags`, which I can only reproduce when cloning our example repos 🤷 

If tags are present in `.git/refs/tags`, which happens if I create tags locally or within tests the following code correctly gets the tag name and it is displayed on the table:

https://github.com/iterative/dvc/blob/3d604a84551e53cfa4473422005421cb42afbc0e/dvc/repo/experiments/show.py#L59-L62
