### ISSUE TITLE
add: support rollback/recovery from partial/failed dvc add

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#6387]
If the user does a long running dvc add directory that dies somewhere in the middle, there is no obvious (to the user) way to recover from the state where

1. DVC has not generated a .dvc file
2. half of the users files are still in the workspace (and have not been moved into cache)
3. half of the user’s files have been moved into cache, but have not been checked out/linked (and now appear to be lost)

Currently it's possible to recover from this state manually as long as we have the `.dir` file for the original complete directory, but not in a straightforward way

discord context https://discord.com/channels/485586884165107732/485596304961962003/872423982463340555

**Comment by skshetry** [comment]
Related: https://github.com/iterative/dvc/discussions/6252.
> DVC when committing the cache, moves the files to the cache and then after that is complete, relinks the file back to the workspace. This might result in data loss if it happens to fail in between.

**Comment by efiop** [comment]
As noted by @karajan1001 , we could try to use `hardlink` instead of `move()` so that we have files in both odb and workspace and even if checkout breaks - the workspace will be intact. And if `hardlink` is not supported it means that `rename()` will also not be supported and we'll need to copy stuff anyway, so there is no reason to use `move()`(copy + rename) and we could again keep the workspace intact.

**Comment by efiop** [comment]
@isidentical Btw, notice how ^^^ is related to our copy/upload/download/link unification discussion :slightly_smiling_face:

**Comment by karajan1001** [comment]
> As noted by @karajan1001 , we could try to use `hardlink` instead of `move()` so that we have files in both odb and workspace and even if checkout breaks - the workspace will be intact. And if `hardlink` is not supported it means that `rename()` will also not be supported and we'll need to copy stuff anyway, so there is no reason to use `move()`(copy + rename) and we could again keep the workspace intact.

But, the `hardlink` for default is a bit dangerous. Users might modify it manually without knowing it is a `hardlink`, and make a corrupt cache.

**Comment by efiop** [comment]
@karajan1001 Good point! I meant that we could use hardlink temporarily, just so that we have an easier time rolling back if something goes wrong.

**Comment by efiop** [comment]
Another user on discord running into this: https://discord.com/channels/485586884165107732/485596304961962003/900792694023028766

Also, note that we've stopped poisoning our local cache with .dir, but our staging db is still memory-only, so you are no longer able to recover the metadata 🙁

Unfortunately, we are not ready to make staging persistent right now, and we clearly shouldn't bring back poisoning, so instead we should take a closer look at the approach with trying to reflink/hardlink/copy(in this order and without symlink) instead of moving during `odb.add` in `dvc/fs/utils.py::transfer()`. These days our object transfering (talking about dvc/objects/transfer.py one) and checkingout are separate and in more-or-less good shape that they should be able to handle the aforementioned approach instead of `move`. This will allow us to be failure proof during `transfer`(before we've saved .dir into .dvc/cache) and during later failures (e.g. checkout) we will already have `.dir` that could be used for recovery (by us in the midterm, but as a hack in the shortterm).

**Comment by skshetry** [comment]
We don't save `.dir` files now?

**Comment by dberenbaum** [comment]
@efiop @skshetry Any thoughts on priority or how to solve this one?

**Comment by emremrah** [comment]
Suggestion: prioritize a progress bar to show the ETA. Lack of pb was the reason I was interupted the add process. Thanks again for the support for getting the data back.

**Comment by karajan1001** [comment]
A Related case but in `dvc remove` instead of `dvc add`.

**Comment by dberenbaum** [comment]
> @efiop @skshetry Any thoughts on priority or how to solve this one?

Ping @iterative/dvc. It sounds severe but I can't recall it coming up frequently. Thoughts on priority? Are we likely to solve it soon?

**Comment by efiop** [comment]
Seems like this was solved by https://github.com/iterative/dvc/pull/6860 for the most part. Let's close for now.
