### ISSUE TITLE
[CLI]: Table not rendered properly

### ISSUE THREAD

**Issue by ShauryaAg** [iterative/dvc#6411]
# Bug Report

`exp show`: table not rendered properly

## Description

When `dvc exp show` is run, the table is not rendered properly
![image](https://user-images.githubusercontent.com/31778302/128908435-959602cf-25ff-4a97-b6db-1642c3a8b7c9.png)

### Reproduce
1. Run some experiments in dvc
2. Run `dvc exp show`

### Expected
Table should be rendered properly like:
![image](https://user-images.githubusercontent.com/31778302/128908973-132cd0f2-e3d9-494d-b09b-f04d0732db56.png)

### Environment information
OS: WIndows 10 Home
Python version: 3.7.8

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
```
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.7.8 on Windows-10-10.0.19041-SP0
Supports:
        http (requests = 2.26.0),
        https (requests = 2.26.0)
Cache types: hardlink
Cache directory: NTFS on D:\
Caches: local
Remotes: None
Workspace directory: NTFS on D:\
Repo: dvc, git
```

**Additional Information (if any):**
The table is rendered properly from Linux environment (using WSL on windows), but not in Windows env.

**Comment by pmrowla** [comment]
@ShauryaAg what font are you using in cmd prompt or powershell?

**Comment by skshetry** [comment]
The problem is with the `less` pager, using `--no-pager` should work fine. I am trying to see if the newest version of less works.

**Comment by skshetry** [comment]
Okay, I was able to figure out what the issue is. 

We use [`tempfilepager`](https://github.com/iterative/dvc/blob/fb96b13f13948d775a3061c03868db3775f6c665/dvc/utils/pager.py#L48) which  saves the file to a temporary file as follows ([here](https://github.com/python/cpython/blob/bfc2d5a5c4550ab3a2fadeb9459b4bd948ff61a2/Lib/pydoc.py#L1622)(:
```python
with open(filename, 'w', errors='backslashreplace') as file:
    file.write(text)
```

As the rich's table is expected to be in utf-8, and the default encoding might be different on Windows, `backslashreplace` will replace those unicode box characters with backslash.

If we were directly printing it, `PYTHONIOENCODING="utf-8"` would have solved this, but the `tempfilepager` uses `open` where it does not have any effect.  A temporary fix is to set ` PYTHONUTF8=1`, this will have effect on all parts of the interpreter.

We need to figure out a way to page the output kept in `utf-8` format, most likely modifying `tempfilepager` itself to save in `utf-8` format. eg:
```python
with open(filename, 'w', encoding="utf-8") as file:
    file.write(text)
```

**Comment by ShauryaAg** [comment]
Upon some testing, I have figured out one solution to the problem. 
On line 94:
https://github.com/iterative/dvc/blob/fb96b13f13948d775a3061c03868db3775f6c665/dvc/ui/table.py#L93-L98

This can be changed to something like
```py 
import platform
WINDOWS = platform.system() == "Windows"

....
border_style = { 
     True: box.ASCII_DOUBLE_HEAD if WINDOWS else box.HEAVY_HEAD,
     False: None, 
     "simple": box.SIMPLE, 
     "minimal": box.MINIMAL, 
} 
....
```

This way we can print a table like the following for Windows while maintaining the current type for Linux
```
+---+---+---+
| A | B | C |
+===+===+===+
| a | b | c |
| 1 | 2 | 3 |
| 4 | 5 | 6 |
+---+---+---+
```

Please let me know if the solution seems ok to you. I'd like to make a PR for the same.

**Comment by ShauryaAg** [comment]
Upon further testing and implementing the above solution does fix the box issue.
However, it still doesn't properly render the experiment tree

![image](https://user-images.githubusercontent.com/31778302/129036447-e7287d76-c87d-4992-a7e1-dae712d01ce5.png)
