### ISSUE TITLE
dvc exp: get currently running experiment name with python API

### ISSUE THREAD

**Issue by macio232** [iterative/dvc#6668]
Hi, I run into a situation when I would like to get the currently running experiment name with python API. My use case is to relate DVC experiment names with experiment names in other tools that I use to report my results. This can be done manually/in post-processing in most cases but such a python command would make my life much easier.

Thx :)

**Comment by danudeep90** [comment]
@macio232 : Did you figure out a way to get the experiment name which is auto generated by dvc. I would like to log it into MLFlow tracking

**Comment by macio232** [comment]
@danudeep90, unfortunately not. I was hoping somebody would answer my call :) I would like to log it into wandb tracking. Once it is there, I will immediately start using it.

**Comment by pmrowla** [comment]
Part of the issue here is that currently the auto-generated experiment names are not generated at all until the experiment has finished (and the way the names are generated requires a completed experiment run).

Basically the easiest way to do this right now would be to autogenerate your own names beforehand and run experiments with `-n/--name`

**Comment by pmrowla** [comment]
related discussions regarding changing the way we generate exp names: https://github.com/iterative/dvc/issues/6071 https://github.com/iterative/dvc/issues/6680

**Comment by danudeep90** [comment]
@pmrowla : Can i configure the experiment name in the params.yaml so that when i execute **dvc exp run**, it is picked from params.yaml file

**Comment by pmrowla** [comment]
No, it has to be done via the `-n/--name` argument

**Comment by danudeep90** [comment]
@macio232 : You can build a python script to perform the dvc exp run via code and control the name. This could be fetched in the code for model training and logged into wandb or mlflow(url)

Created one file run_experiment.py as 
```python
## run_experiment.py
import subprocess
import os, sys

# Adding working directory to path to run the files as standalone
curr_wd = os.getcwd()
if curr_wd not in sys.path:
    sys.path.append(curr_wd)  # add working directory to PATH

from src.utils.helpers import create_exp_name


def main():

    # create experiment id
    exp_id = create_exp_name()

    # Execute "dvc exp run --queue --set-param train.alpha=<alpha> --set-param train.l1_ratio=<l1_ratio>".
    subprocess.run(["dvc", "exp", "run",
                    "--name", exp_id,
                    "--set-param", f"train.exp_id={exp_id}"])


if __name__ == "__main__":

    main()
```
our params.yaml can be as 
``` bash
data_ingestion:
  bucket_name: kaggle
  folder_path_in_bucket: wheat_detection
  local_save_dir: datasets
  local_folder_name: shrinkage
train:
  experiment-name: wine-regression1
  alpha: 0.75
  l1-ratio: 0.5
  exp_id: # placeholder for exp_id will be set while running the experiment

```

In your training script, you can load the params and log it as below
```python
 # Logging the DVC experiment name
  if params["exp_id"] is not None:
      print("Logging DVC experiment id to the run")
      mlflow.log_param("DVC Experiment name", params["exp_id"])
```

The only catch in such a approach is we should stop using **dvc exp run** on command line and instead use
 ```bash python run_experiment.py```

Using this we can run the experiment with a name and use the name in our training code to log into MLFlow or any tracking tools, so that we can checkout to the commit and reproduce the experiment

Let me know your thoughts

**Comment by KernelA** [comment]
A way to get exp name from DVC API is very useful. In my case, I log additional information to the [ClearML](https://clear.ml/) and run all experiments via `dvc exp run --queue -S <params> ...` with hydra composition. 

After all experiment are completed need a way to match experiment name from DVC and results in the ClearML.

**Comment by mvshmakov** [comment]
@daavoo should this one be closed as addressed?

**Comment by daavoo** [comment]
Starting next release (>`2.35.2`), the experiment name should be accessible via env var:

```
import os
print(os.environ.get("DVC_EXP_NAME", "")
```

Don't hesitate to re-open if there is some use case not covered

**Comment by daavoo** [comment]
> also, will it work for dvc exp run experiments or only for a particular flow?

I have tested with workspace, temp, and queue, and it worked as expected for me.

**Comment by daavoo** [comment]
> will it work if name is not set before running it (when DVC generates it at then end), 

I will not work right now

> or it's not an issue anymore?

It should stop being an issue soon.

**Comment by dberenbaum** [comment]
@daavoo Does `Live(save_dvc_exp=True)` also set this env var?

**Comment by daavoo** [comment]
> @daavoo Does `Live(save_dvc_exp=True)` also set this env var?

No. Do you think it should?
In the Python context, the name can be accessed from the `Live` instance.
