### ISSUE TITLE
dvc.yaml: handling .gitignore in dvc.yaml driven workflow

### ISSUE THREAD

**Issue by pared** [iterative/dvc#6952]
Sometimes we want to conduct our project by editing the `dvc.yaml` (eg #5371).
If we want to to support this kind of workflow, we should discuss how are we handling `.gitingore` file.

Lets take for example the following reproduction script:

```
#!/bin/bash

set -ex

pushd $TMPDIR
rm -rf test_wspace
mkdir test_wspace
pushd test_wspace

mkdir test_repo
pushd test_repo

git init
dvc init

git add -A
git commit -am "init"

echo data >> data
dvc add data
git add -A
git commit -am "data"

dvc run -d data -n train -o out "cp data out"

echo -e "stages:
  train:
    cmd: cp data out
    deps:
    - data
    outs:
    - out:
        cache: False" > dvc.yaml

dvc repro train
git check-ignore out && echo "out is ignored!"
```

We have create a workflow that simply copies `data` into out. The `echo` takes care of modifying the `dvc.yaml` so that the `out` has `cache: False`.
Since we stared our workflow with out added as  DVC-controlled `out`, DVC adds `/out` to `.gitignore`.

Should we have some kind of mechanism that would modify the `.gitignore` / warn the user that `out` is no longer tracked by DVC?

Kudos to @mnrozhkov for pointing that out.

**Comment by daavoo** [comment]
This won't really solve the issue but we could add a validator in `dvcyaml-schema` for outputs with `cache: False` checking that they are not gitignored:

https://github.com/iterative/dvcyaml-schema/blob/master/gen.py#L17

We should be really encouraging `dvcyaml-schema` for workflows involving manual editions of `dvc.yaml`

**Comment by dberenbaum** [comment]
This is tricky because sometimes users intentionally set cache to false and ignore in Git. For example, see `data/images/` in https://github.com/iterative/example-dvc-experiments.

**Comment by daavoo** [comment]
> This is tricky because sometimes users intentionally set cache to false and ignore in Git. For example, see `data/images/` in https://github.com/iterative/example-dvc-experiments.

Not sure if the following difference matters at all (agree it is tricky) but:

In that example repo, the user is manually adding the `cache: false` output to `.gitignore`: https://github.com/iterative/example-repos-dev/blob/master/example-dvc-experiments/generate.bash#L51

However, in the described workflow the `.gitignore` entry was added by DVC so the user might not be aware of that, and so the issue was reported.

Maybe in the workflow described in this issue (transitioning an output to `cache: False`), we should just recommend using `dvc remove` like in https://dvc.org/doc/user-guide/how-to/stop-tracking-data ?
