### ISSUE TITLE
remote: support `digest` auth for WebDAV

### ISSUE THREAD

**Issue by FatemeKhodayari** [iterative/dvc#7065]
Hi. I'm a beginner to DVC. Yesterday, I set up DVC with a `webdav` backend as said in the official documentation. When I wanted to push to the remote, the URL had `00` added to it. It must have been `https://mydomain/webdav/models` but instead DVC was trying to push to `https://mydomain/webdav/models/00` which is a nonexisting URL.

Any idea why this is happening and how I should solve it?

**Comment by jorgeorpinel** [comment]
From the conversation in https://discord.com/channels/485586884165107732/485596304961962003/914048099742253068 it seems it's a compatibility issue. Summary:

>  00 is probably from trying to estimate your remote size. There is nothing wrong with that. It looks like you might have some configuration problem.
What server are you using? owncloud?
- @efiop 

> It's a VPS with apache.
Based on apache error log, the problem seems to be with the authentication scheme. The authentication scheme of the webdav server is set to digest while it seems dvc is using basic.
- @FatemeKhodayari 

> We don't support digest auth in dvc for webdav. We'll be happy to add that if someone contributes
- @skshetry

**Comment by jorgeorpinel** [comment]
Another recap from the user in https://github.com/iterative/dvc.org/issues/3044#issuecomment-982666435. This issue is stuck "being transferred" by GH though, may want to close and re-open.

**Comment by skshetry** [comment]
Closing as duplicate, see #7107.
