### ISSUE TITLE
exp run: rename `--run-all` to `--all`

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#7127]
Command:

`dvc exp run --run-all`

looks weird, what was the reason to not name it

`dvc exp run --all`

or even:

`dvc exp run --queue` to be consistent with `remove` and `gc`?

**Comment by pmrowla** [comment]
Essentially both `exp run --run-all` and `exp run --queue` haven't been touched since the entire exp feature was experimental (before any release), and they both predate the current iterations of `exp remove` and `exp gc`.

I think the `--queue/--run-all` flags should eventually just go away entirely in favor of a proper solution for https://github.com/iterative/dvc/issues/5615

**Comment by dberenbaum** [comment]
`dvc exp run --all` is already a valid command apparently, although I don't know what this flag is intended to do and am having trouble figuring out where it comes from.
