### ISSUE TITLE
`dvc exp run` prints exception message twice

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#7276]
Here's the repro:
```console
cd "$(mktemp -d)"
git init && dvc init
echo "foo: 1" > params.yaml
git add -A
git commit -m "initial"
dvc exp init python train.py
dvc exp run
```

This outputs:
```console
ERROR: failed to reproduce 'dvc.yaml': [Errno 2] No such file or directory: '/private/var/folders/xh/trg29z296h70n109kwfk6g800000gn/T/tmp.dUgMYVQs/data'
ERROR: failed to reproduce 'dvc.yaml': [Errno 2] No such file or directory: '/private/var/folders/xh/trg29z296h70n109kwfk6g800000gn/T/tmp.dUgMYVQs/data
```

**Comment by skshetry** [comment]
This is happening because of:

https://github.com/iterative/dvc/blob/822b501069f4553b76534aadf0b2266fd5c26c24/dvc/repo/experiments/executor/base.py#L563-L565

@pmrowla, do we need to log errors here if we want to raise it again anyway?

**Comment by pmrowla** [comment]
We normally need to log them here because they are normally not re-raised. The exceptions happen inside multiprocessing child process contexts, and an exception is returned w/ the multiprocessing futures, but the exceptions are not re-raised at that point.
https://github.com/iterative/dvc/blob/47d10c4a8b9bdc18dec17a9380f0593e43383c4c/dvc/repo/experiments/executor/manager/base.py#L215

I think the issue here is just a bug in the workspace specific handling after the executor refactors. For workspace runs specifically, we should be passing `log_errors=False` here, since we can just directly pass the exceptions back to the caller (since workspace runs don't happen inside the multiprocessing context)

https://github.com/iterative/dvc/blob/47d10c4a8b9bdc18dec17a9380f0593e43383c4c/dvc/repo/experiments/executor/manager/local.py#L86
