### ISSUE TITLE
Add support for Huawei cloud obs

### ISSUE THREAD

**Issue by satheeshkatipomu** [iterative/dvc#7332]
Hi,

Thank you for creating dvc. I have used it using s3 as remote storage. It was pretty neat. Can you please add support for huawei cloud obs? It is almost similar to AWS S3.

**Comment by efiop** [comment]
Hey @satheeshkatipomu !

Unfortunately, we don't have capacity right now to add support for new remotes, as we are trying to focus on quality of existing ones and other features 🙁 That being said, we are working on introducing dvc plugins that would allow users to use unofficial storage types. So in order to support obs, one would need to first implement a full-featured [fsspec](https://github.com/fsspec/filesystem_spec) implementation for it and then that could be plugged into dvc in the near future. For example, thanks to great work by @karajan1001 we now have https://github.com/fsspec/ossfs for Alibaba oss. So anyone who's interested in obs, would need to create a similar implementation for obs.

**Comment by satheeshkatipomu** [comment]
Thanks for the response.
