### ISSUE TITLE
exp show/list: help text for -n

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7444]
From https://github.com/iterative/dvc.org/pull/3187#discussion_r821382100.

@karajan1001 @jorgeorpinel What is the suggested text now? I'm a bit lost with all the updates.

**Comment by dberenbaum** [comment]
@jorgeorpinel Do you think the "first-parent" stuff in the description is too much detail/too technical for the CLI help? Also, do you think we need to reference Git somewhere in the docs when mentioning it?

No need to block any PR for these questions. We can always tweak language in future PRs.

**Comment by dberenbaum** [comment]
Also should include `remove`, `push`, and `pull`.

**Comment by jorgeorpinel** [comment]
> What is the suggested text now? 

In docs we went with your [last suggestion](https://github.com/iterative/dvc.org/pull/3187#pullrequestreview-903319359):

```md
- `-n <num>`, `--num <num>` - show experiments from the last `num` commits
  (first parents) starting from the `--rev` baseline. Give a negative value to include
  all first-parent commits (similar to `git log -n`).
```

> Do you think the "first-parent" stuff in the description is too much detail

I think it's important for the `-n -x` case because the tree can be long and not all parents are included. Unless you phrase it differently e.g. "negative number goes back to the git history root". Up to you.
