### ISSUE TITLE
gc: have option to keep .dir files

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7496]
From https://discord.com/channels/485586884165107732/485596304961962003/956093681818034246:

> I am very surprised by the fact dvc gc removes .dir files by default, this seems counterintuitive to me and dangerous. After making the mistake of running dvc gc after data deletion (cleaning),  now all data tracked and tagged previously is rendered useless as the .dir files has all been deleted. I do not get why will this be the default setting for garbage collection, .dir files are the core of dvc tracking and the deletion of it renders the data.dvc of all previous commits to be useless.  To be fair, re-reading the docs, it does state removal of file and directories but I assumed it meant actual directories in the file system and not the .dir files. This leads to the question: Wouldn't the deletion of .dir be the exception rather than the rule as most cases wants to retain the .dir but delete all the unnecessary files from cache?
>
>
> If .dir files are kept while there are missing file locations (due to data deletion + running dvc gc --cloud -w to remove unnecessary data), we can switch to the older data.dvc file to reconstruct the dataset while ignoring all the missing locations (already deleted for good); providing a simple message stating how many files are missing will be useful here. 
>
> Use case example
datav1: start tracking image dataset, dataset source from blablabla
datav2: add new data from another dataset source to combine with current data collected from datav1
datav3: clean up all mislabels and blurry images, clean up the data cache for good in dvc via dvc gc --cloud -w
>
> In the current dvc version, we can never go back to datav1 or datav2 anymore as the .dir files of these respective data.dvc is gone.  It is useful to go back to datav1 or datav2 and reconstruct the dataset (ignoring all the deleted images). That way, I can still track all previous dataset that I have while all the images that I do not want is gone from it.

**Comment by timothylimyl** [comment]
Hi, my suggestion is to provide an argument to flag whether to save `.dir` files or not. I am in favor of `.dir` files being kept as default, open to discussion.

We have to definitely allow `dvc checkout/pull` even if there are missing files, a message can be provided when missing files are detected such as:
```
CAUTION: Missing Files Detected

Total Expected Files: 5000
Total Missing Files: 20
Total Files that will be pulled: 4880

If you want to print out all the differences between the current and previous commit of the data.dvc files, please use the command:

dvc diff prev-commit-id curr-commit-id  , we can automatically check the commit-id of the current `data.dvc` file to what the user is checked out to.

Confirm to continue [Y/n]:
```

**Comment by pmrowla** [comment]
I'm confused as to the need for this, since when you use `dvc gc --cloud -w` in the first place, all of the files are also removed from the remote. Preserving the `.dir` file would only tell you that you have 5000 files that can no longer be pulled.

It seems like there may be some confusion between using `dvc gc` and `dvc gc --cloud` here. To remove data from your local cache, you use `dvc gc` (without `--cloud`). `dvc gc -w` will clean up all the data from your local cache that is not used in your current workspace. This does not affect data in any of your DVC remotes. If a `.dir` file is removed from your local cache and is needed for a future `pull` operation, DVC can retrieve that `.dir` file from the DVC remote (and does this automatically during commands like `dvc pull` and `dvc status --cloud`.

If you intend to pull `datav1` and `datav2` in the future, you should never be using `dvc gc --cloud -w`. Using `dvc --cloud -w` will remove all files (and `.dir` files) that are not used in your current workspace from the remote. This means that any files that only exist in `datav1` and not your current workspace will also be removed (and can never be `dvc pull`ed in the future).

**Comment by dberenbaum** [comment]
@pmrowla That was also my initial reaction, but I think it makes sense in the use case presented above:

> Use case example
> datav1: start tracking image dataset, dataset source from blablabla 
> datav2: add new data from another dataset source to combine with current data collected from datav1
> datav3: clean up all mislabels and blurry images, clean up the data cache for good in dvc via dvc gc --cloud -w
> 
> In the current dvc version, we can never go back to datav1 or datav2 anymore as the .dir files of these respective data.dvc is gone. It is useful to go back to datav1 or datav2 and reconstruct the dataset (ignoring all the deleted images). That way, I can still track all previous dataset that I have while all the images that I do not want is gone from it.

They may still want to pull the intersection of `datav3` and either `datav1`/`datav2`. By keeping the `.dir` files from `datav1`/`datav2`, they could pull whatever files remain. Although the pull would "fail," it should retrieve all the files that still exist in the intersection of that data and `datav3`.

On the other hand, it seems like this violates a basic principle of dvc caching since we want to assume that every object referenced in `.dir` files exists, and I'm not sure how common this need is among dvc users. This might be a use case for @volkfox to consider, since it might be better addressed outside of dvc.

**Comment by timothylimyl** [comment]
@pmrowla , my point was to provide an option to keep the `.dir` files in local/remote while deleting everything else that is unnecessary from both local and remote (`--cloud -w`).  If we only do `gc -w` then the remote will still contain all of the unnecessary files that is taking up our space. 

The important feature is to allow us to pull whatever files remain as mentioned by @dberenbaum.  My current workaround is keeping it all in the remote location as suggesed by @pmrowla.

The thing is DVC already has this capability, it can see the differences of both `.dir` files and let us know what was removed. Example of running `dvc diff old-data HEAD`:
```
Deleted:
    data_segmentation/n02089973/ILSVRC2012_val_00007929.JPEG
    data_segmentation/n02111889/ILSVRC2012_val_00022266.JPEG
    data_segmentation/n02111889/ILSVRC2012_val_00031709.JPEG
    data_segmentation/n02111889/ILSVRC2012_val_00041759.JPEG

Modified:
    data_segmentation/


files summary: 4 deleted
```

DVC can check what files are missing (output it to the users),  `dvc pull/checkout` then allows us to restore everything that remains.

I am not aware of this: "On the other hand, it seems like this violates a basic principle of dvc caching since we want to assume that every object referenced in .dir files exists, ". **If this is a dvc core principle, then I think this issue thread can be closed**

**Comment by karajan1001** [comment]
Agreed that if you want to switch back to `datav1`, you should not use `dvc gc -w` at all.

**Comment by dberenbaum** [comment]
Closing as not planned since there does not seem to be any further interest in this feature
