### ISSUE TITLE
pull: DVC installed via Ubuntu .deb fails to pull from S3 remote but DVC installed via pip works

### ISSUE THREAD

**Issue by rightparen** [iterative/dvc#7531]
# Bug Report

## Description

In Circle CI, the command `dvc pull -f assets/models` began failing between Mar 30 4:18:21 PM PDT and Mar 30 9:28:58 PM PDT when using the Ubuntu `.deb` from https://dvc.org/deb/dvc.list.  All commits in the repo fail with the same error now, and the main branch has not changed since all commits succeeded.

The same command with the same Circle CI environment and same source tree passes if we use `pip install dvc[s3]` to install DVC.

The output in the log when it fails is:
```
A       assets/models/
1 file added and 12 files fetched
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_importers.py", line 298, in get_code
  File "PyInstaller/loader/pyimod02_archive.py", line 287, in extract
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/__main__.py", line 7, in <module>
  File "dvc/cli/__init__.py", line 121, in main
  File "dvc/analytics.py", line 37, in collect_and_send_report
  File "dvc/daemon.py", line 109, in daemon
  File "inspect.py", line 1514, in stack
  File "inspect.py", line 1491, in getouterframes
  File "inspect.py", line 1465, in getframeinfo
  File "inspect.py", line 792, in findsource
  File "inspect.py", line 745, in getmodule
  File "importlib/util.py", line 245, in __getattribute__
  File "PyInstaller/loader/pyimod03_importers.py", line 478, in exec_module
  File "PyInstaller/loader/pyimod03_importers.py", line 300, in get_code
TypeError: can only concatenate str (not "dict") to str
[2151] Failed to execute script '__main__' due to unhandled exception!
```

### Reproduce

In Circle CI, install DVC using Ubuntu `.deb` package from dvc.org:
```
    steps:
      - run:
          # DVC CLI is required to download production models from our DVC repository.
          name: Install DVC
          command: |
            sudo wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list
            # TODO: commit iterative.asc key to repo rather than downloading from dvc.org
            wget -qO - https://dvc.org/deb/iterative.asc | sudo apt-key add -
            sudo apt update
            sudo apt install dvc
            dvc version
```

The reported `dvc version` information at the end of that Circle CI block (this is the version that fails):
```
DVC version: 2.10.0 (deb)
---------------------------------
Platform: Python 3.8.3 on Linux-5.13.0-1017-aws-x86_64-with-glibc2.14
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.8.0),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.2.0),
	hdfs (fsspec = 2022.2.0, pyarrow = 7.0.0),
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.2.0, boto3 = 1.20.24),
	ssh (sshfs = 2022.3.1),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.5),
	webdavs (webdav4 = 0.9.5)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: overlay on overlay
Repo: dvc, git
```

Use `dvc pull -f some/path` to pull `some/path.dvc` contents from an S3 remote.

### Expected

`dvc pull -f some/path` works, whether DVC is installed from a `.deb` or via `pip`.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
```
DVC version: 2.10.0 (deb)
---------------------------------
Platform: Python 3.8.3 on Linux-5.13.0-1017-aws-x86_64-with-glibc2.14
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.8.0),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.2.0),
	hdfs (fsspec = 2022.2.0, pyarrow = 7.0.0),
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.2.0, boto3 = 1.20.24),
	ssh (sshfs = 2022.3.1),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.5),
	webdavs (webdav4 = 0.9.5)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: overlay on overlay
Repo: dvc, git
```

**Additional Information (if any):**

The `dvc pull ...` works when I replace the `apt-get` installation steps above with an equivalent that uses pip to install DVC:
```
    steps:
      - run:
          # DVC CLI is required to download production models from our DVC repository.
          name: Install DVC
          command: |
            sudo apt-get update
            sudo apt-get install python3-pip
            sudo python3 -m pip install dvc
            sudo python3 -m pip install 'dvc[s3]'
            dvc version
```

The version reported by the `pip` installation is (this is the version that works):
```
DVC version: 2.10.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.13.0-1017-aws-x86_64-with-glibc2.29
Supports:
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.2.0, boto3 = 1.21.21)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: overlay on overlay
Repo: dvc, git
```

The output with this version is:
```
A       assets/models/
1 file added and 12 files fetched
```

**Comment by lcbm** [comment]
Having the same issue, with GitLab CI, I reported this earlier today in the [in DVC's Discord community](https://discord.com/channels/485586884165107732/485596304961962003/959115274651566120).[in DVC's Discord community](https://discord.com/channels/485586884165107732/485596304961962003/959115274651566120) as well. I'll leave the same information here, LMK I could be of further assistance.

---

### `dvc pull`: fails to pull from SSH remote

**Description**

In short, we have a `reports` stage in our CI/CD pipeline where we pull data (more specifically, evaluation data, e.g. confusion matrix) using `dvc` and build a report with that. Yesterday, our pipeline was working just fine. Today, we ran the pipeline again (no alterations) and we received the following error:

```
$ dvc pull --run-cache --remote "$DVC_REMOTE_NAME" "$DVC_EVALUATION_DIR"
A       data/ef/evaluation/
1 file added and 8 files fetched
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_importers.py", line 298, in get_code
  File "PyInstaller/loader/pyimod02_archive.py", line 287, in extract
TypeError: unhashable type: 'dict'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "dvc/__main__.py", line 7, in <module>
  File "dvc/cli/__init__.py", line 121, in main
  File "dvc/analytics.py", line 37, in collect_and_send_report
  File "dvc/daemon.py", line 109, in daemon
  File "inspect.py", line 1514, in stack
  File "inspect.py", line 1491, in getouterframes
  File "inspect.py", line 1465, in getframeinfo
  File "inspect.py", line 792, in findsource
  File "inspect.py", line 745, in getmodule
  File "importlib/util.py", line 245, in __getattribute__
  File "PyInstaller/loader/pyimod03_importers.py", line 478, in exec_module
  File "PyInstaller/loader/pyimod03_importers.py", line 300, in get_code
TypeError: can only concatenate str (not "dict") to str
[19] Failed to execute script '__main__' due to unhandled exception!
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

**Reproduce**

In GitLab CI, use the iterativeai/cml:0-dvc2-base1 image to pull data from the remote server and publish a report:

```
image: "python:3.10-slim"

# ...

.config-ssh:
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -yq && apt-get $APT_OPTIONS install -y openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

# ...

reports:
  stage: reports
  image: iterativeai/cml:0-dvc2-base1
  extends: .config-ssh
  variables:
    DVC_REMOTE_NAME: "<name>"
    DVC_EVALUATION_DIR: "data/ef/evaluation"
    DVC_CONFUSION_MATRIX_FILE: "$DVC_EVALUATION_DIR/confusion_matrix_graph.png"
    DVC_CLASSIFICATION_REPORT_FILE: "$DVC_EVALUATION_DIR/classification_report"
  script:
    - dvc pull --run-cache --remote "$DVC_REMOTE_NAME" "$DVC_EVALUATION_DIR"

    - printf "## Classification Report\n" > report.md
    - cat "$DVC_CLASSIFICATION_REPORT_FILE" >> report.md
    - printf "\n\n## Confusion Matrix\n" >> report.md

    - cml publish "$DVC_CONFUSION_MATRIX_FILE" --md >> report.md
    - cml send-comment --token "$GITLAB_CML_TOKEN" report.md
```

**Environment information**

Output of `dvc doctor`:

```
DVC version: 2.10.0 (deb)
---------------------------------
Platform: Python 3.8.3 on Linux-5.13.0-37-generic-x86_64-with-glibc2.14
Supports:
    azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.8.0),
    gdrive (pydrive2 = 1.10.0),
    gs (gcsfs = 2022.2.0),
    hdfs (fsspec = 2022.2.0, pyarrow = 7.0.0),
    webhdfs (fsspec = 2022.2.0),
    http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
    https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
    s3 (s3fs = 2022.2.0, boto3 = 1.20.24),
    ssh (sshfs = 2022.3.1),
    oss (ossfs = 2021.8.0),
    webdav (webdav4 = 0.9.5),
    webdavs (webdav4 = 0.9.5)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: ssh, local
Workspace directory: ext4 on /dev/sda3
Repo: dvc, git
``` 

**Additional Information (if any):**

(a) We noticed there was an update in DockerHub for the tag we were using, just about 7 hours ago. I'm assuming it could be something related to the changed pushed to the image. I could be wrong, however. 
```
0-dvc2-base1
Last pushed 8 hours ago by iterativeaibot
DIGEST 7fc267e11fb3
```

(b) I am able to use the same `dvc pull ...` command locally (also using the same SSH config, key, etc):
```
λ eval "$(ssh-agent -s)"
λ ssh-add ~/.ssh/id_ed25519_x_gitlab_ci
λ dvc pull --run-cache --remote balllab data/ef/evaluation
A       data/ef/evaluation/
1 file added and 8 files fetched
```

(c) For reference, we left the stages of interest from our `.gitlabci.yml` (in **Reproduce** section, above) as well a screenshot from a past GitLab CI pipeline log, where it succeeded with the same `yml`:.

![image](https://user-images.githubusercontent.com/31375047/161120182-50cc8199-d7d3-404b-8efd-098600a8de7a.png)

As instructed by @dabarnes#8000 (DVC's community Discord user), we further ran the `dvc doctor` command (output below) both locally and in the CI/CD pipeline. From that, we observed the following:

(e) The `dvc` tool CI and local versions are different: local (`2.9.3`) and CI (`2.10.0`). We tried updating local dvc to `2.10.0` and running the same `dvc pull...` command yields no errors locally. 

(f) The CI and local `platform` (Python) are different: local (`Python 3.10`) and CI (`Python 3.8.3`). Since we're using iterativeai/cml:0-dvc2-base1, we can't update the CI's platform (Python version).

Local `dvc doctor` output (`dvc pull` working):

```
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.10.4 on Linux-5.17.1-arch1-1-x86_64-with-glibc2.35
Supports:
    hdfs (fsspec = 2022.1.0, pyarrow = 7.0.0),
    webhdfs (fsspec = 2022.1.0),
    http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
    https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
    ssh (sshfs = 2021.11.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p3
Caches: local
Remotes: ssh, local
Workspace directory: ext4 on /dev/nvme0n1p3
Repo: dvc, git
```

**Comment by casperdcl** [comment]
`@dabarnes` is actually @dacbd here, right?

**Comment by dtrifiro** [comment]
I can confirm 2.9.5 works fine and that 2.10 is broken

**Comment by pmrowla** [comment]
I'm looking into this now, I'm assuming rolling back to pyinstaller 2.9 (same version used to build 2.9.5) will work as a short term workaround

**Comment by pmrowla** [comment]
So after some more research, it looks like the error happens when trying to spawn the analytics daemon, so for users encountering this problem, [disabling analytics](https://dvc.org/doc/user-guide/analytics#opting-out) should work as a temporary workaround.

When building with pyinstaller 2.9, I still see the same issue, and it looks like nothing significant was changed in the daemon code at all since 2.9.5, so this will require some deeper investigation

**Comment by pmrowla** [comment]
After some more digging, it looks like this is a general pyinstaller issue for us. It's not specific to the debian packaging, and I can reproduce it with macos pyinstaller builds. I haven't tested the actual packages from the dvc.org site, but I'm assuming users will get the same issue if they install 2.10.0 from the macos pkg or the windows exe

It looks to be some conflict with using `inspect.getmodule` (via `inspect.stack`) in pyinstaller whenever `numpy` is also included in the package (numpy is a dependency of pyarrow, so it gets included in our pyinstaller builds). Removing numpy from the build environment resolves the issue.

It's still unclear as to what exactly causes the difference in behavior between the 2.9.5 and 2.10.0 builds, since nothing that appears relevant changed in DVC, numpy or pyinstaller in that time frame. And I can actually reproduce the issue on pyinstaller when buildng DVC 2.9.5 with pyinstaller 4.9 (which is what was used when the last .deb package worked properly).

The only difference I can see is that the 2.9.5 build environment was using python 3.9.10, while the current environment uses 3.9.12. So I will have to continue doing some more testing to see if the python release difference is actually what introduced the issue.
