### ISSUE TITLE
Changing permissions of dvc cache in NFS makes dvc checkout slow and buggy

### ISSUE THREAD

**Issue by dalnoguer** [iterative/dvc#7544]
Hello,

I am using DVC on an NFS in gcloud. Until recently, I was the only one registering new datasets in dvc using the cache in the same mounted NFS. Everything worked smoothly. However, when another user started registering datasets we had to change the dvc and its subdirectories permissions, otherwise there was a permission error when trying to write new files to the cache (I guess its due to the fact that the new user wanted to write files in a directory my user created). Changing permissions solved the issue.

However, when running `dvc checkout <path>.dvc` it gets stuck in the checkout with process to 0%. Then, after a long time it works.

Is this change in permissions changing the file hash? What is the issue?

Thanks!

**Comment by pmrowla** [comment]
Have you set the `cache.shared` config option in DVC?

If you are sharing a DVC cache directory (or an entire repo) between multiple users you need to set it to `group` so that DVC handles the file and directory permissions properly: https://dvc.org/doc/user-guide/how-to/share-a-dvc-cache#configure-the-shared-cache

**Comment by dalnoguer** [comment]
I was not aware about this. Thanks for the quick reply. Will try it out and close the issue if it works ;) Thanks!

**Comment by efiop** [comment]
closing as stale
