### ISSUE TITLE
exp queue: monitor queue status

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#7590]
Support monitoring queue status and viewing output of running experiments

* [x] `dvc queue status`
* [x] `dvc queue attach`
* [x] `dvc queue logs`

Optional/under discussion:

Remove queued exps from `exp show` by default and implement `exp show --queue` option to include queued exps in the table

**Comment by dberenbaum** [comment]
Does this include how to deal with failed experiments? We need the ability to see which experiments failed instead of having them "disappear."

Sorry for changing requirements here, but can `dvc queue attach` show all output up to the current point instead of streaming only new output? This would also be really useful for completed and failed experiments. Otherwise, I think it's hard to see what's happening in the experiments, and we may need a separate command like `dvc queue log`.
