### ISSUE TITLE
DVC subdependency conflict arising periodically 

### ISSUE THREAD

**Issue by mridul97-dev** [iterative/dvc#7706]
# Bug Report

## Description
Hi, currently dvc==2.8.1 is being used within our pipelines and starts to break randomly with the following logs [ss-attached]
<img width="653" alt="Screenshot 2022-05-06 at 1 36 18 PM" src="https://user-images.githubusercontent.com/77056469/167092960-974eeebf-5858-4b58-abae-be61ff01e38a.png">

On further investigation, i noticed that this happens due to subdepdency conflicts mainly with (due to which dvc is unable to pull models from s3) - 

1. boto3
2. botocore
3. s3fs
4. s3transfer
5. fsspec

We're using a pinned version of dvc==2.8.1 and dvc[s3]==2.8.1, but still have to manually downgrade/upgrade dependencies from time to time. Can anyone help suggest a proper fix for this? 

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by skshetry** [comment]
It'd be great if you could provide which versions worked for you? I'll recommend doing a `pip check` too, to see if there are any conflicts due to other packages. 

You can use `pip freeze` to see what's changed. 

> Can anyone help suggest a proper fix for this?

Being a python package/library, DVC has to have good support for a range of versions in those dependencies. If they are incompatible, we do bump the version.

You may also want to install from `pip freeze` output or use some kind of lockfiles like the way `pip-compile`/`poetry`/`pipenv` provides.  Again, it'd be great to know which version is dvc incompatible with, so that we can fix this for others users too.

**Comment by skshetry** [comment]
We don't really have control over newer versions of those libraries. All of those dependencies are transitive, from `s3fs`, except the `typing-extensions`.

If you can figure out which dependency is the problem there, that'd be great (aiobotocore recently had a release, so it's one of the suspects).

Also, Please try to run the command in `--verbose` mode, it'll have more information. I'll recommend you to also try with newer version of DVC, we don't support old versions.

**Comment by mridul97-dev** [comment]
Which dvc version or above would you recommend? Would prefer a version where sub dependency version upgrades dont interfere with dvc pull/push operations.

**Comment by skshetry** [comment]
@mridul97-dev, we only support the latest version at any time. :)

> Would prefer a version where sub dependency version upgrades dont interfere with dvc pull/push operations.

It's hard for us to guarantee all transitive dependencies because we don't control most of them. We expect them to be largely compatible, and if some are not compatible, we bump the version where they are. Other packages that you install may also cause conflicts.

Please try with the latest version, and let us know if there's any conflicts, we'll fix them right away. Thanks. 🙂
