### ISSUE TITLE
dvc exp run : runs very slow in big monorepositories (subdir dvc project)

### ISSUE THREAD

**Issue by ThibaultMetais** [iterative/dvc#7774]
# Bug Report

## Description

I am working inside a big repository with several projects inside, so I used the --subdir option when setting up my dvc project inside it.
dvc repro works fine, but when it comes to dvc exp run it is very slow. Thanks to a git client, I can see that the dvc exp run command is moving around a lot of files around the whole repo, and not only in the subdirectory where my project is located.
Finally, I tried to run the exact same project in a separate repository and everything works fine, so I assume that dvc exp run does not ignore the files outside the dvc project even with the subdir option, which affects the performances dramatically (it takes several minutes before running the pipeline at times).

### Reproduce

Inside a big repository:

1. dvc init --subdir (in the subdirectory of your choice)
2. dvc exp run

### Expected

A reasonnable execution time for the dvc exp run command. The subdir option should allow the user to ignore the files outside the directory that contains this particular dvc project.

### Environment information

dvc==2.10.1
git repository (Azure Repos)

**Comment by pmrowla** [comment]
The issue here is that experiments need to do git operations in a large monorepo. Possible solutions would be using sparse checkouts or partial clones, but these (git) features are not supported in libgit or dulwich and are non-trivial to implement.

A potential workaround may be using `stash -- <pathspec>` to try and avoid touching the rest of the monorepo when generating an experiment, but iirc pathspec support for stash is also not implemented in either git backend
