### ISSUE TITLE
Cannot install dvc, failing to install dulwich

### ISSUE THREAD

**Issue by mbergal** [iterative/dvc#7788]
![image](https://user-images.githubusercontent.com/167835/169404175-88aab973-f980-441d-94a6-922fa2c330d6.png)

**Comment by efiop** [comment]
Hi @mbergal . This is a known issue with a yet another dulwich release that broke its wheel building process. It is fixed in upstream, waiting for dulwich 0.20.41 to be released. On our side we will set an upper bound so this doesn't happen again https://github.com/iterative/scmrepo/issues/73

A workaround for now is to:

```
pip install dulwich==0.20.37
```

first
