### ISSUE TITLE
`dvc metrics diff --show-md` empty output for no diff

### ISSUE THREAD

**Issue by shortcipher3** [iterative/dvc#8141]
```
dvc metrics diff --show-md
```

Produces column headers if the files haven't changed.  It would be nice to have it output nothing (as I'm putting the output into a report and a table with headers and no rows is a little confusing).

Also it would be nice if `dvc metrics diff` behaved more like `diff` and returned a `0` error code if the files match and a `non-zero` error code if they do not match.

Haven't checked the plots diff, but that is another case to consider.

**Comment by pmrowla** [comment]
IIRC this is intentional - initially when the markdown output formats were added for CML, I think it was decided that having the empty header-only table (to indicate that there are no changes) was preferred over having the table not show up at all in the output report.

We can revisit this but it may require input from the CML team as well @dberenbaum

**Comment by shortcipher3** [comment]
I was thinking you could provide an optional flag that would determine the behavior.

**Comment by dberenbaum** [comment]
> Produces column headers if the files haven't changed. It would be nice to have it output nothing (as I'm putting the output into a report and a table with headers and no rows is a little confusing).

As @pmrowla, this is intentional because:

1. It's often less confusing to have an empty table in the metrics section of a report than nothing at all. At least it's clear the command worked and output something.
2. It's easier to work around it this way than vice versa. You can at least check if there's any output from `dvc metrics diff` and only do `dvc metrics diff --md` if there is some output.

> Also it would be nice if `dvc metrics diff` behaved more like `diff` and returned a `0` error code if the files match and a `non-zero` error code if they do not match.

This may introduce more problems than it solves, especially since it's easy to work around this by checking the output of `dvc metrics diff` as mentioned above. A typical pattern is to use `dvc metrics diff --md` as part of CI, and it's often expected that the metrics will not match. Having to deal with the non-zero codes for these circumstances seems like an extra annoyance there.

---
 
We discussed in https://github.com/iterative/dvc/issues/5576 that we could introduce `--silent` in these scenarios if needed. I don't think it's likely to be a priority soon, but if someone wants to contribute that option, we could merge it.
