### ISSUE TITLE
ui: Add `show_empty` option for `table`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#8179]
seems like we should maybe have something like a `show_empty` flag rather than relying on what output format is set

_Originally posted by @pmrowla in https://github.com/iterative/dvc/pull/8177#discussion_r954693597_

**Comment by dberenbaum** [comment]
Seems like this is getting back to the discussion in https://github.com/iterative/dvc/issues/8141 but in reverse?

**Comment by pmrowla** [comment]
@dberenbaum I'm not sure it's the same? This issue isn't about having CLI flag support for whether or not to display an empty table, it's about the internal `ui.table` API, which assumes it should never print any output for empty tables except for when it is markdown mode.

The problem here was that in an empty git repo, after the changes in #8177 `exp show` (with no other json/md flags) just exits immediately with no output at all due to how `ui.table` works right now.

I don't think `exp show` exiting immediately is the right behavior, we either need to print a message about why there is no table, or just force drawing the empty table.

Whether or not using `--md` should draw empty tables is a separate discussion (and depends on CML needs)
