### ISSUE TITLE
Relax Rich Requirement

### ISSUE THREAD

**Issue by nmichlo** [iterative/dvc#8218]
https://github.com/iterative/dvc/blob/e7daeb1c3e07b754de898c38f710d73561f427a9/setup.cfg#L62

Is it possible to relax the rich requirement? possibly to `>=9`.

This would greatly help compatibility with other libs.

**Comment by skshetry** [comment]
Sorry, we cannot. That version `10.13.0` of `rich` is almost a year old. I suggest opening an issue on the projects that are incompatible. `rich` is a relatively young project, and will have new features/bugfixes that we want to use. Anyway, we are not very strict since the recent version is 12.5.1.

**Comment by efiop** [comment]
@nmichlo If you are not using dvc through python api (and only using CLI instead), you might want to install it through one of the binary packages (e.g. deb, rpm, exe) or isolated packages (pipx, snap, homebrew, etc), to isolate your libraries depending on old rich from dvc.

**Comment by nmichlo** [comment]
This is not an ideal solution if dvc is a dependency in an existing projects requirements.

**Comment by efiop** [comment]
@nmichlo So you are using dvc purely through python api? Could you elaborate on your use case, please?

**Comment by nmichlo** [comment]
@efiop 

One of our use cases is versioning and the pulling data for automated testing.
