### ISSUE TITLE
Auto resolve merge conflicts in dvc metadata

### ISSUE THREAD

**Issue by RCdeWit** [iterative/dvc#8233]
A merge conflict arises in the DVC metadata when:
- A development branch is behind `main`;
- There has been a DVC commit on `main`;
- There is a DVC commit on the development branch.

The [user guide](https://dvc.org/doc/user-guide/how-to/merge-conflicts) mentions how the merge driver can resolve merge conflicts automatically in append-only directories. This does not work when files can be updated, moved, removed, or renamed.

In that case, the solution to the merge conflict is as follows:
1. Checkout `main` and copy the files that are not in the development branch to a temporary directory;
2. Checkout the development directory and copy the files from the temporary directory back to the project;
3. Commit and push the changes to the development branch;
4. Resolve the merge conflict manually by overwriting `main`'s metadata with the development branch metadata.

This is far from a great user experience and gets worse with more branches. Based on my understanding of DVC, it would be quite difficult to prevent this without fundamentally changing the metadata structure.

I believe UX would greatly be improved if DVC could help you automatically resolve these conflicts.

Related:
- [iterative/iterative.ai script for this purpose](https://github.com/iterative/iterative.ai/pull/561/files#diff-35be933bbd1078a7d491f8d9a7d69f4c834698aaa176fd87a3d8cfe7ba72428a)
- [Slack thread documenting my experience while encountering this for the first time](https://iterativeai.slack.com/archives/CB41NAL8H/p1662025266339669)

**Comment by shcheklein** [comment]
cc @mattseddon - can we plug into VS Code merge tool and do something with it? Or even put together our own merger for directories.

**Comment by dberenbaum** [comment]
Related: https://github.com/iterative/dvc/issues/5151

It would be nice to give users an option to setup the merge driver during `dvc init`. I understand we may not want to automatically touch user's Git config, but I can't think of much downside if we let them know up front and ask if they want to do so.

I also see no reason DVC can't have a merge driver that works for all situations except where both sides make some change to the same file path. I assume it just hasn't been a priority. It looks like support for removed files already exists in https://github.com/iterative/dvc-data/blob/f7e932a0cafa751ed2eb23683e0f18fc3339e504/src/dvc_data/objects/tree.py#L253 and just needs to be enabled for the merge driver. I don't see why support couldn't be added even for modified files as long as only one side modifies the file.

**Comment by mattseddon** [comment]
> cc @mattseddon - can we plug into VS Code merge tool and do something with it? Or even put together our own merger for directories.

I have a task to look into it.

**Comment by mattseddon** [comment]
> cc @mattseddon - can we plug into VS Code merge tool and do something with it? Or even put together our own merger for directories.

Gitlens has tried to provide a merge tool for directories but I can't seem to get it to work. This definitely seems like a non-trivial piece of work. IMO to provide further value outside of the SCM tree we would need to get access to the original files from the conflicted path (i.e `dvc checkout <target(s)> <rev>`. In order to add the functionality we would therefore need to do a large workaround with something like `git stash`.*

I've looked further into the problem in general as well. One thing that jumps out as a possibility with the about-to-be-introduced language server is that we should be able to detect merge conflict markers in any of the DVC-based YAML files. If any are detected we could prompt the user to go to the existing docs page via the normal toast message.

Going through the actions already listed on that page:

## [Simple tracking (add)](https://dvc.org/doc/user-guide/how-to/merge-conflicts#simple-tracking-add)

### "You can pick one of the versions"

VS Code should already help with this. We do not need to take any action for this scenario.

### "But if you want to actually merge the data files (or directories) of both versions, then you can follow this process:"/"Merge if by hand" 

We can provide a diff editor under these circumstances (screenshot below of diff editor). 

![Screen Shot 2022-09-07 at 11 32 27 am (2)](https://user-images.githubusercontent.com/37993418/188769146-5f012e2a-1dc5-4a5e-976a-6573c2363e1e.png)

In order to do that we would need access to the conflicted version of the file. See * above for more information.

## [Append-only directories](https://dvc.org/doc/user-guide/how-to/merge-conflicts#append-only-directories)

### DVC provides a so-called [merge-driver](https://git-scm.com/docs/git-merge#Documentation/git-merge.txt-mergeltdrivergtname)

We can add a wizard to "auto-magically" set up this driver under certain circumstances. It would follow the normal flow of a toast message appearing when the problem presents itself.

## [Imported data](https://dvc.org/doc/user-guide/how-to/merge-conflicts#imported-data)

### To resolve conflicted [.dvc](https://dvc.org/doc/user-guide/project-structure/dvc-files) files generated by [dvc import](https://dvc.org/doc/command-reference/import) or [dvc import-url](https://dvc.org/doc/command-reference/import-url), remove the conflicted values altogether:

This definitely seems like something we may be able to detect via the language server but that would be a later step IMO.

**Comment by shcheklein** [comment]
> We can provide a diff editor under these circumstances (screenshot below of diff editor).

Yep, this is what would be interesting to explore. In this case we might need to build a custom way to show lists of added, removed, renamed files in those split panes.
