### ISSUE TITLE
exp: random sweeps

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8258]
As a follow up to #8083, it would be helpful to have support for random search. It's not possible with the basic sweeper in hydra. 

Possible solutions:
1. Add support for random search override syntax in the hydra basic sweeper (https://hydra.cc/docs/advanced/override_grammar/extended/#sweeps). Since random search needs to select random combinations across multiple parameters, I think this would require another top-level parameter to designate a random sweep and additional parameters (most importantly, the number of experiments to randomly try).
2. Add a new hydra sweeper for random search.
3. Add DVC-specific syntax for random search.

cc @alex000kim

**Comment by JohnTheDeere** [comment]
Thumbs of from me to this one! Before starting to use dvc more actively I used to use [test_tube](https://github.com/williamFalcon/test-tube/blob/master/docs/hyperparameter_optimization/HyperOptArgumentParser.md) for this exact purpose in my projects.

There generating random trials is implemented like:
```
    def __generate_random_search_trials(self, params):
        results = []

        # ensures we have unique results
        seen_trials = set()

        # shuffle each param list
        potential_trials = 1
        for p in params:
            random.shuffle(p)
            potential_trials *= len(p)

        # we can't sample more trials than are possible
        max_iters = min(potential_trials, self.nb_iterations)

        # then for the nb of trials requested, create a new param tuple
        # by picking a random integer at each param level
        while len(results) < max_iters:
            trial = []
            for param in params:
                p = random.sample(param, 1)[0]
                trial.append(p)

            # verify this is a unique trial so we
            # don't duplicate work
            trial_str = json.dumps(trial)
            if trial_str not in seen_trials:
                seen_trials.add(trial_str)
                results.append(trial)

        return results
```
It's quite nice because for each parameter you can specify either `min`/`max` values or give a list of values to randomly select from.

Can help with this if necessary.
