### ISSUE TITLE
Install DVC with winget

### ISSUE THREAD

**Issue by bryan-bg** [iterative/dvc#8392]
winget is an easy way to install Windows applications. It would be convenient if DVC had a winget installation option.

More details:
https://learn.microsoft.com/en-us/windows/package-manager/winget/

Thank you for your consideration!

For example, here is documentation on download Git with winget:
https://git-scm.com/download/win

**Comment by pmrowla** [comment]
While we have no plans to maintain a winget package ourselves, anyone is allowed to submit packages to their repository: https://github.com/microsoft/winget-pkgs

**Comment by efiop** [comment]
For windows we support chocolatey and exe already among other things like pypi. I don't think we need more packages right now on our side, as we don't have capacity to maintain them (at least right now). Closing since this is mostly up to anyone actually wanting to add this to https://github.com/microsoft/winget-pkgs , as noted by @pmrowla
