### ISSUE TITLE
plots: make smooth default

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8396]
Should the `smooth` plot be the default either in DVC or DVCLive? What about in VS Code or Studio?

Comment from @dmpetrov :

> It is hard to understand the pattern without smoothing - 0.5% improvement (a tremendous model improvement!) are not-recognizable without smoothing. See TB, wandb etc. It would be amazing to be able to change the smoothing coefficient in UI.

**Comment by dberenbaum** [comment]
@pared Do you know if there's a reason the min value for the smooth template is 0.001 and not 0? If we make the min 0, I'd see no reason not to make it default since it only adds functionality to the existing template.

**Comment by pared** [comment]
I left it at this value due to the behavior, which I had no time to investigate and check whether it's intended or a bug:
![Screenshot 2022-10-05 at 13 37 51](https://user-images.githubusercontent.com/10195618/194052284-2d5d66ac-4e32-4671-a2bf-6bc03dadd18c.png)
![Screenshot 2022-10-05 at 13 40 56](https://user-images.githubusercontent.com/10195618/194052293-1eef6b21-ab5c-42d8-9777-0782e2d70375.png)

**Comment by dberenbaum** [comment]
Fixed by https://github.com/iterative/dvc-render/pull/112
