### ISSUE TITLE
How do you organize dvc files?

### ISSUE THREAD

**Issue by LexSong** [iterative/dvc#857]
Currently I have a project structure like this:

    project\
    project\data\raw_data.zip
    project\data\raw_data.zip.dvc
    project\data\processed_data.npy
    project\data\processed_data.npy.dvc # I want to put dvc file here
    project\scripts\process_data.py

I ran `python scripts\process_data.py` under `project` directory to generate `processed_data.npy`

I could `dvc run python scripts\process_data.py` to generate dvc file. However it leaves the dvc file at the project root. I tried to use `-f` and `-c` options to generate dvc file under data directory, but I can't `dvc repro` successfully.

Is it true that we can only put dvc files at where we run the command? Thanks

**Comment by LexSong** [comment]
Related issue: #779

**Comment by villasv** [comment]
Another related discussion: https://github.com/iterative/dvc/issues/611

**Comment by efiop** [comment]
Hi @LexSong !

> Is it true that we can only put dvc files at where we run the command?

It is true for the `dvc run` for the reasons listed in the #611(e.g. because using different paths in the command itself and -d/-o for dvc run would create a lot of confusion and because we think that your dvcfiles are a part of description for your project and thus it is a lot easier to follow the project structure if you don't have them hidden somewhere), but you are free to write/edit dvc files manually to suit you specific needs. Dvc files are in a simple self-explanatory yaml format which is very easy to edit. Here is an example of a dvc file for simple copy stage:

```
cmd: ./copy.py foo bar
deps:
- path: foo
- path: copy.py
outs:
- cache: true
  path: bar
```

If you want to put your dvcfile somewhere else, just modify your command and deps/outs path properly. E.g. if you wish to put your dvcfiles into mydvcfiles directory, but run your scripts from code directory and put your data to data directory, you can write you dvc file like so:

```
cmd: cd code && ./copy ../data/foo ../data/bar
deps:
- path: ../data/foo
- path: ../code/copy.py
outs:
- path: ../data/bar
```

Thanks,
Ruslan

**Comment by LexSong** [comment]
Currently I have settled with solution like this:

    cmd: python ../scripts/data/data_script1.py
    deps:
    - path: raw_data.zip
    outs:
    - path: processed_data.npy

with .dvc in `/data` folder, and modify scripts to run under `/data` folder, too.

Although it's nice to generate dvc files automatically for small project, I think this approach may get into trouble when the project becomes more complex. Thanks for your helps. I may experiment more different options in the future.

**Comment by efiop** [comment]
Both my example and yours could be generated with `dvc run` as well. It just so happened that we talk more about `dvc run` instead of manual dvcfile writing, but we actually think of both ways as being equal and they both have their pros and cons and are suitable for some situations more than others.

Feel free to share your experience, we really appreciate any feedback!

Thanks,
Ruslan

**Comment by efiop** [comment]
Issue seems to be resolved. Closing for now. Feel free to reopen.
