### ISSUE TITLE
exp run --temp: Process creates and leaves lock files in .dvc/tmp after creating checkpoint

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#8628]
# Bug Report

## Description

I am not sure exactly why this happens, but I just noticed there are lock files `lock` and `rwlock.lock` with `.dvc/tmp` with the PID of the running `dvc exp run --temp` process. This causes "unable to acquire lock" errors for `dvc` commands in the workspace.

### Expected

 I would have expected the `--temp` option to isolate the execution of the experiment using DVC checkpoints sufficiently such that it would not interfere with use of DVC command in the workspace.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.31.0 (rpm)
---------------------------------
Platform: Python 3.8.3 on Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.14
Subprojects:

Supports:
        azure (adlfs = None, knack = 0.10.0, azure-identity = 1.11.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = None),
        hdfs (fsspec = None, pyarrow = 9.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = None, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7),
        webhdfs (fsspec = None)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/md124
Caches: local, s3
Remotes: s3, s3
Workspace directory: xfs on /dev/md124
Repo: dvc (subdir), git
```

**Additional Information (if any):**

**Comment by aschuh-hf** [comment]
The same lock files `lock` and `rwlock.lock` (i.e., with the same PID) are also inside the temp folder in `.dvc/tmp/exps/standalone/tmpXXX/.../.dvc/tmp`. This is expected. The issue is rather the lock files in `.dvc/tmp`.

**Comment by karajan1001** [comment]
Hi, @aschuh-hf . Thanks for your reporting. 

Sorry `lock` and `rwlock.lock` might not be the reason for `unable to acquire lock`. They just needed to be cleaned after the `DVC` command was finished.  What you met might be because of #8448. In previous we lock the whole repository during the initialization of the `dvc exp run --temp` process, and because of #8477, this progress might last for tens for seconds. In the latest `main` branch we have made a more granular lock during this progress, it only locks the running experiment.

**Comment by pmrowla** [comment]
This should be resolved in the latest releas w/the recent changes to exp collection/locking behavior. Feel free to re-open the issue if you run into it again.
