### ISSUE TITLE
cloud versioning: not able to do any data sync operations

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8670]
# Bug Report

## Description

https://github.com/iterative/dvc/pull/8662 broke all data sync operations.

### Reproduce

Try any of the following with a `version_aware` or `worktree` remote:

```
$ dvc push
ERROR: failed to push data to the cloud - config file error: '<command>' is unsupported for cloud versioned remotes
$ dvc pull
ERROR: failed to pull data from the cloud - config file error: '<command>' is unsupported for cloud versioned remotes
$ dvc fetch
ERROR: failed to fetch data from the cloud - config file error: '<command>' is unsupported for cloud versioned remotes
```

Also, the error isn't showing the command as expected.

**Comment by pmrowla** [comment]
looks like the issue here happens when using the default remote, if you are running the commands with `-r/--remote <remotename>` the error does not occur

**Comment by dberenbaum** [comment]
> Also, the error isn't showing the command as expected.

**Comment by pmrowla** [comment]
> > Also, the error isn't showing the command as expected.
> 
> See how the errors above show `<command>` instead of the actual command.
> 
> Can we fix this while we are at it? It's unclear to me what the correct behavior is:
> 
> 1. The method signature for `get_remote_odb` is wrong (why are there separate `name` and `command` kwargs?).
> 2. The `name` should be used in the error instead of the `command`.
> 3. The `command` should default to the `name` if not provided.

The `name` argument is a DVC remote name that we are loading.

The default `<command>` parameter is because we use `get_remote` and `get_remote_odb` from parts of DVC that can be called from anywhere in DVC (and not only CLI data sync commands). When we are doing actual push/pull/gc/etc operations we pass the CLI command name into the call.

`<command>` is just a filler string for the default value, since there are places that we make this call even when we are not doing `dvc push` or `dvc fetch`. In those cases we normally just silently handle this exception in DVC (since it's an expected error) and don't ever log the message with the default filler `<command>`.

The bug was that in #8662 we started raising a different exception class that was not handled properly in these expected error try/except blocks, which made us exit with the generic message
