### ISSUE TITLE
cloud versioning: enable exp push

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8675]
We can't support pushing multiple revs in cloud versioned remotes, since we will be unable to write the version IDs/etags to the .dvc files for old git commits.

This isn't a problem for fetch/pull, but we could consider disabling the multiple revs flags on fetch/pull just for parity reasons.

@dberenbaum this also means that `exp push` cannot push cache for cloud versioned remotes

_Originally posted by @pmrowla in https://github.com/iterative/dvc/issues/8673#issuecomment-1341977833_

**Comment by dberenbaum** [comment]
Related: #8678. We should be able to push without the cache. For now, we should warn/fail on trying to push the cache, noting that it's not supported for cloud versioning.

**Comment by efiop** [comment]
@dberenbaum Yeah, this one is clear, thank you! 🙏

**Comment by efiop** [comment]
Also side note: there is really no reason why we can't support multiple revs. I think it was a leftover from `worktree` considerations back in a day. As long as filesystem supports it, we can totally push different versions at the same time, but in reality, that would be tricky right now. At the same time we can totally just push rev-by-rev one-by-one without any complications. The only problem is that after the push of each rev we need to retrieve new metadata and write it down, which means that we should iterate each rev and push instead of just pushing all revs at the same time.

For now, as suggested, I'll just send a patch not to error-out when there is nothing really to be pushed and maybe we could discuss proper support as a next step.

**Comment by dberenbaum** [comment]
> there is really no reason why we can't support multiple revs.

Not sure I follow. Doesn't this still apply?

> we will be unable to write the version IDs/etags to the .dvc files for old git commits

**Comment by dberenbaum** [comment]
Yeah, for this specific issue we can. It doesn't solve doing something like `dvc push -A`, which is what I think that error was originally created for.

How much effort do you think it would take to implement this for `dvc exp push`? @pmrowla @daavoo Any thoughts on whether it would cause issues with other experiment-related features or in other products?

**Comment by efiop** [comment]
@dberenbaum Oh, I see. Yeah, I was talking about experiments only.

With `dvc exp push` there are a few levels of complication that we could choose:

1) (fastest to do, a day or two, we have all the instruments already) For each rev, create a temporary experiment (this gives us a writable git repo), `dvc push`, commit changes and we should be done. A bit worried about identifying the same experiment before and after this new commit though, but seems like it should be alright, unless I'm missing something.

Cons: pretty inefficient because of having to create an exp env and also all revs are pushed sequentially.

2)  (more correct, but needs more time than option 1) make `fs.upload` return a new `info`, so that we can get the new `etags` without doing an explicit `fs.info()` call after, and so be able to upload stuff in parallel for different revs. Another involved thing is just processing multiple `indexes`(there is one index per rev) in parallel, which is something that we need for other stuff and might get introduced soon. Also could try using virtual workspace instead of real temp experiment env.

**Comment by dberenbaum** [comment]
@efiop I think it's good to have this, but it sounds like neither option is great (either too hacky or too much work). Let's not prioritize this now and move on to other issues.

**Comment by dberenbaum** [comment]
Unfortunately, we are moving towards dropping support for version-aware remotes since there are too many broken features like this one related to it.
