### ISSUE TITLE
cloud versioning: status command

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8761]
`dvc status` or `dvc data status` should work with cloud-versioned remotes.

Edit: The scope for this ticket is limited to `version_aware` remotes.

**Comment by dberenbaum** [comment]
I'd rather have it in `dvc data status`, but there's not any support for cloud status in that command yet, so it depends on how much effort this would be

**Comment by efiop** [comment]
For the record: looking at it closer, `dvc data status` is closer to the spirit, but `dvc status` is already a trainwreck and it is easy to shove another cloud-related functionality there, but that introduces a yet another type of output and users won't be happy, esp in a newly released feature. For now trying to put it into `dvc data status` in an elegant way 🙂

**Comment by efiop** [comment]
Looks like https://github.com/iterative/dvc-data/issues/208 is also needed here to make data status use index comfortably, but trying to salvage old state db for now...

**Comment by efiop** [comment]
On second thought, I am wondering if we are making a similar mistake to `dvc status -c` back in a day by trying to shove something that doesn't really belong to `status`. Status is about your local workspace, but for cloud versioning we are using a remote workspace, so I'm wondering if what we actually want is something closer to `diff` rather than to status. For example, in git you can diff against a remote, but you can't status against it. Which makes sense, since `status` is about `index vs workspace`.

So if this should really be `dvc data diff`, it is still interesting how to designate our remote vs git revs. Maybe `dvc diff remote://mycloudversioningremote`? Or `dvc/mycloudversioningremote` or just some special `--worktree` flag or something? 🤔

**Comment by efiop** [comment]
For the record: thanks to @dberenbaum 's well-developed and documented `dvc data status` spec from half a year ago 🙏 , it is clear that cloud versioning should fit into the remote status:

![image](https://user-images.githubusercontent.com/5367102/215095350-14fe1a5f-9dda-4f17-9468-06c13d898dec.png)

![image](https://user-images.githubusercontent.com/5367102/215095399-3c07fbd6-3448-454e-a9d3-8616c4b430ff.png)

The current plan is to:

1) implement regular remote status according to the data status doc
2) add support for cloud versioning remotes (likely need `restore` functionality https://github.com/iterative/dvc-data/issues/284 first)

**Comment by efiop** [comment]
The functionality seems to fit quite nicely, but the current way it is implemented is kinda slow (we do exists calls for every object, which results in many head requests, which is slow and wasteful). Working on making it nicer and faster.

<img width="710" alt="Screenshot 2023-01-30 at 16 24 45" src="https://user-images.githubusercontent.com/5367102/215503637-e76accac-1095-43ec-ab0d-a9bf39d06ae1.png">

**Comment by skshetry** [comment]
So we are only adding a new output type? I thought it'd be more like comparing two worktrees (local and the remote).

**Comment by efiop** [comment]
@skshetry Yes, only what was specified in that data status doc. worktree scenario is out of scope for now, but we should be able to plug it into `dvc data status` later, since it is all index-based.

**Comment by skshetry** [comment]
I guess it's confusing because we call it remote, but it is also a workspace sometimes.
As `worktree` might be going away, it makes sense to only consider it as a remote as show `Not in remote`.

Otherwise, how are you supposed to compare between remote worktree index and local index (to know what will be pushed?).

**Comment by dberenbaum** [comment]
@skshetry Should we create a separate issue as a follow up to discuss?

**Comment by skshetry** [comment]
> Non-wortree case is just like remote, just funky remote.

It's a quasi-workspace too, if we push a new version, right?

**Comment by skshetry** [comment]
> @skshetry Should we create a separate issue as a follow up to discuss?

feels like this is a place to discuss exactly that, right?

**Comment by dberenbaum** [comment]
@skshetry The scope for this ticket for now is `version_aware` remotes (added a clarification at the top), so I was thinking we could have a separate issue to discuss `worktree` status.

**Comment by skshetry** [comment]
I'll pass for now as it is even outside of the scope of cloud versioning. We discussed a similar thing yesterday as well about cloud versioning, where what is being implemented is remote, not the workspace, with the names being human-readable instead of md5s (as Peter laid out in simple terms), and that solutions to improve external workspaces were offered. I do find myself confused between workspace and remotes (and I don't think I am alone).

Sorry for the noise. :(

**Comment by dberenbaum** [comment]
> The functionality seems to fit quite nicely, but the current way it is implemented is kinda slow (we do exists calls for every object, which results in many head requests, which is slow and wasteful). Working on making it nicer and faster.

Discussed with @efiop. The output (`Not in remote:`) looks good as is. 

This section can work like `git status` does for remotes. By default, it compares to whatever it has fetched from that remote. If we can make a persistent index work without too much extra effort, we can use it to do the same thing, reporting the status based on the latest persistent index by default (no flags).

We can also have a flag `--remote-update` (similar to [git remote update](https://git-scm.com/docs/git-remote#Documentation/git-remote.txt-emupdateem)) to refresh the remote index so that users check against the actual state of the remote at the time.

**Comment by efiop** [comment]
For the record: now in the upstream not-in-remote is reported by default (no more --not-in-remote flag) for both cloud versioning and regular remotes. It does so without connecting to the cloud unless `--remote-refresh` is specified (chose `refresh` over `update` for less conflict with existing terminology). For cloud versioning the experience is pretty nice because the index used is also populated by dvc push, but for regular remotes it is a bit more awkward right now, because it doesn't get populated without `--remote-refresh` for now. Regular remotes should start using index in the near future as well, but for now we are in a bit of limbo, but it is for the best ui/ux in the near future.
