### ISSUE TITLE
Automatically detect command outputs?

### ISSUE THREAD

**Issue by remram44** [iterative/dvc#931]
Hi there,

I am new to DVC, and to be frank I am still investigating options. It seems that Datalad, which is not that different a tool (if one likes git-annex), automatically detects the output of a command by simply looking at the modified files after the command run.

It seems to me that DVC can also determine changed files, based on Git status or comparing to the hash in the .dvc pointer file. Wouldn't it be possible to use those as the set of changed files? Mechanisms like inotify might also make this very efficient.

Detecting the set of inputs might be more complex, but detecting the outputs would already go a long way.

**Comment by efiop** [comment]
Hi @remram44 !

We have actually experimented with automatic outputs detection in the early versions of dvc, where we were indeed using `git status` to find newly created files and assumed that those were the outputs of the command. Since then we've decided against that approach for a few reasons:

1) Explicit is better than implicit. With automatic output detection it is pretty easy to shoot yourself in the leg if the command you are running doesn't behave as you are imagining(i.e. outputs some temporary files somewhere, that don't even matter for your pipelines). But by explicitly specifying your dependencies and outputs, you can be fully in control of building your pipeline.

2) While automatic output detection is doable when your outputs are located in your workspace on your machine, it becomes much harder when you are dealing with external outputs(e.g. you are launching a spark task on the remote host that outputs a file to hdfs) because there is no `git status` to help you and generally there is no determined workspace to scan. But with DVC and explicit approach you can simply specify your external file(s3://mybucket/data, hdfs://user@example.com/path/to/data, etc) as a dependency or an output for your pipeline stage.

3) It is not clear how to detect outputs when you are executing a few stages in parallel without mixing up their outputs.

With DVC we aim to provide a no nonsense flexible tool that allows you to manage your data and build your pipelines in the most transparent way possible. We do the tooling so you can do the magic! :slightly_smiling_face: Sorry if that is too corny :slightly_smiling_face: : 

Thanks,
Ruslan

**Comment by dmpetrov** [comment]
Thank you @efiop for the explanation of why we made this decision and got rid of all implicit dependencies logic. We could add auto\implicit dependencies later. It might be a separate project\extension or even part of DVC.

@remram44 Please let us know if you have some ideas how to generalize this. Project examples would be really helpful.

**Comment by remram44** [comment]
If running stages in parallel is an important use case then indeed I don't think there is a way to support this.

**Comment by efiop** [comment]
Closing for now as stale.
