### ISSUE TITLE
Dry run option for dvc gc

### ISSUE THREAD

**Issue by fedorn** [iterative/dvc#9330]
Can we have a dry run option for `dvc gc` so we can see what files and directories the command would delete without actually deleting it?

**Comment by efiop** [comment]
@fedorn Sure. Contributions are welcome.

**Comment by parthvnp** [comment]
Happy to work on this one!

**Comment by dberenbaum** [comment]
Related: https://discord.com/channels/485586884165107732/563406153334128681/1139483806957576212

**Comment by christian-steinmeyer** [comment]
Just used this for the first time. I was slightly discouraged by the warning message given, when no `-f` flag is present. Perhaps one could add an additional confirmational hint / don't show this warning, when running with `--dry`? (Did not open a new issue because it's a minor thing.)

```shell
> dvc gc -A --dry
WARNING: This will remove all cache except items used in the workspace and all git commits of the current repo.
Are you sure you want to proceed? [y/n]:
```

And further down the line, when there are any files found, a similar message is given:
```shell
Missing cache for directory <...> Cache for files inside will be lost. Would you like to continue? Use '-f' to force. [y/n]

**Comment by dberenbaum** [comment]
Good point @christian-steinmeyer. Opened a PR in #10061 to assume `--force` when using `--dry`.
