### ISSUE TITLE
studio: queued experiments never show as done

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9349]
Not sure whether this is a dvc, dvclive, or studio issue, but when queueing experiments and running them with the `DVC_STUDIO_TOKEN`, they never appear as done:

https://user-images.githubusercontent.com/2308172/233197450-5f7eacd5-537b-4b50-b71d-ba09de34788b.mov

I would expect the spinner in studio to stop after the experiments complete, but it never does. The video only shows until shortly after the end of the experiment, but I've verified across multiple projects that it's reproducible and that the spinner continues to show hours after the experiment completes.

**Comment by daavoo** [comment]
So, I found the bug and have a couple of ideas on how to fix it.

But, this got me thinking about whether we really need/want the Studio events in DVC at all.

The original reasons to add `start` and `done` events in DVC instead of handling everything in DVCLive were:

1. Try to send DVC information (metrics, params) beyond the scope of DVCLive.
  - Because DVCLive was not fully dependent on DVC Python lib back then.
  - Because Studio was not showing completed exp refs back then.
2. More "correctness" on when the `start` and `done` happened.
3. In preparation for a potential extension to send `stage execution` updates by DVC.

As of today, motivations for 1 no longer hold and 2 and 3 don't feel such strong reasons to me.

@dberenbaum 

Should we remove this events from DVC and make `live updates` more of a DVCLive-only thing?

**Comment by dberenbaum** [comment]
No strong opinion from me for now. I think we initially scoped live metrics as DVCLive-only, and I think it's easier to explain that way. On the other hand, we will need to keep reporting the non-DVCLive metrics and other info since that was an almost immediate request AFAIR, and I think we will need some solution for 3 before long.
