### ISSUE TITLE
data status: do not show "not in remote" status by default

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#9410]
As I have been playing with virtual operations, the fact that `data status` shows "Not in remote" statuses of files has really started bothering me. Couple that with `data status` not supporting filtering to sub-paths, it's extremely noisy.

A command meant for showing workspace status should not nag about files not being in remote by default. Also it's annoying that there's no way to turn it off.

**Comment by skshetry** [comment]
Also it's extremely annoying that there's no way to turn it off.

**Comment by efiop** [comment]
@dberenbaum But `remote-refresh` and `not-in-remote` do different things. You don't always want to refresh all the time. We should have both.

I'm a bit surprised that we are hiding remote status now, because it was meant to mimic git status and show all the useful info by default. I think this goes against the `data status` doc even? Or do you want to disable it temporarily?

**Comment by skshetry** [comment]
git status does not show anything more than if you are behind by certain commits, right?

**Comment by dberenbaum** [comment]
@efiop After having it around for a bit, it seems like including it by default is too noisy. What do you think of the approach in #9411?

Having the git-like ability to check against the "index" is nice but pretty niche. In this case, we might not want to copy git because the git status behavior for remotes is not the most intuitive or helpful. In most scenarios I know, users want the local status (what needs to be committed), and when they care about the remote status, they mostly want to check the latest of what's on the remote (what needs to be pushed).

**Comment by efiop** [comment]
@dberenbaum I'm fine with making it opt-in if that's the consensus about it. Then we need to update the doc too (i mean that data status doc that you've created in notion).

Approach in #9411 makes sense to me 👍

**Comment by skshetry** [comment]
I don't think the doc mentioned enabling this by default, just that there might be a section for the output, _Not in remote_. I see `-c` flag being used in the doc for remote statuses.
