### ISSUE TITLE
hardlink seem to be not working. I got double size for downloaded data

### ISSUE THREAD

**Issue by KietNhiTran** [iterative/dvc#942]
Hi,

I follow the tutorial to experience DVC. At step "Data file internals", https://dvc.org/doc/tutorial/define-ml-pipeline, I follow the instruction to download the dataset and take a look into the actual file size after adding the dataset into dvc. I saw that both files are not in the same inode and my local env has double file size. See below console log info

```
(dvc) XXX$ ls -i Posts.xml.tgz
3103909 Posts.xml.tgz
(dvc) XXX$ ls -i ../.dvc/cache/59/
3103662 88519f8465218abb23ce0e0e8b1384
(dvc) XXX$ du -sh .
 41M	.
(dvc) XXX$ du -sh ./..
 82M	./..
```

I found 2 issues :
- location of x.dvc file is added to current folder when using 'dvc add data/<data file>' 
- double file size in my env and 2 files (cach & actual file) are not at the same inode

It is serious issue.

**Comment by KietNhiTran** [comment]
Addition info: I am using latest vdc version : dvc 0.14.2

**Comment by KietNhiTran** [comment]
updater is not old enough to check for updates
Data file 'Posts.xml' didn't change, skipping checkout.
Checking out 'Posts.xml.tgz' with cache '5988519f8465218abb23ce0e0e8b1384'

**Comment by KietNhiTran** [comment]
Above is the outout. Sorry for the late response.

**Comment by efiop** [comment]
No worries :)

Ok, so by default when dvc is linking your data to cache, it tries 4 types of links in this order:

1) `reflink` -- The best link possible, because it is fast as hardlink/symlink, doesn't duplicate data and at the same time doesn't leave direct link from source to destination, so when you modify src(or dest) it doesn't affect dest(or src) and thus it helps eliminate even the slightest chance of cache corruption. You can think of reflinks as Copy-On-Write for files, so when a block from src(or dest) modified, filesystem automatically copies it, so the block on dest(or src) stays intact. This type of link is currently supported on the limited range of filesystems(e.g. XFS, Btrfs, APFS, etc) and looks like you are running one of those. It is also important to note, that `du` utility counts reflinks as a copy and thus showing you that your directory is twice the expected size, but if you check the amount of available space left on your drive, you could see, that only 41M was taken, not 82M. Also, the inode is not the same(as it would be with hardlink) because the underlying reflink mechanism works on a smaller scale and thus inode of the src doesn't match the dest;
2) `hardlink` -- this is the link type we use if reflink is not supported and your cache directory and your work directory are located on the same partition;
3) `symlink` -- this is the link type we use if your cache directory and your work directory are located on different partitions(i.e. cache is on HDD, but workspace is on SSD);
4) `copy` -- this is the link type we use if for some reason non of the above links work;

Thanks,
Ruslan
