### ISSUE TITLE
gdrive push: insufficient permissions for the specified parent

### ISSUE THREAD

**Issue by entbappy** [iterative/dvc#9761]
![image](https://github.com/iterative/dvc/assets/68845761/7fbfd284-d66e-4ecc-aa5d-fd83bdc15847)

```
ERROR: failed to transfer '29b074fb2ff2463f2f80c521d5d3cfd3' - <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files?supportsAllDrives=true&alt=json returned "Insufficient permissions for the specified parent.". Details: "[{'message': 'Insufficient permissions for the specified parent.', 'domain': 'global', 'reason': 'forbidden', 'location': 'parent.permissions', 'locationType': 'other'}]">
```

When i am trying do dvc push i am having this issue. For the very first time, it worked with my another google drive but when I am changing it to other google drive I am having this issue. Please suggest me what to do with this. How to resolve it

**Comment by pmrowla** [comment]
If your two gdrive remotes use the same client ID, you need to specify separate profile names for each remote, otherwise they will both try to use the same default profile (and you will only have valid credentials for the initial remote that you configured). See the docs for how to set `profile` on gdrive remotes: https://dvc.org/doc/user-guide/data-management/remote-storage/google-drive#configuration-parameters

**Comment by entbappy** [comment]
![image](https://github.com/iterative/dvc/assets/68845761/a67b0f61-7006-4099-a68f-2bb6ae183f63)


Got the solution,, I have given edit access here, now its working  😅
