### ISSUE TITLE
benchmark regressions

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9914]
Investigate regressions in https://github.com/iterative/dvc-bench for:

- [ ] push (sometime between 3.10 and 3.20)
- [x] ~plots~
- [x] ~exp show~
- [x] pull (after 3.20)
- [x] checkout

**Comment by dberenbaum** [comment]
Makes sense, so we only need to investigate `push`

**Comment by dberenbaum** [comment]
Added `pull` based on issues since 3.20

**Comment by pmrowla** [comment]
It looks like the issue for both fetch and push is with index collection - specifically the problem is that sqltrie traverse is slow.

This is a local fetch of the cats_dogs dataset in main, using 3.10.0 (without the index collection) the fetch only takes 10.3s:
![Screenshot 2023-11-15 at 5 46 47 PM](https://github.com/iterative/dvc/assets/651988/710d9fab-a279-4446-a82c-015274d6ee09)

Caching the `sqltrie._traverse()` results in memory cuts the fetch time in half, but the real issue is that the underlying script to generate the temporary steps tables for traversal has to be called once per file, and that temp table generation is the main performance blocker. (the caching cuts the runtime exactly in half because we are calling traverse twice per file)

So fixing this will require revisiting how the sqltrie traversal queries work. Or maybe we need to consider only using sqltrie for dump/load and then do all of our index operations in memory. cc @efiop

**Comment by pmrowla** [comment]
Actually it looks like we can probably just get away with building an in-memory pygtrie for sqltrie views, since views are the only place we heavily use traverse right now

**Comment by pmrowla** [comment]
Yes, all the pull regressions should be resolved after the sqltrie changes.

**Comment by pmrowla** [comment]
bench.dvc.org is up to date now, pull regressions have been resolved but it looks like push has still regressed since 3.10

![pull](https://github.com/iterative/dvc/assets/651988/8de29e11-141b-44c7-949f-9128f92e5558)
![push](https://github.com/iterative/dvc/assets/651988/cc95c05e-fe05-4630-ad6c-e9d08e5f9296)

**Comment by efiop** [comment]
Switched pull -> fetch and there is no regression for local:

```
---------------------------------------------------------------------------- benchmark 'test_fetch-fetch': 5 tests ----------------------------------------------------------------------------
Name (time in s)                  Min                 Max                Mean            StdDev              Median               IQR            Outliers     OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_fetch-fetch[2.58.2]     112.4179 (1.0)      112.4179 (1.0)      112.4179 (1.0)      0.0000 (1.0)      112.4179 (1.0)      0.0000 (1.0)           0;0  0.0089 (1.0)           1           1
test_fetch-fetch[3.0.0]      118.5058 (1.05)     118.5058 (1.05)     118.5058 (1.05)     0.0000 (1.0)      118.5058 (1.05)     0.0000 (1.0)           0;0  0.0084 (0.95)          1           1
test_fetch-fetch[main]       118.[67](https://github.com/iterative/dvc-bench/actions/runs/7022369198/job/19106534095#step:5:68)35 (1.06)     118.6735 (1.06)     118.6735 (1.06)     0.0000 (1.0)      118.6735 (1.06)     0.0000 (1.0)           0;0  0.0084 (0.95)          1           1
test_fetch-fetch[3.10.0]     119.21[71](https://github.com/iterative/dvc-bench/actions/runs/7022369198/job/19106534095#step:5:72) (1.06)     119.2171 (1.06)     119.2171 (1.06)     0.0000 (1.0)      119.2171 (1.06)     0.0000 (1.0)           0;0  0.0084 (0.94)          1           1
test_fetch-fetch[3.20.0]     119.2340 (1.06)     119.2340 (1.06)     119.2340 (1.06)     0.0000 (1.0)      119.2340 (1.06)     0.0000 (1.0)           0;0  0.0084 (0.94)          1           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

but there is for checkout, which we already knew.

**Comment by efiop** [comment]
Same for real clouds:

<img width="440" alt="Screenshot 2023-11-29 at 09 46 20" src="https://github.com/iterative/dvc/assets/5367102/1c87a4c0-0501-4aa2-ad7a-39d8d37ad1cb">

<img width="445" alt="Screenshot 2023-11-29 at 09 46 31" src="https://github.com/iterative/dvc/assets/5367102/50bfbf1a-88c1-4e1b-841b-10be3dd410e4">

<img width="436" alt="Screenshot 2023-11-29 at 09 46 47" src="https://github.com/iterative/dvc/assets/5367102/219d5e99-a041-4750-b2ba-f718b67ecd64">

So it is not pull, it is checkout. Let's leave checkout out of this issue. So only `push` left to check here.

**Comment by dberenbaum** [comment]
Why not add `checkout` to the list? It looks like that is a significant regression.

**Comment by efiop** [comment]
@dberenbaum Ah, let me just clarify that I meant to leave it out of the current optimization effort considering the schedule. Unlike fetch/push which migrated to index fully, checkout also relies quite a bit on what we do with `state` and other things, so, even though I don't oppose taking another look there right now, we will absolutely need to take a look at it once `state` is removed. At least things like noop and update haven't regressed much.

<img width="1413" alt="Screenshot 2023-11-29 at 16 32 01" src="https://github.com/iterative/dvc/assets/5367102/9b018392-64ea-4f31-9798-bfac11c9bcfe">

**Comment by efiop** [comment]
For the record: I'm taking a look at checkout.

**Comment by dberenbaum** [comment]
Discussed with @efiop and summarizing here. Let's do our best to finalize the major changes needed around index so dvc 3.x can be in a better place and so it doesn't drag into next year as a major project. That means prioritizing both push and checkout here, and more generally removing state and migrating checkout and add to use index (@efiop please correct me if I'm wrong).

**Comment by efiop** [comment]
Another thing to note: only `copy` link degraded, `symlink` and `hardlink` are actually better than before 3.0 and they are pretty stable:

<img width="1383" alt="Screenshot 2023-11-30 at 00 52 43" src="https://github.com/iterative/dvc/assets/5367102/67841c46-5ad4-4e17-9ebf-836f06fcf482">
<img width="1394" alt="Screenshot 2023-11-30 at 00 52 55" src="https://github.com/iterative/dvc/assets/5367102/41711b50-5a4a-4a2c-9f54-4796c7be8b42">

and locally on macOS I can also see `checkout` with `reflink` being almost twice as fast as 2.58.2 was. Looking into `copy`, but will probably post a summary on it in the morning.

**Comment by efiop** [comment]
Ok, so for the record: with small files (esp the ones in mnist) the overhead of callback creation in https://github.com/iterative/dvc-objects/blob/231e5273cf929cea2424c9d6e885f72bb5d90750/src/dvc_objects/fs/utils.py#L167 is just too wasteful and even besides that it is unnecessary. There are a few things that we can do there as well, but even that alone speeds up link creation for me by like 50+ times. reflink/hardlink/symlink bypass that thus not suffering from the overhead. I'll send some patches in the morning.

**Comment by skshetry** [comment]
What changed between 2.58.2 and 3.0.0? The callback was still there before that, no?

**Comment by efiop** [comment]
The main thing that changed is https://github.com/iterative/dvc/pull/9444 . Before it we were processing files one-by-one and passing them to `generic.transfer()`, while after it, among other things, we are passing _all_ files that we need to create to `generic.transfer()` which makes it use a bit more overhead in different places down the line.

This is a bit early, but I've sent a few more fixes and now, at least on my linux machine, it looks like we are not only back to 2.58.2, but actually faster too (~30sec vs ~37sec for mnist checkout). Waiting for proper confirmation in dvc-bench https://github.com/iterative/dvc-bench/actions/runs/7066555049/job/19239201268

**Comment by efiop** [comment]
Ok, so looks promising so far.

<img width="287" alt="Screenshot 2023-12-02 at 03 11 27" src="https://github.com/iterative/dvc/assets/5367102/cf111301-d6f7-4ae7-b325-cf1411419b0d">

3.20 also improved because it also installed new dvc-objects version. So indeed, checkout-copy is now faster than it was in 2.x - 

But because we've unified all transfer-like logic in the past year, we also get these improvements in other commands that use this same code. E.g. fetch from local remote is now 2.5 times faster than it was.

<img width="240" alt="Screenshot 2023-12-02 at 03 13 21" src="https://github.com/iterative/dvc/assets/5367102/0a2c2d20-30da-4858-a998-2c27c2e4fb31">

and push to local remote is now ~2 times faster than before and over 4 times faster than in 2.x

<img width="217" alt="Screenshot 2023-12-02 at 03 16 20" src="https://github.com/iterative/dvc/assets/5367102/e0063562-5bbb-40bc-b629-4ec6093a2b1c">

and dvc get-url

<img width="216" alt="Screenshot 2023-12-02 at 03 18 42" src="https://github.com/iterative/dvc/assets/5367102/82ec7d88-aa45-4fc4-81c1-cc19f6fc521f">

and dvc import-url

<img width="284" alt="Screenshot 2023-12-02 at 03 19 17" src="https://github.com/iterative/dvc/assets/5367102/12043c78-bb1f-4241-a5de-b78c8fdd2372">

and a few more. We'll see on on bench.dvc.org once ready.

**Comment by skshetry** [comment]
Great work, @efiop. The only thing that I want to mention is that, https://github.com/iterative/dvc-objects/pull/231 is going to make it slower for users with large files. So we should benchmark on that kind of datasets to be sure. ThreadPoolExecutor has high overhead for small files, but that is noise for larger files which take a lot of time. Parallellizing also help SSDs as they have a lot of bandwidth, and HDDs in planning in their shortest route.

**Comment by skshetry** [comment]
Maybe it's time to write checkout in rust? 😉

**Comment by dberenbaum** [comment]
Can we test on some dataset like https://www.kaggle.com/datasets/thedevastator/open-orca-augmented-flan-dataset? We don't need to put them into our regular benchmarks but would be good to test it out this time to see how these changes perform on a large file.

**Comment by efiop** [comment]
Sorry for the delay, was AFK.

Indeed, we should benchmark other datasets as well, no doubt about that. And we should perform well in both cases, mnist is a very good edge case for that. We can pick smarter strategies based on what we are dealing with.

OpenOrca seems pretty good for testing a dataset that has 1 file that is big-ish, we should definitely add it to the dvc-bench datasets so that we have it around at our disposal, I'll upload it later today 👍 . I was also looking into some famous/well-known video/sound/other catalogue-looking datasets to test many (but not too many, maybe up to 10-100) of big-ish files (so typical classification datasets won't do), to test a bit beyond that. Those videos have to be non-copyright ones, so youtube-based ones won't do. If you have ideas - let me know.

**Comment by efiop** [comment]
@dberenbaum It is very nice to have it in the toolset generally, but it also allows us to trigger `dispatch` runs in CI. I've also added a smaller one `used-cars` dataset and it is even faster to run than mnist (i mean total time) https://github.com/iterative/dvc-bench/actions/runs/7087497084 , so we can probably run something chunkier on a regular basis, just need to figure out how/where to post. I'll also add a dataset like the one I was talking about above later.

**Comment by efiop** [comment]
For the record, some benchmarks with different datasets:

mnist (70K+ ~300B images)

https://bench.dvc.org/schedule/7147613411_2.html

xray (6K ~30KB images)

https://bench.dvc.org/workflow_dispatch/7151367965_3.html

used-cargs (1.4G single file)

https://bench.dvc.org/workflow_dispatch/7146419624_1.html

**Comment by dberenbaum** [comment]
Worth noting that these are not "real" benchmarks for older versions though since those may be benefitting from updates to dvc-objects and other libs, right?

**Comment by dberenbaum** [comment]
So overall, it looks like it's a great improvement but we are trading off some performance on big files to get improvements on many small files. Is that right?

**Comment by dberenbaum** [comment]
Any updates here? What about s3? Any idea why it doesn't show the same improvements as other clouds in the benchmarks?

**Comment by efiop** [comment]
Sorry, I was convinced I responded before, but probably forgot to post.

> Worth noting that these are not "real" benchmarks for older versions though since those may be benefitting from updates to dvc-objects and other libs, right?

Yes, mostly recent versions as very old ones will have more strict requirements.

> So overall, it looks like it's a great improvement but we are trading off some performance on big files to get improvements on many small files. Is that right?

Marginally in `used-cars`, but there is no benchmark with many big files which should be more affected.

> Any updates here? What about s3? Any idea why it doesn't show the same improvements as other clouds in the benchmarks?

No updates, haven't looked into this since the last time 🙁 s3 is likely because of chunking configuration (similar to improvements that @pmrowla did in adlfs in the past), but haven't looked into it.

**Comment by dberenbaum** [comment]
@pmrowla Any thoughts on the s3 performance? I'd like to look into that either as part of this issue or a new one.

Is there anything else left before closing this issue?

**Comment by pmrowla** [comment]
@dberenbaum this can be closed, we have a separate issue for the s3 performance https://github.com/iterative/dvc/issues/9893
