### ISSUE TITLE
Delay indexing

### ISSUE THREAD

**Issue by johnyaku** [iterative/dvc#9982]
Indexing large datasets can take hours, as discussed in #9813.

While having an index may provide net efficiencies in the long term, having to wait hours just to checkout a branch can be extremely frustrating. 

This request is for an option to skip indexing, which could then apply to all operations that including an indexing step, including `add`, `checkout`, and `import`. 

We can then run `dvc status` overnight to build the index and make future operations more efficient.

**Comment by dberenbaum** [comment]
Based on what I have seen in https://github.com/iterative/dvc/issues/9813#issuecomment-2037303874, I don't think delaying indexing will be that helpful, since the underlying operations that are taking most of the time aren't directly tied to indexing. I think it will be better to focus on the issues noted there.
